### ISSUE TITLE
Is it possible to make certain graphs available on a public/per user basis?

### ISSUE THREAD

**Issue by KawaiiPotato** [firehol/netdata#1061]
My current Netdata implementation is behind Nginx to provide authentication, is it possible to (for example) make IPv4 I/O data publicly available on my homepage, while keeping all other graphs behind authentication?

**Comment by ktsaou** [comment]
I am not an expert on nginx. I guess it can be done, but since there are many files involved, it would be tricky.

I would for something like that:

1. allow netdata to be publicly available at the url.

2. download `/api/v1/charts` from netdata and remove all the charts you don't want to publish. Put the result somewhere on your nginx (as `charts.json`).

3. rewrite all requests to `/api/v1/charts` to go to the location of the saved file.

  Up to this point, anyone accessing the public netdata dashboard will get just one chart. Of course, if he knows other charts, he can access them by writing the URLs by hand. Let's fix that.

4. deny all requests to `/api/v1/chart` and `/api/v1/data` that do not include `?chart=ipv4.net` (or the allowed charts).

  This means a bad guy will not be able to query other charts, even if he knows they exist.

5. deny all other requests to `/api/`.

  This will protect all other functions, like the registry, alarms, etc.

If anyone knows how to translate these into nginx statements, please help...

**Comment by ktsaou** [comment]
I edited my response above.

**Comment by shadycuz** [comment]
This looks very doable. I have not thought about making certain charts available. I will give this a shot and post back.

**Comment by shadycuz** [comment]
> rewrite all requests to /api/v1/charts

```
location /api/v1/charts {
         alias /path/to/modified/charts
         allow all; #might not be needed I use Auth on my netdata sites.
        }
```
I haven't actually spent much time looking at the web side of netdata. The above should work. I have not tested it but will attempt to overnight.

**Comment by shadycuz** [comment]
@ktsaou So the nginx portion works. As you can see from the screen shot I only have 2 charts in my new public facing demo site. The site doesn't render however. The console does show a Uncaught TypeError. It is possible my nginx config is not set up right, or that I messed the json structure up when I was cutting charts from it. 
![image](https://cloud.githubusercontent.com/assets/17090999/19298258/2ce3e2c0-901a-11e6-8cc5-b8d7655a3f83.png)

Site is empty 
![image](https://cloud.githubusercontent.com/assets/17090999/19298351/d326d016-901a-11e6-8ea9-72451e9ecf57.png)

here is my json

**Comment by shadycuz** [comment]
So this is only really useful for someone with one Netdata site. If they want to use the Nginx proxy config found in the wiki then some type of regex will have to be added. So you can serve a charts.json to each backend server, because when I download /api/v1/charts from my normal server I noticed the Hostname is hard coded into it. 

```
 location ~ /netdata/(?<behost>.*)/(?<ndpath>.*) {
        #auth_basic "Protected";
        #auth_basic_user_file passwords;

        location ~ /api/v1/charts {
         alias /var/www/demo/api/v1/charts;
         allow all; #might not be needed I use Auth on my netdata sites.
        }
```

I'm pretty sure you would just need to modify the above to say 

```
 location ~ /netdata/(?<behost>.*)/(?<ndpath>.*) {
        #auth_basic "Protected";
        #auth_basic_user_file passwords;

        location ~ /netdata/*insert_backend_host*/api/v1/charts {
         alias /var/www/demo/*insert_backend_host*/charts;
         allow all; #might not be needed I use Auth on my netdata sites.
        }
```

As soon as we determine why the site is not loading I will continue to work on the nginx config part. Ps. I still see the alarms?active in the chrome console. But the site is still blank.

**Comment by ktsaou** [comment]
> The console does show a Uncaught TypeError.

hm... For some reason javascript does not read the json properly. I suspect that your json is not returned with the right mime content type.

Can you save to the file the whole `/api/v1/charts` response, without touching it? If it still breaks, nginx needs a content type for `.json` files.

**Comment by shadycuz** [comment]
I tried the default chart file and the out come is the came. I have checked the mime config file and it has an application/json   json;   listing.

**Comment by ktsaou** [comment]
> I tried the default chart file and the out come is the came. I have checked the mime config file and it has an application/json json; listing.

hm... could you please verify that it is really served with the proper mime type. Get the live version and the file version and compare their headers.

**Comment by shadycuz** [comment]
You are right, in the response I'm getting 

`Accept-Ranges:bytes
Connection:keep-alive
Content-Length:145007
Content-Type:application/octet-stream
Date:Thu, 13 Oct 2016 02:38:28 GMT
ETag:"57fdea9d-2366f"
Last-Modified:Wed, 12 Oct 2016 07:47:41 GMT
Server:nginx/1.11.4`

I have tried several things in Nginx to force mime type of json and nothing has worked. I might have to break down and ask stackexange for some assistance.

**Comment by ktsaou** [comment]
Cleaning up. If there something pending, let me know.
This is related to #2636
