### ISSUE TITLE
Removing sections of netdata html

### ISSUE THREAD

**Issue by Codgedodger** [firehol/netdata#1097]
Finally got my reverse proxy setup with netdata and works amazing!

I just want the "System Overview" section from the netdata for my users to see what is going on with the server. I don't want them to see all of the user names nor more in depth processes. Just having the system overview information would be absolutely perfect. 

I have tried to modify the /etc/netdata.conf and committing out some of the sections but having no luck on the reload. What would be the easiest way of doing this?

**Comment by ktsaou** [comment]
Create a custom dashboard, like `/tv.html` as e.g. `/default.html`, then make your web server to rewrite `/` to `/default.html`.

This is how I run http://my-netdata.io

**Comment by shadycuz** [comment]
@ktsaou What we could really use is some kinda pre-built NOC/Tv dashboard. Something that auto generates the servers based on our my-netdata menu. Something similar to [Spice Works](http://wahlnetwork.com/wp-content/uploads/2014/12/sw-monitor.jpg) . We could have the health alerts that we have now but also cause the chart to pop up on the main NOC page. I need to start looking into this for my work.

**Comment by MelkorLord** [comment]
Hi,

I'd really love netdata providing an equivalent of "index.html" but without any kind of reference to the registry! It's rather painful to sync the defaut index.html to a custom one stripped of everything registry related with every release.

I don't want my servers to phone home anywhere to anyone, let alone notify their online presence to any third party.

Would it be possible to provide such an alternative HTML file (ie: "noreg.html") that would be identical to the "index.html" but without any reference to the registry?

**Comment by ktsaou** [comment]
why don't you configure one of your netdata as the registry?
It is just 1 line in netdata.conf to do this.

**Comment by ktsaou** [comment]
> @ktsaou What we could really use is some kinda pre-built NOC/Tv dashboard. Something that auto generates the servers based on our my-netdata menu. Something similar to Spice Works . We could have the health alerts that we have now but also cause the chart to pop up on the main NOC page. I need to start looking into this for my work.

I plan to do this on the standard dashboard, using the registry. So, a button will appear on all netdata servers, which will query all the netdata installations you know and provide a high level dashboard of all your netdata installations.

Also, I plan to allow you pin charts on the dashboard, which will be transferred from netdata to netdata via the registry and then allow you to customize a dashboard (i.e. resize and move the charts) using the pinned charts, which will be saved at the registry.

So, guys you need a registry... You can have yours if you are concerned about contributing your usage data to the project. The registry is a key component to distributed monitoring. So, use one.

**Comment by shadycuz** [comment]
I wish I could be of more help on the development of netdata. My
programming skills are only so so. When I look at some of the code I
understand parts but not how it works as a whole. I need to really take a
look at the code base but life ya know. I work in networking, and most of
my free time has been going into the new CCNA or learning python. I use the
public registry but I was planning eventually to use the self hosted one
for speed. You guys do have something special here. I love Netdata.

**Comment by MelkorLord** [comment]
> why don't you configure one of your netdata as the registry?
It is just 1 line in netdata.conf to do this.

Before replying, I experimented a bit :-) I don't really see the benefit of a **central registry** for a number of reasons.

- My browser is configured to delete all cookies upon exit. I've checked, everytime I open my browser on netdata and go to "my-netdata -> settings" (right to "What is this?") I get a new ID which is expected. I haven't tested with multiple servers yes but I guess that this menu won't reflect the real list of servers. I'll only get the current one thanks to the "new" ID. If I open every "netdata" URL on that particular browser session, the menu will fill up but as soon as I close the browser, everything will be lost.

- I manage quite a bunch of servers but they mainly are unrelated to each other which means that there's little reason to have a central registry.

- Nonetheless, I found a suitable usage upon experimenting. Using each server as its own registry seems useful for the alert emails :-) When such an email is received, the `View NetData` button points to the right URL and I get the related chart displayed instead of `Sorry... your account is not linked to a netdata server named: <server-name>` when the registry is disabled.

So I guess I'll use the registry on a per-server basis to benefit from the email alerts.

**Comment by ktsaou** [comment]
That is a good use.

I am trying to figure a way to add OAUTH to netdata, so that only one netdata will know the usernames and passwords. The others will just obey to that one. Using this feature, you will login to the registry and your server list will re-appear - the registry will give you again the same GUID, after authentication.

Using registries you can build farms of servers. So, if you manage 20 farms of servers, each of them can be autonomous and private. This would be even more interesting in cases where the registry pushes all the servers to all the viewers (for example to share the dashboards with different sysadmin teams, or even customers).

**Comment by MelkorLord** [comment]
That's a very good idea! If you even manage to add some kind of ACLs, we could give partial access to third parties, be it direct panels view on netdata or just API calls to display on their own environment. This is indeed a very nice enhancement.

**Comment by ktsaou** [comment]
> If you even manage to add some kind of ACLs, we could give partial access to third parties, be it direct panels view on netdata or just API calls to display on their own environment.

Yeap. This is going to be done with API keys that will grand the caller access to specific charts.

**Comment by ktsaou** [comment]
Cleaning up: I am closing this. I think there are open tasks/projects for everything mentioned here. If you believe there is something missing, let me know and I'll re-open it.
