### ISSUE TITLE
Question about the charts

### ISSUE THREAD

**Issue by ConsoleTVs** [firehol/netdata#1112]
I am the owner of a library that makesuse of a lot of charts, what are the chart libraries used for netdata? From gauges to plots, everything!

**Comment by ktsaou** [comment]
All of them are here with my comments: http://london.my-netdata.io/dashboard.html

**Comment by ConsoleTVs** [comment]
Thanks a lot!

**Comment by ktsaou** [comment]
keep in mind only dygraphs, easypiechart and gauge.js are finally used.
I have integrated the others, but they were not good enough for what I needed.

**Comment by ktsaou** [comment]
I see in this repo: https://github.com/ConsoleTVs/Charts
a lot of other chart libraries. Have you done any benchmark on them for their performance?

In general I need chart libraries that:

1. are super fast (the URL I gave you above measures their timings too). They chart libraries should support a way of giving them data is raw format that will directly be used for rendering, without any processing.

  I also tried to measure their concurrency (although I don't have visible metric for that). For example, if you fill a page with dozens of charts, gauge.gs animation is horrible, while easypiechart animation is smooth.

2. their hover can be intercepted and propagated to other charts (so that when you hover a chart, the others show the same selection)

3. pan and zoom operations can be intercepted and controlled externally, via javascript, so that panning or zooming one, can allow the others to follow.

What would interesting for netdata, which none of the ones I have seen so far supports, is incremental addition of data, so that instead of re-drawing the whole canvas on every update, the canvas is shifted and just few points are added. This is will significantly lower the browser CPU pressure for netdata.

**Comment by ConsoleTVs** [comment]
I have not tested any performance on it since you're the one who selects what things do you want to be outputted and choose the library you want, so in that case you're the one choosing the best for either speed or fancyness, anyway, I'll try to add some more in the following days because I had no idea about 2 of the ones you had in your site! Thanks a lot!
