### ISSUE TITLE
Possible to have netdata show host latency with fping

### ISSUE THREAD

**Issue by Dedsec1** [firehol/netdata#1122]
i know netdata can monitor alot of things but iam curious to see if netdata can show remote host latency via fping or even smokeping.  my guess an custom plugin would need to be created for it but iam kind of stuck on how i would get the plugin to read out the latency for each host.

**Comment by ktsaou** [comment]
Hi, I have submitted PR https://github.com/schweikert/fping/pull/105 to fping to allow it become a netdata plugin.

You will need a wrapper script.

In the mean time, you can use it like that:

1. download the install the modified version of fping:

  ```sh
cd /usr/src
git clone https://github.com/ktsaou/fping.git fping-netdata.git
cd fping-netdata.git
./autogen.sh
./configure --prefix=/usr/local
make
cp src/fping /usr/local/bin/
chown root:root /usr/local/bin/fping
chmod 4755 /usr/local/bin/fping
```

2. copy the script I posted to https://github.com/schweikert/fping/pull/105 as `/usr/libexec/netdata/plugins.d/fping.plugin`. Make sure it is executable and owned by user `netdata`.

3. create the file `/etc/netdata/fping.conf` and add these contents:

   ```
fping="/usr/local/bin/fping"
hosts="host1 host2 host3 host4"
```

4. restart netdata and 3 new charts per host will appear in the dashboard.

If you have any problems, do `cat /var/log/netdata/error.log | grep fping`. It should tell you what the problem is.

**Comment by Dedsec1** [comment]
thanks for the fast reply,  i got the charts working and should be working well, thanks for an great tool as well.

**Comment by Dedsec1** [comment]
just another question , how can i organize each chart into different categories such as for different providers or different locations.   like how netdata has one main folder for networking then has the charts listed below.

**Comment by ktsaou** [comment]
> just another question , how can i organize each chart into different categories such as for different providers or different locations. like how netdata has one main folder for networking then has the charts listed below.

not that easy with the current dashboard.
It could be easier to create a custom one. Check `http://your.netdata.ip:19999/tv.html`. You can copy that file and edit it to create a custom dashboard according to your needs. It is plain html, no javascript required.

**Comment by Dedsec1** [comment]
cool, will look into that, iam not even sure if this is even possible with netdata but what if their was an chart that showed current network traffic via tcpdump or even netcat?  i think it would be kind of cool but  my guess it would take an good chuck of resources.
