### ISSUE TITLE
loopsleepms.sh.inc: invalid timeout specification

### ISSUE THREAD

**Issue by vpashka** [firehol/netdata#1177]
This is normal?  netdata-1.4.0

16-10-28 23:12:44: INFO: netdata: executing command: 'exec /usr/lib/netdata/plugins.d/tc-qos-helper.sh 1' on pid 3749.
/usr/lib/netdata/plugins.d/loopsleepms.sh.inc: line 95: read: 0.977: invalid timeout specification
/usr/lib/netdata/plugins.d/tc-qos-helper.sh: Cannot use read for sleeping (return code 1).
16-10-29 00:12:46: INFO: netdata: executing command: 'exec /usr/lib/netdata/plugins.d/tc-qos-helper.sh 1' on pid 16264.
/usr/lib/netdata/plugins.d/loopsleepms.sh.inc: line 95: read: 0.978: invalid timeout specification
/usr/lib/netdata/plugins.d/tc-qos-helper.sh: Cannot use read for sleeping (return code 1).

**Comment by ktsaou** [comment]
which distribution do you use?

**Comment by ktsaou** [comment]
This is what is happening:

1. in shell scripts to sleep for some time, you have to call `sleep`. Since netdata does per-second data collection, it has to call sleep once every second. This is bad.
2. to solve it, netdata uses the `read` command for sleeping. The `read` command is internal - already present into BASH, so this call is very light and preferred for sleeping.

It seems however, that your system does not a compatible `read`. The good news is that netdata found out and switched to the less efficient `sleep`. So, everything should be working for you, but not optimal. This is why I asked for your Linux distribution.

**Comment by vpashka** [comment]
I use ALT Linux. Maybe your code waits for bash v.4  It is not the default in my linux.

[root@pvbook ~]# bash --version
GNU bash, version 3.2.57(1)-release (i586-alt-linux-gnu)
Copyright (C) 2007 Free Software Foundation, Inc.
[root@pvbook ~]# 

But bash 4 is also installed on the system.

**Comment by vpashka** [comment]
Perhaps somewhere you need to write
#!/usr/bin/env bash4

**Comment by ktsaou** [comment]
It is checked here: https://github.com/firehol/netdata/blob/master/plugins.d/charts.d.plugin#L110

Bash 4 was released Feb 2009.
Why do you use bash 3?

**Comment by vpashka** [comment]
I dont know :)
But this version of the default in my distro ..

**Comment by vpashka** [comment]
> It is checked here: https://github.com/firehol/netdata/blob/master/plugins.d/charts.d.plugin#L110
I blame myself. In this file, I corrected test on the "#!/usr/bin/env bash4"
maybe I still something broke in charts.d.plugin

**Comment by vpashka** [comment]
In any case, thanks for the reply! You have a great project. I really like him.

**Comment by ktsaou** [comment]
thanks!
