### ISSUE TITLE
Access to file '/usr/share/netdata/web/index.html' is not permitted.

### ISSUE THREAD

**Issue by haasn** [firehol/netdata#1199]
```
λ curl http://localhost:19999
Access to file '/usr/share/netdata/web/index.html' is not permitted.%

λ ps aux | grep netdata
netdata   5935  0.5  1.3 597112 455092 ?       Ssl  11:19   1:06 /usr/sbin/netdata -D
netdata   6148  0.3  0.0 122492 18288 ?        Sl   11:19   0:35 /usr/lib/python-exec/python2.7/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
netdata   6151  1.3  0.0  16944  3948 ?        S    11:19   2:32 /usr/libexec/netdata/plugins.d/apps.plugin 1
netdata   6152  0.0  0.0  15972  3024 ?        S    11:19   0:01 bash /usr/libexec/netdata/plugins.d/charts.d.plugin 1
nand     21148  0.0  0.0  10168   960 pts/5    S+   14:32   0:00 grep -i --color=auto netdata
netdata  30724  0.0  0.0  15628  2884 ?        S    14:19   0:00 bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1

λ ll /usr/share/netdata/web/index.html
-rw-r--r-- 1 netdata netdata 1.3Mb Oct 31 16:05 /usr/share/netdata/web/index.html

λ sudo -u netdata file /usr/share/netdata/web/index.html 
/usr/share/netdata/web/index.html: HTML document, UTF-8 Unicode text, with very long lines

λ eix -I netdata
[I] net-analyzer/netdata
     Available versions:  (~)1.2.0-r1 (~)1.3.0 (~)1.4.0 **9999 {+compression +filecaps mysql nfacct nodejs +python CPU_FLAGS_X86="sse2" PYTHON_TARGETS="python2_7 python3_4 python3_5"}
     Installed versions:  1.4.0(16:05:39 2016-10-31)(compression filecaps nfacct python -mysql -nodejs CPU_FLAGS_X86="sse2" PYTHON_TARGETS="python2_7 python3_5 -python3_4")
     Homepage:            https://github.com/firehol/netdata https://my-netdata.io/
     Description:         Linux real time system monitoring, done right!


λ cat /etc/os-release 
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
```

**Comment by haasn** [comment]
```
==> /var/log/netdata/access.log <==
16-11-02 14:35:12: 1: 127.0.0.1 port 57408 connected on thread task id 31849

==> /var/log/netdata/error.log <==
16-11-02 14:35:12: ERROR: netdata: 1: File '/usr/share/netdata/web/index.html' is owned by user 145 (expected user 0). Access Denied.

==> /var/log/netdata/access.log <==
16-11-02 14:35:12: 1: (sent/all = 68/68 bytes -0%, prep/sent/total = 0.12/0.04/0.16 ms) data: 403 '/'
16-11-02 14:35:12: 1: 127.0.0.1 port 57408 disconnected from thread task id 31849
```

It works after a `chown -R root /usr/share/netdata`. Possible packaging issue?

**Comment by ktsaou** [comment]
Can you post the `[global]` section of your `/etc/netdata/netdata.conf`

**Comment by haasn** [comment]
@ktsaou 

```
[global]
	run as user = netdata
	web files owner = root
	web files group = netdata
        memory deduplication (ksm) = yes
        history = 28800
        memory mode = ram
```

The first three lines were there by default when I installed the package.

**Comment by ktsaou** [comment]
@candrews it seems that the package shipped with gentoo has wrong permissions on `/usr/share/netdata`. It installs this directory as `netdata:netdata` but the default configuration installed requires `root:netdata`.

Can we fix it?

**Comment by candrews** [comment]
The gentoo packaging does not install `/etc/netdata/netdata.conf` - so if a user has it, they got it by means other than the gentoo packing. Also, without `/etc/netdata/netdata.conf` netdata works with the owner of `/usr/share/netdata` being `netdata`.

Here are the options I've come up with:
* I change the owner of `/usr/share/netdata` to `netdata`. This breaks all existing installations.
* I change the owner of `/usr/share/netdata` to `netdata`  and also install `/etc/netdata/netdata.conf` from the system/netdata.conf the build system makes.

I think I'll have to do the second option.

Also, I think netdata should be changed so that it's internal default configuration matches the system/netdata.conf it distributes. Right now, if netdata.conf doesn't exist, netdata behaves as if `web files owner = netdata` but the "default" configuration file you distribute says `web files owner = root` - that's awfully confusing.

**Comment by ktsaou** [comment]
hm... well, I think that by `the "default" configuration you distribute`, you mean `contrib/debian/netdata.conf`.

There was a very long discussion about this file at #132 

The debian folks believe the web files should not be owned by the user netdata runs, to prevent an attack that could possibly write something there in order to fill the disks. They suggested these files should be owned by `root`.

There is no mechanism in netdata to write to these files and directories and I find the the risk of having netdata read files owned by `root` as unacceptable. netdata already implements checks to prevent reading files outside `/usr/share/netdata/web`, but I needed another check in case there is another method of reaching any other directory via a netdata URL (except `..` - this is not accepted by netdata already) - so I needed netdata web files to be owned by something that is not `root`.

Anyway, I accepted having web files owned by `root`, only if the group is also checked and is not `root`. So, I added the option `[global].web files group` which is also checked against all web files. The debian folks install everything as `root:netdata` and the files and directories are not writable by user `netdata`.

The result is what you found.

My suggestion, is either to:

- install an empty `netdata.conf` and have all files owned by `netdata`, or
- put whatever you believe in `netdata.conf` but please have the files and directories installed with the permissions you chose.

I agree that the debian folks suggestion is better, but somehow I still resist to the idea of hardcoding `root` into the netdata source code... (it is psychological I guess....).

**Comment by candrews** [comment]
I'm always in favor of matching upstream, so I'll make the gentoo packaging match what it does. :)

https://github.com/gentoo/gentoo/issues/2733 installs `system/netdata.conf` to `/etc/netdata/netdata.conf` and changes the permissions on `/usr/share/netdata` to root.

**Comment by ktsaou** [comment]
ok. This file too has the stricter installation options too. So, yes this is a good strategy.
Thanks!

**Comment by ktsaou** [comment]
This is done, so I am closing it.
Thanks! Please post if something remains.
