### ISSUE TITLE
cpu details of  different processes running with same process name

### ISSUE THREAD

**Issue by monikaallireddy** [firehol/netdata#1223]
Can i see cpu details of different processes running with same process name .

ex : I have process1, process2 running with java application.
Can i able to see cpu details of process1 and process2 grouping seperately.

**Comment by ktsaou** [comment]
You have to separate them somehow.

1. Is there anything different on the command line?
2. Do they run as different users?
3. Are they at different process trees (i.e. is their parent different)?

The easiest is the command line. If they have something different, you can edit `/etc/netdata/apps_groups.conf` and give the different command lines there.

If they run as different users, just check the `users` charts.

If their parent is different, try matching their parent at `/etc/netdata/apps_groups.conf` and make sure you don't match the processes themselves.  The idea is that the parent will get them with them.

**Comment by marko8904** [comment]
The documentation specifies that the processes are matched according to the output of ps -e. However, the processes we are monitoring differ only further down the command line (same process binary, different switches). I haven't found a way to differentiate the processes in apps_groups.conf if the difference is only in the command line switches. Either the processes are not matched at all or all of them are matched together under one group name.

Is there a way to differentiate them or is this something that would have to be implemented in the the apps plugin? The processes all run under the same user name.

**Comment by ktsaou** [comment]
Yes you can differentiate based on the whole command line, using the contents of `/proc/PID/cmdline`:

https://github.com/firehol/netdata/blob/4b5f021453cd3220c4d4c2507d4cee1a8c88804b/conf.d/apps_groups.conf#L28

Where did you find the documentation that states only `ps -e`? I need to fix that.

**Comment by marko8904** [comment]
Thanks @ktsaou! The key here was that for command line parsing the pattern had to be prefixed with a wildcard. I technically didn't need the wildcard prefix but I misread the docs and didn't realize that without it cmdline matching wasn't going to happen at all. Now the problem's solved! Thanks!

As for ps -e, apps_groups.conf indicates that command as a way to see which process names would be matched but, as I mentioned, I failed to notice the key to unlocking cmdline matchine further down. All good now! (and considering that there is a space in the cmdline due to switches that threw in a bit of confusion but "*process -switch1*" worked perfectly).

**Comment by ktsaou** [comment]
ok nice!
I am closing this.
