### ISSUE TITLE
snmp, wrong values.

### ISSUE THREAD

**Issue by cis2131** [firehol/netdata#1236]
I am trying to messure signal quality in a sat headend.

My OID gives:
.1.3.6.1.4.1.7465.20.2.9.4.4.3.1.2.1.5.1.3 = STRING: "14.000000"

node.d.plugin 1 snmp debug, shows:
2016-10-04 15:19:40: node.d.plugin: DEBUG: snmp: 172.16.10.209: making 2 entries request, max is: 50
2016-10-04 15:19:40: node.d.plugin: DEBUG: snmp: 172.16.10.209: got valid snmp response: [ { oid: '1.3.6.1.4.1.7465.20.2.9.4.4.4.1.2.1.5.1.2',
    type: 4,
    value: <Buffer 31 34 2e 32 35 30 30 30 30> },
  { oid: '1.3.6.1.4.1.7465.20.2.9.4.4.4.1.2.1.5.1.1',
    type: 4,
    value: <Buffer 31 35 2e 35 30 30 30 30 30> } ]
2016-10-04 15:19:40: node.d.plugin: DEBUG: snmp: 172.16.10.209: found snmp value of OIDs 1.3.6.1.4.1.7465.20.2.9.4.4.4.1.2.1.5.1.2 = 14.250000
2016-10-04 15:19:40: node.d.plugin: DEBUG: snmp: 172.16.10.209: found snmp value of OIDs 1.3.6.1.4.1.7465.20.2.9.4.4.4.1.2.1.5.1.1 = 15.500000
2016-10-04 15:19:40: node.d.plugin: DEBUG: snmp: 172.16.10.209: finished snmp with 2 successful and 0 failed values
2016-10-04 15:19:40: node.d.plugin: DEBUG: snmp: 172.16.10.209: processing snmp response (received in 10 ms)
2016-10-04 15:19:40: node.d.plugin: DEBUG: setting current chart to snmp_switch.bandwidth_port1
BEGIN snmp_switch.bandwidth_port1 2917000
SET db = 0x31342e323530303030
END

2016-10-04 15:19:40: node.d.plugin: DEBUG: sent chart snmp_switch.bandwidth_port1
2016-10-04 15:19:40: node.d.plugin: DEBUG: setting current chart to snmp_switch.bandwidth_port2
BEGIN snmp_switch.bandwidth_port2 2917000
SET db = 0x31352e353030303030
END

And the graphs ends up showing 0.

What am I doing wrong?.

**Comment by l2isbad** [comment]
If values are equal and algorithm is "incremental" result will be zero.

**Comment by cis2131** [comment]
Thanks.. Borrowed a bit too much form the example.

I have done as you said, but now i get values like: 22e+13 in the chart.

**Comment by l2isbad** [comment]
Oh, its because 0x31342e323530303030 and 0x31352e353030303030 (check it yourself! - echo 0x31342e323530303030 | xargs printf '%d \n' ) values are huge (the actual values snmp pluging sending to netdata)

Maybe the problem is type STRING. not gauge or counter

**Comment by ktsaou** [comment]
yeap, this is the problem. The SNMP plugin will use 32bit and 64bit numbers, but it does not parse strings. Are you sure there is no another OID with a numeric representation of this?

**Comment by cis2131** [comment]
I have checked all OID's now, there is only a STRING version of the value. Is there no workarround for it?..

**Comment by ktsaou** [comment]
> I have checked all OID's now, there is only a STRING version of the value. Is there no workarround for it?..

I'll check if the plugin can know these are strings. If it can I'll attempt to parse them.

**Comment by ktsaou** [comment]
Well, I am trying to figure how to fix that.

I understand that this condition: https://github.com/firehol/netdata/blob/282a350685750f6dcff74501810c49287ee98a8f/node.d/node_modules/netdata.js#L363 results to `true`, so netdata believes it is a stream of bytes.

Since the the plugin cannot tell the difference between strings and byte arrays, the only option we have is to figure out how to check for strings here: https://github.com/firehol/netdata/blob/282a350685750f6dcff74501810c49287ee98a8f/node.d/snmp.node.js#L252

The objects in the array `varbinds` have a `type` based on this: https://github.com/firehol/netdata/blob/282a350685750f6dcff74501810c49287ee98a8f/node.d/node_modules/net-snmp.js#L45-L60

So, instead of:

```js
value = varbinds[i].value;
```

I understand we could use something like:

```js
if(varbinds[i].type === net_snmp.ObjectType.OctetString)
    value = parseFloat(varbinds[i].value);
else
    value = varbinds[i].value;
```

Even if this works, we have another problem: you value is decimal. Unfortunately the decimal part will be lost due to this line: https://github.com/firehol/netdata/blob/282a350685750f6dcff74501810c49287ee98a8f/src/plugins_d.c#L166

The solution could be to the dimension divider to 1000 and do this:

```js
if(varbinds[i].type === net_snmp.ObjectType.OctetString)
    value = parseFloat(varbinds[i].value) * 1000;
else
    value = varbinds[i].value;
```

So, can you check if this change works? You will need to put the code above in the place of the this line (replacing it): https://github.com/firehol/netdata/blob/282a350685750f6dcff74501810c49287ee98a8f/node.d/snmp.node.js#L252

**Comment by cis2131** [comment]
Thanks, that works fine.. :-)

**Comment by ktsaou** [comment]
added it to the repo, will merge later today...

**Comment by ktsaou** [comment]
merged it.
