### ISSUE TITLE
Sending netdata data to another backend

### ISSUE THREAD

**Issue by ElieLiabeuf** [firehol/netdata#1247]
Hi.

I really like netdata and I am closely following developments and discussions about new features.

It seems that some users want to send data to various backends (opentsdb, infludb, graphite, elasticsearch, you name it). Goals differ but these subjects appear to be recurrent : get longer history, so some sort of data consolidation, alerting (not so relevant anymore). Issues related : (https://github.com/firehol/netdata/issues/636, https://github.com/firehol/netdata/issues/174, https://github.com/firehol/netdata/issues/313, https://github.com/firehol/netdata/issues/178, https://github.com/firehol/netdata/issues/309)

You may have heard of telegraf, it's "an agent written in Go for collecting, processing, aggregating, and writing metrics". It's open source and part of the influx data stack : https://github.com/influxdata/telegraf

I've just made a pull request to support netdata as an input : https://github.com/influxdata/telegraf/pull/2039. This is pretty basic but It allows to reduce the resolution by setting the collection interval and number of points you want to gather as describe in the [readme](https://github.com/influxdata/telegraf/pull/2039/files#diff-ae399c811fa8d1f23ede62f79771c5c8).

Telegraf offer a variety of [output](https://github.com/influxdata/telegraf#output-plugins) to store your netdata metrics (there is a [PR to add elasticsearch output](https://github.com/influxdata/telegraf/pull/1875)).

I'd be happy if you try it and give me some feedback. It's really simple to build Telegraf from source as shown [here](https://github.com/influxdata/telegraf#from-source).

Here is a capture of grafana displaying netdata metrics stored in influxdb:
![image](https://cloud.githubusercontent.com/assets/5363843/20282631/d4afb7f8-aab5-11e6-8d7e-f6a460d4ce83.png)

**Comment by ktsaou** [comment]
very nice!
I'll give it a try for sure.
Thank you!

**Comment by bkmeneguello** [comment]
I was wondering if it's possible to allow some kind of plugin to receive events fom https://github.com/firehol/netdata/blob/master/src/rrd.c#L976 and decide where to send them.
This is a good point to send data to statsd service.

**Comment by ktsaou** [comment]
> This is a good point to send data to statsd service.

hm... the other way around I think: I am thinking of writing a statsd plugin for netdata to send data to netdata.

The reason is simple: statsd is an aggregator. It collects data, aggregates them and sends them to a database for storage and visualization.

Statsd allows embedding simple code in applications that fires-up events when something happens. It does this with UDP, so the application do not slow down. Its cause is to have a very high performance metric collector that summarizes the data once every a few seconds and sends the normalized ones for storage and visualization.

There are many statsd implementations, I think the most widely used is probably a node.js one (https://github.com/etsy/statsd) and the fastest one is probably a C one, developed by github (https://github.com/github/brubeck).

The problem with all these implementations is latency. Data are collected and visualized with quite some latency. A statsd implementation that sends data to netdata every second will significantly lower the visualization latency and additionally will provide quite powerful alarms in real-time.

To send data to time-series databases I plan to add another thread that will send either raw or processed data to opentsdb or graphite. It should not be hooked at the point you suggest, since this will increase the latency for the whole of netdata. The idea is to send the data to other databases without replicating the data inside netdata or to send data possibly at a lower resolution (netdata collects up to 5000 metrics per server per second, i.e. lots of data: 4 bytes per metric * 5000 metrics * 86400 seconds = 1.65GB per server per day, so some aggregation might be needed before sending them).

I need this opentsdb connection, so I think within the next month we will have at least a very simple opentsdb connection, upon which other back-ends can be developed.

**Comment by divgwd** [comment]
Hi,
I wanted to know if the [[inputs.netdata.servers]]  section in the telegraf.conf can have more than one URL.I am trying to pull data from a few netdata servers via nginx proxy server .

**Comment by ElieLiabeuf** [comment]
Yes you can collect data from multiple servers. Simply add one [[inputs.netdata.servers]] section per netdata server.

**Comment by divgwd** [comment]
Thank you :)
Is there a way to pull alarm data from the netdata plugin?

**Comment by ktsaou** [comment]
implemented backends: **graphite** and **opentsdb** in PR #1264 .
testers needed, so if you use any, please join comment on the PR.

**Comment by bkmeneguello** [comment]
I'll do it. Amazing work!

**Comment by ktsaou** [comment]
merged it. so just update netdata and configure it.
wiki page: https://github.com/firehol/netdata/wiki/netdata-backends

**Comment by bkmeneguello** [comment]
I'm using in my monitor full stack at https://github.com/bkmeneguello/docker-monitor. Anyone can test only with a "docker-compose up".

**Comment by busyninja** [comment]
Dear ktsaou,

First of all I wanted to thank you a lot for this amazing tool. We have been using in production for some time.

We can test graphite backends in production with several hundred hosts, but I wanted to ask if its possible to implement a filter to not send unwanted metrics to the graphite backend. 

I'm little worried about sending so many metrics to graphite, with so many hosts at same time.

I don't have C programming experience, but I do have in other programming languages. I'll try to make a look if I can implement somehow a filter, and if succefully , send a PR.

Thanks a lot once again,
Kind regards.

**Comment by ktsaou** [comment]
You are right, the metrics are just too many.
However, implementing a filter would require quite some work (mainly for the management of the filters).

Have you tried to filter them at the graphite side, by setting a very small retention policy for the ones you don't need? Graphite already provides the means to manage this policy per metric or group of metrics.

I agree though, there should be a filter somewhere (and probably a map - i.e. allow netdata emulate other metric collectors). If you can make a PR, please do so...

**Comment by bkmeneguello** [comment]
At graphite side also you can use white/blacklist to filter input data. If you are concerned about data volume on disk, this can solve. If you worry about network data volume, the aggregation already implemented in Netdata works nicely limiting this. I don't use so many hosts, and my network volume didn't impacted and whitelisting my metrics, the storage is under control.

**Comment by busyninja** [comment]
Thanks ktsaou and bkmenguello for your fast response.
We will try to implement with graphite whitelist and get back to you.

**Comment by thecityofguanyu** [comment]
Implemented this with Graphite and it works awesome. Thanks for all the work done here.

**Comment by busyninja** [comment]
wow awesome thecityofguanyu!

We are still preparing deploy , it's a lot of work. I'll keep you updated.

**Comment by divgwd** [comment]
@ElieLiabeuf I am trying to pull netdata's data via a Nginx proxy and put it to a kafka broker..is there a way to get the remote host's ip rather than the server ip parsed from the config file??

**Comment by ktsaou** [comment]
Cleaning up day: I am closing this now, but if there is something I missed, let me know and I'll re-open it.

Thank you @ElieLiabeuf for sharing your work with us! I hope the new netdata backends will be helpful for you too.

**Comment by jpriebe** [comment]
@busyninja - just thought you might want to know that backend metric filtering is in the latest PR.  See this issue: https://github.com/firehol/netdata/issues/2257#issuecomment-307416297

**Comment by busyninja** [comment]
We are currently testing with very good results.

Good job and thanks a lot.
