### ISSUE TITLE
node.js module performance concerns

### ISSUE THREAD

**Issue by mutsys** [firehol/netdata#1281]
First off, congratulations on creating an awesome tool. I was absolutely blown away by both the power and the simplicity of **netdata**. However, with all of the effort and concern that has gone into the performance aspects of netdata, it appears that the netdata module for node may not have received the same attention. There are a number of items I noticed that may negatively impact performance and ease of adoption.

* The collected data is sent to from the plugin to the server by writing to `console.log`, which is then consumed by **netdata** reading from .  `console.log` is a synchronous, blocking call and should not be used in any production application. If you must ship data via `stdout`, there are a number of high-performance, asynchronous logging modules available, such as [Winston](https://github.com/winstonjs/winston).

> As an aside, why go the `stdout` route of sending data from the plugin to the server? Certainly it is easy, but it would seem that it comes with a whole host of other issues besides performance. The server has to `exec` and then keep track of all of the external plugin processes. This would seem on the surface to be a limit to scaling external plugins since all data collection must reside on the same host as the **netdata** server. A poorly written plugin could steal resources from the server and make it inaccessible. Why not just send some JSON across the network? Why not extend the REST API to allow for `POST` to send data?

* Timing/scheduling of data collection and generation of timestamps uses `new Date().getTime()` to get milliseconds since the epoch. This is unnecessarily creating `Date` objects at a fairly high frequency. The `Date` object is a good deal larger than a number in javascript (112 vs 16 bytes in V8, according to Chrome profiler). In addition, the amount of code executed when calling `new Date().getTime()` is significantly greater than when calling `Date.now()`. Take a look at [builtins-date.cc](https://github.com/nodejs/node/blob/73ae2d1895c2c0d1d4eeaddd284c58d776d2be87/deps/v8/src/builtins/builtins-date.cc) for the details. `new Date().getTime()` creates a date starting with millis since the epoch, converts it to a date in the local timezone and then converts that back to millis since the epoch again.

* `logdate` formats a `Date` in a rather brute force manner. There are a number of `toXXXString()` methods on `Date` that will get you the same thing. The `zeropad2` method is not necessary. The same can be done more easily as:

```javascript
zeropad(s) {
    return ("00" + s).slice(-2);
}
```

* The `stringify` function is being used exclusively to serialize objects to JSON for debugging purposes. It is using `util.inspect`, which can apply a color scheme to the serialized/json output. However, by default, it does not perform this coloring and the option to specify coloring is not being set. Since this feature is not being used, I would suggest using `JSON.stringify()` instead [JSON.stringify() docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify). It doesn't provide features you aren't using but it does provide you with the ability to customize the format of its output, applying indentation or custom property conversions if you choose, allowing you to present much more readable output. `util.inspect` just writes its output as flat lines, a rather unpleasant presentation if you are trying to debug your plugin.

**Comment by ktsaou** [comment]
Thanks! Nice suggestions!
A few improvements seem trivial, a few need for more work. Are you willing to help?

Regarding the side note:

I am trying hard to restrict each netdata on a single host. This is very important. If netdata is to be used centrally collecting data from multiple hosts, then all the limitations of other existing solutions will also be applied to netdata. We will be forced to end up with a much lower data collection frequency, significantly less metrics collected, a slower UI, etc. There are already very good solutions that follow this approach (collectd, graphite, opentsdb, influxdb, grafana, etc), but such solutions require dedicated resources and are significantly less effective in providing the insights netdata provides out of the box.

I will work hard to fix any bottleneck that will prevent netdata from collecting any number of metrics from a single host, in real-time and without any significant resources consumed, so that we will never decide not to add yet another metric collected in real-time.

So, my approach is to limit all netdata to a single host, with the only exception of nodes that netdata cannot be installed at (i.e. SNMP devices). All muli-host functionality has to be derived at a higher level (i.e. at the UI).

Pipes (i.e. stdout) seemed the best way to collect data for netdata. Internally netdata has a thread for each of its external plugins, so the plugins would never block while writing to their stdout. netdata is able to update all its charts at the same time (if it has to) without any disk I/O and without any locks, so nothing is actually blocking each of these threads from going full speed.

All plugins are designed to collect data, then send them to netdata and wait for the next iteration. So, slight timing differences will only affect the time the plugin will have sleep before the next iteration.

Also pipes allow all the netdata process tree to be managed as one. You start netdata or stop netdata and this is it.

What is missing from netdata, is multi-server dashboards out of the box. Its core can do it, its javascript libraries can do it, I just haven't enough time to work on it yet. The next step is bigger history. netdata can be a lot more efficient in its memory footprint. I have done some work, but it requires a lot more. My target is to allow netdata have 1 week of data, without any significant performance hit or resources on the server.

So, back to the original suggestions: I need help. Can you help?

**Comment by ktsaou** [comment]
So, based on your suggestions:

1. console.log usage for sending data to netdata.

  Winston has a lot of dependencies and I am not sure it is really needed. I'll investigate alternatives. If you take a closer look, you will see that each module is calling `console.log` just once per iteration (they queue all data and at the `end()` they call `console.log`. The reason I made it that way is to prevent multiplexing the responses of multiple modules/job at netdata (it would be a mess).

2. I changed all `new Date().getTime()` calls to `Date.now()`. Thanks for this suggestion. I was not aware.

3. I changed `zeropad2()` as you suggest. `logdate()` is rarely called. It is only called to log error messages and debugging info. I needed a way to have a uniform date logged at `netdata.log` and I couldn't find a better way to have node.js log in exactly the same format all the other plugins and netdata do. So, I compose it.

4. You are right about the `stringify()` call. If you check the commit log, you will see that there was a version using `JSON.stringify()`. However, `JSON.stringify()` does not allow setting a depth and in certain cases this resulted is really huge output. So, I used `util.inspect` to solve that problem. This call is again only for error logging and debugging, so it is rarely used.

Overall: the change of `new Date().getTime()` really made a difference. This is called everywhere (web dashboard and node.js plugins) all the time. I have not measured the final effect on netdata by replacing it with `Date.now()`, but I can tell the netdata dashboard feels snappier.

Very nice catch! Thank you for taking the time to suggest this change!

**Comment by ktsaou** [comment]
merged the fixes.
Thanks for reporting them. I am always open to more suggestions...

**Comment by mutsys** [comment]
Awesome, glad that some of those suggestions made a difference.

   After spending some time tinkering with the node plugin now, I see opportunity for cleanup and simplification. The current version seems to twist itself into knots trying to deal with asynchronous data collection and reporting back to the netdata server. I already started untangling this for my own use, but I would be happy to send you back the result when I am done.

   As for the UI, one thing I did notice when I fired up the default install is that the visualization activity in the browser consumes a tremendous amount of CPU, far more than I would have expected. Nearly 100% of all available CPU on a two core VM (2.8 GHz i7). I'm guessing that there is a lot activity going on rendering graphs off screen that aren't in view, which would be wasted effort. If so, there may be a opportunity for significant optimization there. I'll take a look and see if I can confirm that.

**Comment by ktsaou** [comment]
perfect! looking forward for it.

Unfortunately, dygraphs, the main chart library in netdata is re-drawing everything on every update. It does not support incremental updates. This is the main cause for the browser CPU utilization. There are other chart libraries that support incremental updates, but they are missing almost every other functionality.

If we manage to find a chart library with the right functionality, then we could even receive incremental updates from netdata (now netdata re-sends the chart on every update - hopefully in the format dygraphs expect, so there is no data processing on the client, apart charting).

**Comment by mutsys** [comment]
Are you sure that dygraphs doesn't support incremental updates?  Take a look at this:

[Dynamic Update demo](http://dygraphs.com/gallery/#g/dynamic-update)

This shows a dygraphs line chart being incrementally updated, adding one new data point to the series every second. A quick check of the page source reveals that this is being done by simply appending/pushing new values onto an array in memory. No data reloading is being done is this demo. It would seem that this could be accomplished with a wee bit of async browser api client wizardry, fairly common these days.

That being said, I have had a good experience with d3 lately, implementing line and area charts in a rolling time window, very similar to some of the netdata visualizations. I know for a fact that this can be done with d3. I don't see anything done here with dygraphs that couldn't be done with d3 (and perhaps some additional d3 extensions to make it easier to draw graphs without a lot of low-level svg hacking).

**Comment by ktsaou** [comment]
It appends the values, but it re-draws the whole chart, every time.
I know I could append data to the dataset. But this would only improve network bandwidth and complicate everything else. If it could re-draw only the part of the chart that needs re-drawing, I would have provided incremental updates everywhere.

This is incrementally drawing the charts: https://square.github.io/cubism/
But it is very primitive.

D3 is fantastic, but it is very low level me. A lot of work to provide everything (hover, pan, zoom, selection, annotations, etc).
BTW, this is the chart I love in D3: http://bl.ocks.org/WillTurman/4631136. Fantastic stacked chart, a lot more descriptive of the weights of each dimension.

**Comment by ktsaou** [comment]
And I know of C3, but it is very slow. Just open `http://your.netdata:19999/dashboard.html` to see all the chart libraries I have evaluated.
