### ISSUE TITLE
Work with Heroku? 

### ISSUE THREAD

**Issue by chavenor** [firehol/netdata#1344]
Does Netdata work with Heroku?

**Comment by ktsaou** [comment]
I think Heroku runs applications on infrastructure and servers they manage. I don't use it, so I don't know for sure, but I think that netdata is more likely a system for their use... (i.e. their sysadmins and devops).

**Comment by chavenor** [comment]
Got it.  I opened up a ticket with Heroku.  I'll let you know what I find. 

Would you recomend netdata for a Linux based network appliance?   If so how would one get to the data if it was behind a firewall?

**Comment by ktsaou** [comment]
> Got it. I opened up a ticket with Heroku. I'll let you know what I find.

nice!

> Would you recomend netdata for a Linux based network appliance? If so how would one get to the data if it was behind a firewall?

Yes, of course. If the device is weak, check these settings that might help: https://github.com/firehol/netdata/wiki/netdata-for-IoT

Regarding the firewall, I guess you are not interested just for port-forwarded, but for access control in general. Since netdata does not support authentication itself, you can limit access to it via a nginx (with authentication). Check this: https://github.com/firehol/netdata/wiki/Running-behind-nginx#enable-authentication

**Comment by chavenor** [comment]
AWSOME!

**Comment by chavenor** [comment]
I have a raspberry pi. I'm assuming I can use the full fledged setup.  Good to know there is a lite-version.

**Comment by ktsaou** [comment]
RPi 2 and 3 can run netdata with default settings. The cpu utilization is ignorable.
On RPI 1 I run netdata with `update every = 5` and everything else enabled which results in less that 1% cpu utilization.

**Comment by ktsaou** [comment]
Cleaning up day. I am closing this, but if you have a suggestion/issue, please post and I'll re-open it.
