### ISSUE TITLE
Negative values on easypiechart

### ISSUE THREAD

**Issue by l2isbad** [firehol/netdata#1386]
Are there a way not to abs values on easypiechart?

**Comment by ktsaou** [comment]
hm... these charts actually show a value from 0 to 100. I have mapped them to the min-max of the dimension.

If it was negative, what would you expect to happen? Draw the chart, counter clockwise?

**Comment by l2isbad** [comment]
Yeah draw the chart counter clockwise. In my case i need this for outdoor temperature values .
It would be nice if there was an option to enable this feature

**Comment by ktsaou** [comment]
ok, I added the code to do it.
Since this can be misleading in many cases, to activate this mode you have to add to your chart:

```html
<div ... data-override-options="singed" ...></div>
```

The default options is `absolute`. The reason is very simple: Since netdata shows many dimensions as negatives and allows us to `sum` multiple dimensions, without the `absolute` option the values will be totally wrong.

I understand without this override, the presentation of dimensions that have both positive and negative values is also wrong, but I think this is quite rare for netdata. Most dimensions are either positive or negative.

It should be working for gauge charts too (I haven't tested these though).

Could you please test it before merging it?

**Comment by l2isbad** [comment]
Thanks!
I just tested it and seems everything is working fine

![screenshot_20161219_080603](https://cloud.githubusercontent.com/assets/22274335/21297406/7f4c8ade-c5c2-11e6-9183-96d1fab5fd9f.png)

**Comment by ktsaou** [comment]
merged it!
Thanks!

**Comment by ktsaou** [comment]
Could you please check it again?
I updated it so that zero is always included, with PR #1405

**Comment by l2isbad** [comment]
Checked. All is fine.

**Comment by BrainDoctor** [comment]
This data-override-options feature is not documented in [custom dashboards](https://github.com/firehol/netdata/wiki/Custom-Dashboards) sadly, but helped in my case. Could this be elaborated further?
