### ISSUE TITLE
freebsd and macOS: Dashboard descriptions

### ISSUE THREAD

**Issue by simonnagl** [firehol/netdata#1480]
First I want to congratulate @vlvkobal. You are doing amazing work!!! I just installed netdata on my mac. Everything works like expected but the descriptions are (of course) not right jet.

For example for `system.load` there ist "Netdata reads them from /proc/loadavg." which is not right for MacOS.

@ktsaou If you like please finish my open pull requests. If not maybe I will do it in the future. I did not forget them!

**Comment by vlvkobal** [comment]
Yes. I know it looks ugly :). The same issue is on FreeBSD. But I think it's more important to fill the charts first. Moreover, they may change during the work because statistics on Linux, FreeBSD and macOS is quite different.

At the present stage of work I'm trying to mimic Linux statistics as much as possible. The next step I think has to be expanding the charts to provide native statistics and when the charts become stable it will be possible to write proper descriptions.

**Comment by ktsaou** [comment]
check #1705 for the fix.

**Comment by ktsaou** [comment]
This has been fixed.
I am closing it. I you find something missing, please post.
