### ISSUE TITLE
Temporary 'last collected secs' Warnings

### ISSUE THREAD

**Issue by kmlucy** [firehol/netdata#1483]
Over the past couple of days, I have been getting a lot of 'last collected secs' warnings that last for approximately one minute. The warnings I get are:

- disk (for all disks)
- disk space (for all disks)
- interface (for eth0)
- ipv4 tcphandshake
- netfilter

The warnings last from between 50 seconds to 1 minute 23 seconds, then recover.

**Comment by ktsaou** [comment]
It happens on one of my machines too.
What I found is that during that time, the machine is frozen. I have verified that all the servers running on the machine, do not respond (named, squid, etc).

I am still trying to figure out what triggers this. I have concluded this is not a problem of netdata...

Do you experience the same freeze?

**Comment by kmlucy** [comment]
I'm not sure. I haven't tried to access the server during one of the warnings yet. If it happens again, I will check and report back.

**Comment by kmlucy** [comment]
I think this issue can be closed. I have not had it reoccur, and when it happened, the server was under heavy load.

**Comment by ktsaou** [comment]
ok.

**Comment by ktsaou** [comment]
I found that disk space data collection using the `statvfs()` system call, can be very slow at times.

To handle the issue, I isolated the disk space charts / data collection to a separate thread, so that all other charts cannot be affected by this disk latency.

The fix is merged with PR #1569 (just an hour ago).

So, please update your netdata. Normally, netdata should not give again alarms not related to disk space.

I would appreciate it if you report back your findings.

**Comment by ktsaou** [comment]
Also, there are now a few charts that show data collection latency. So, I would also appreciate if you find the module triggering this latency, the next time it happens:

![image](https://cloud.githubusercontent.com/assets/2662304/21956496/07099d18-da8b-11e6-82d7-b7080a793984.png)

**Comment by kmlucy** [comment]
If it happens again, I will take a look and report back.

**Comment by hameno** [comment]
It happens for me quite often, I just looked at the graph and it shows "stat" taking 1000 - 2500ms:
![image](https://cloud.githubusercontent.com/assets/365084/22009853/0cb2c288-dc86-11e6-9c40-7e2aab0dd524.png)

**Comment by ktsaou** [comment]
> I just looked at the graph and it shows "stat"

interesting. `stat` does not have any disk dependencies... Can you show the system.cpu chart for the same time?

**Comment by hameno** [comment]
![image](https://cloud.githubusercontent.com/assets/365084/22012577/0646bc6a-dc95-11e6-983d-8cb97cba937f.png)

This is a debian 8 VM with gitlab deployed on it. Gitlabs unicorn process spikes almost exactly every minute although there is no traffic to gitlab (neither ssh nor http). Not yet sure if that's normal...

**Comment by hameno** [comment]
Also interesting:
![image](https://cloud.githubusercontent.com/assets/365084/22012646/7e9bc930-dc95-11e6-9a48-6754d78d3abc.png)

**Comment by ktsaou** [comment]
hm... a gap...

netdata runs with IDLE process scheduling priority. I have done this, to prevent netdata from disrupting the applications of the system.

The result of this, is that under such spikes, netdata starves for CPU, which results in these gaps in the charts.

In your case though, since this is an interrupt that spiked that high, I think all the processes of the system faced similar issues. The machine was virtually frozen during that time.

One quick fix to prevent the alarms from triggering, is to increase the time they check. But before doing so, I would suggest to verify this is the right decision.

What do you say?

**Comment by hameno** [comment]
Not sure, I'd much rather remove the gaps...I'll try to distribute the load a bit better (there are cron jobs running at all VMs at the same time, I suspect those are the cause.)
