### ISSUE TITLE
Password for netdata. 

### ISSUE THREAD

**Issue by AmirIqbal1** [firehol/netdata#1532]
Could a password and username be added to netdata, to prevent unauthorised users from getting access to the monitoring console?

**Comment by djmattyg007** [comment]
This would be a nice option to have. It's not always feasible to lock it down behind a reverse proxy like nginx and use its basic auth.

**Comment by pjz** [comment]
Why is it not always feasible?  I just threw some info on doing so behind lighttpd on the wiki [here](https://github.com/firehol/netdata/wiki/Running-behind-lighttpd) .

**Comment by djmattyg007** [comment]
You might not be able to install a webserver in your working environment.

**Comment by pjz** [comment]
...but you can install netdata?  Seems unlikely.

**Comment by ktsaou** [comment]
Authentication is missing of course.

netdata is a distributed monitoring system.  So, it should use an OAUTH2 provider so that all your netdata installations will have single-sign-on and accounts management will be needed at the OAUTH2 provider only.

I already have this on my todo list: #70 

But please, be patient.

The day I am going to release this, people will start asking for SSL/TLS support. So, these have to be implemented together.

At the same time, I will receive a lot of requests for supporting API keys, so that other applications will be able to talk to netdata without authentication (i.e. for badges, prometheus backends, embedding charts on third party apps, etc). So, API keys need to be implemented with authentication too.

As you can see, it is not a small feature. I could continue adding related features.

For the moment I prefer to develop features that provide the maximum benefits to the community, like #1527 . Since there is a work-around for authentication, I prefer to let it a bit back.

I hope you will agree...

**Comment by djmattyg007** [comment]
Thank you @ktsaou for your consideration :)

**Comment by ktsaou** [comment]
Cleaning up.
I am closing this in favor of #70 
Let's continue the discussion there.
