### ISSUE TITLE
Debian 8.4 ("Jessie") Shell Issues 

### ISSUE THREAD

**Issue by GreenDragon** [firehol/netdata#155]
/bin/sh defaults to /bin/dash in Jessie installs.

This causes invocations of some chart plugins to fail:

```
user@host:/opt/netdata/usr/libexec/netdata/charts.d
$ grep -n ^declare *
apache.chart.sh:18:declare -a apache_response=()
ap.chart.sh:8:declare -A ap_devs=()
mysql.chart.sh:13:declare -A mysql_cmds=() mysql_opts=() mysql_ids=()
nginx.chart.sh:13:declare -a nginx_response=()
nut.chart.sh:15:declare -A nut_ids=()

$ ./apache.chart.sh
./apache.chart.sh: 18: ./apache.chart.sh: Syntax error: "(" unexpected

$ ./ap.chart.sh
./ap.chart.sh: 8: ./ap.chart.sh: Syntax error: "(" unexpected

$ ./mysql.chart.sh
./mysql.chart.sh: 13: ./mysql.chart.sh: Syntax error: "(" unexpected

$ ./nginx.chart.sh
./nginx.chart.sh: 13: ./nginx.chart.sh: Syntax error: "(" unexpected
```

nut.chart.sh doesn't throw an error since it's shell is explicitly set to /bin/bash.

**Comment by ktsaou** [comment]
These scripts are not standalone. They are sourced from [charts.d.plugin](https://github.com/firehol/netdata/blob/master/plugins.d/charts.d.plugin) which is properly configured to run bash.

There is also the PR #132 that updates them to use BASH (although not required since they are never execute directly).

For netdata errors (including its plugins), I suggest to look at `/var/log/netdata/error.log`.
