### ISSUE TITLE
Listen on docker container stop

### ISSUE THREAD

**Issue by felixoi** [firehol/netdata#1578]
I'm not sure if there is any option to do this:

At the moment when stopping a docker container with `docker stop <container name>` netdata sends me tons of messages because the virtual network interface is not responding. I think the interface / container should be automatically removed if the docker container is stopped. Or is this known and right?

**Comment by ktsaou** [comment]
> I'm not sure if there is any option to do this:

I am not either. Ephemeral containers is a problem - I am trying to figure out how to solve this.
Until we have a solution, what you can do is:

1. edit `/etc/netdata/health.d/net.conf`
2. change the `families: *` lines on all alarms to `families: !veth* *`, so that netdata will not attach alarms to veth interfaces.

The pattern `!veth* *` says:

- `!veth*`: do not match interfaces starting with `veth`.
- `*`: match anything else

**Comment by ktsaou** [comment]
Cleaning up. I am closing this. There are already a number of issues dealing with ephemeral containers.
