### ISSUE TITLE
Failed to build on FreeBSD 10.3-RELEASE-p11 -- uuid.h

### ISSUE THREAD

**Issue by 0xc0decafe** [firehol/netdata#1644]
The file src/common.h includes the <uuid/uuid.h> header file, which on my FreeBSD machine is not located in the uuid subfolder. changing the include to <uuid.h> fixed the problem.

cheers

**Comment by ktsaou** [comment]
hi. thanks  for reporting this!

@vlvkobal please check it.

**Comment by vlvkobal** [comment]
Did you install `e2fsprogs-libuuid`? It installs `/usr/local/include/uuid/uuid.h`. Anyway, it's interesting. Does FreeBSD have `uuid` without additional package installation? I've not verified it yet.

**Comment by 0xc0decafe** [comment]
hi,

yes, i have `e2fsprogs-libuuid` installed. And yes, there is a `/usr/local/include/uuid/uuid.h`, but /usr/local/include is not in the default include path. As of the header, the file `/usr/include/uuid.h` belongs to the FreeBSD base system: `$FreeBSD: releng/10.3/include/uuid.h 183057 2008-09-15 23:47:19Z emax $`.

best

/daniel

**Comment by vlvkobal** [comment]
I updated my 10.3 vitrual machine up to `FreeBSD 10.3-RELEASE-p11`, uninstalled `netdata`, got it again from github, built and ran it. Everything works fine.

Please check dependencies: `bash e2fsprogs-libuuid git wget curl autogen autoconf autoconf-archive automake gcc libtool pkgconf pido`. You might have missed some (most probably `gcc`).

BTW. I verified `/usr/include/uuid.h`. I can't build `netdata` with it because some functions are missing. So we need to install `e2fsprogs-libuuid` despite FreeBSD base system has some parts of `libuuid`.

**Comment by ktsaou** [comment]
@0xc0decafe did you solve it?
I am closing this, but if you haven't solve it, please post and I'll re-open it.
