### ISSUE TITLE
Custom settings in /etc/netdata/conf.d/

### ISSUE THREAD

**Issue by mrmodolo** [firehol/netdata#1646]
In the folder '/etc/netdata' a folder like for example '/etc/netdata/conf.d/*.conf' where we can put the settings that will not be overwritten in case of update.

Thanks,
Marcelo Módolo

**Comment by ktsaou** [comment]
`netdata-installer.sh` does not overwrite your configuration files.

It has md5 sums of all config files shipped by netdata (all versions the stock config files) and it overwrites files in `/etc/netdata` only when the installed is a stock version.

**Comment by ktsaou** [comment]
When netdata is installed as a package (i.e. via the distro package manager), there should be a way, provided by the package manager, to review and maintain application configuration files.

Keep in mind we generally try to have all configuration backwards compatible, so that updating netdata but keeping the old config files will not break anything, although certain modules may be disabled and others may be unconfigured.

I am not sure if netdata should do something in this area. If you believe it should, we should invide in this discussion the package maintainers of netdata ( #651 ) to find a cross distro way of doing it.

I am closing this now. Post if you believe we should do something and I'll trigger the discussion with the maintainers.

**Comment by zhangxin0112** [comment]
@ktsaou  could u check  #5386 
What is ”stock version“ ？

**Comment by SS88UK** [comment]
Hi,

I am facing this issue. I have edited nginx.conf because I have a custom location + install. It was working great, then netdata updated and overwrote my files.

I followed this to make the changes: https://docs.netdata.cloud/collectors/python.d.plugin/nginx/

I simply installed netdata as per your homepage with automatic updating turned on.

**Comment by ilyam8** [comment]
Hi @SS88UK 

see https://github.com/netdata/netdata/issues/8435 (same goes for all user config files)

**Comment by SS88UK** [comment]
Hi @ilyam8,

Thanks - understood!
