### ISSUE TITLE
NetData in a Docker Container

### ISSUE THREAD

**Issue by brando56894** [firehol/netdata#1659]
I was very happy to see that you guys have extended NetData to FreeBSD, since I have been running it for a year or two on all of my Linux VMs and absolutely love it. I'm pretty active in the testing of the new FreeNAS 10 ( open source NAS appliance, with Enterprise offerings, based on FreeBSD 11, due to be released around the end of February) and I (along with another user, a few months before you mentioned the FreeBSD support) requested it be integrated into the base OS for users that would like a far more in depth view of their system's statistics, compared to the 8-10 graphs that they currently offer in the dashboard.

I have spoken with their CTO regarding it's inclusion and this was his response:

> From an architectural standpoint, we've also still not seen anything compelling enough to supplant collectd and all of the various plugins we've written to feed it. It sends its data to the middleware which re-exports the data as agnostic stats streams, and we can do various things to optimize that stream by sending timestamps only at the top of the feed (and deltas thereafter) and so on - something we probably wouldn't be able to do if we couldn't know the format of the stats output. NetData seems nowhere near as agnostic - it wants to be the very bottom of the stack, so you can't just direct graphite output at it and expect it to be happy, unlike grafana.

He is still willing to include it, but as a Docker container (FreeNAS 10 supports VMs and Docker containers) and was wondering if NetData would be able to receive data from an outside source (FreeNAS itself, possibly via Graphite, instead of the Docker container stats or that of the Docker host), so that they wouldn't have to ditch their entire collectd system that they built.

Graphite and Grafana containers are already available, I gave them a try and they are nice but it takes a while to get everything working. I've been trying to sell them on NetData's ease of use because I'm so used to a few minute installation in Arch Linux and I have over a thousand metrics available to me. I was highly disappointed that I had to create every chart manually with Grafana.

**Comment by ktsaou** [comment]
Hi, thank you! Nice you like netdata so much.

netdata in a docker container may not be able to monitor the host. So it will be useless. In Linux it can be done by mapping the /proc filesystem of the host into the container, but under FreeBSD I think this will not work.

I am not sure I understand why they need all this feeding and streaming or metrics. The whole idea with netdata is to avoid all these altogether. With netdata they will just add a `div` on a page, and they are done: chart shown, no middleware, no feeding, no streaming of metrics.

Unfortunately I cannot make netdata something it is not. netdata archives its metrics to backend databases (graphite, opentsdb, prometheus), but never reads from them. This is just archiving and is normally used in large installations where a number of netdata installations need to send metrics for providing aggregated statistics (e.g. 10x FreeNAS boxes viewed as one).

When I started netdata, I was really pissed off to have just 20-30 metrics per server, updated every 10+ seconds (like you are). This information is "statistics of past performance". It is totally useless from a performance monitoring / troubleshooting standpoint. It might make you feel happy you measure something, but this is it: nice charts of past performance - a business report.

netdata is different. It is so real-time that is can easily replace `top`, `vmstat`, `iostat`, etc. It is a console replacement for real-time performance monitoring, with a relatively small history and alarms. In other words, it is real-time performance monitoring.

Since they have invested in writing their own plugins, I understand they will need to invest now again in netdata to port their collectd plugins to netdata. This cannot be avoided. Of course, this will provide to FreeNAS real-time performance monitoring, unlike anything they have so far. But they need to see value in it and it is up to them to decide if they need it or not...

Keep also in mind @vlvkobal has in its roadmap for FreeBSD a lot more metrics, so probably at some point in future many of their plugins might be shipped by netdata, out of the box.

**Comment by brando56894** [comment]
> netdata in a docker container may not be able to monitor the host. So it will be useless. In Linux it can be done by mapping the /proc filesystem of the host into the container, but under FreeBSD I think this will not work.

Thanks for the response! I figured this may be the case, especially since the Docker Host is Linux and is running under Bhyve :( 

> I am not sure I understand why they need all this feeding and streaming or metrics. The whole idea with netdata is to avoid all these altogether. With netdata they will just add a div on a page, and they are done: chart shown, no middleware, no feeding, no streaming of metrics.

The middleware is necessary for their home brewed CLI to talk to the GUI (and vice versa) because in FreeNAS 9.x it was one way communication from the GUI to the backend which just left you with a GUI with a spinning wheel, wondering if the task is actually doing something or is hung. All the others you mentioned, I'm not sure for their reasoning, as I'm just a user.

> When I started netdata, I was really pissed off to have just 20-30 metrics per server, updated every 10+ seconds (like you are). This information is "statistics of past performance". It is totally useless from a performance monitoring / troubleshooting standpoint. It might make you feel happy you measure something, but this is it: nice charts of past performance - a business report.

This is how the metrics were in FreeNAS 9.x, but instead of every 10 seconds, it was like every 10 minutes so it was absolutely useless for real-time monitoring. I know they're using collectd to feed data to their dashboard widgets, which are nice, but as I stated before only give a high level view of a few things and they update every 5 to 15 seconds. I've been trying to like Grafana but the metrics that it has available are either not something I care about, don't display correctly (the cputemp streams report that my CPU is 3300C haha), or are very nondescript. I have only created about 3 dashboards with about 10 graphs total. I guess I'm spoiled by NetData haha

> netdata is different. It is so real-time that is can easily replace top, vmstat, iostat, etc. It is a console replacement for real-time performance monitoring, with a relatively small history and alarms. In other words, it is real-time performance monitoring.

Ever since I started using it, that's exactly how I use it: if a movie seems like it's loading slowly I can pull up NetData on that host and instantly see the CPU, Network and Disk activity. The only time I use the binary tools is when I'm already SSH'd in.

> Since they have invested in writing their own plugins, I understand they will need to invest now again in netdata to port their collectd plugins to netdata. This cannot be avoided. Of course, this will provide to FreeNAS real-time performance monitoring, unlike anything they have so far. But they need to see value in it and it is up to them to decide if they need it or not...

Yea, this is going to be a hard pill for them to swallow considering they've been working on the development for over a year (not specifically the collectd and dashboard plugins, but everything in general) and I highly doubt they'll ditch it for something they've never really used. 

I'll pass along your info to them and hopefully through some sort of geek magic they'll make it work! :D

**Comment by ktsaou** [comment]
> The middleware is necessary for their home brewed CLI to talk to the GUI (and vice versa) because in FreeNAS 9.x it was one way communication from the GUI to the backend which just left you with a GUI with a spinning wheel, wondering if the task is actually doing something or is hung.

ok. netdata can provide metrics to a shell script, like this:

```sh
# source the metrics
eval "$(curl -s 'http://localhost:19999/api/v1/allmetrics')"

# let's see if there are variables exposed by netdata for system.cpu
set | grep "^NETDATA_SYSTEM_CPU"

NETDATA_SYSTEM_CPU_GUEST=0
NETDATA_SYSTEM_CPU_GUEST_NICE=0
NETDATA_SYSTEM_CPU_IDLE=95
NETDATA_SYSTEM_CPU_IOWAIT=0
NETDATA_SYSTEM_CPU_IRQ=0
NETDATA_SYSTEM_CPU_NICE=0
NETDATA_SYSTEM_CPU_SOFTIRQ=0
NETDATA_SYSTEM_CPU_STEAL=0
NETDATA_SYSTEM_CPU_SYSTEM=1
NETDATA_SYSTEM_CPU_USER=4
NETDATA_SYSTEM_CPU_VISIBLETOTAL=5

# let's see the total cpu utilization of the system
echo ${NETDATA_SYSTEM_CPU_VISIBLETOTAL}
5

# what about alarms?
set | grep "^NETDATA_ALARM_SYSTEM_SWAP_"
NETDATA_ALARM_SYSTEM_SWAP_RAM_IN_SWAP_STATUS=CRITICAL
NETDATA_ALARM_SYSTEM_SWAP_RAM_IN_SWAP_VALUE=53
NETDATA_ALARM_SYSTEM_SWAP_USED_SWAP_STATUS=CLEAR
NETDATA_ALARM_SYSTEM_SWAP_USED_SWAP_VALUE=51

# let's get the current status of the alarm 'ram in swap'
echo ${NETDATA_ALARM_SYSTEM_SWAP_RAM_IN_SWAP_STATUS}
CRITICAL

# is it fast?
time curl -s 'http://localhost:19999/api/v1/allmetrics' >/dev/null

real  0m0,070s
user  0m0,000s
sys   0m0,007s

# it is...
# 0.07 seconds for curl to be loaded, connect to netdata and fetch the response back...
```

The `_VISIBLETOTAL` variable sums up all the dimensions of each chart.

The format of the variables is:

`NETDATA_${chart_id^^}_${dimension_id^^}="${value}"`

The `value` is rounded to the closest integer, since shell script cannot process decimal numbers.

**Comment by brando56894** [comment]
Interesting! It seems that I really got a few other people interested in NetData over at the FreeNAS forums, I'll pass this information along. Thanks.

**Comment by ktsaou** [comment]
ok. I am closing this. If you need my help, just post.
