### ISSUE TITLE
web_log extended format

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#1764]
@l2isbad I see in apache conf shipped with ArchLinux, that apache suggests this:

```
    <IfModule logio_module>
      # You need to enable mod_logio.c to use %I and %O
      LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
   </IfModule>
```

So, they appended `%I` and `%O` to the `combined` format.

This seems a good strategy, since programs parsing the `combined` format, will be able to parse the `combinedio` too.

What do you think? Shall we do the same and append the extended options to the combined format for all web servers (apache and nginx)?

**Comment by ktsaou** [comment]
I have to admit I thought this before, but I was afraid that if we add them after referrer and user-agent, we may end up to a situation where we can't parse it properly (i.e. referrer and user-agent may include quotes, which might be escaped and would be difficult if not impossible to match these escape sequences with regex).

**Comment by l2isbad** [comment]
You need to enable mod_logio.c 

Well, seems mod_logio built-in in debian.  
Actually current version will fail to parse arch httpd logs because of `%b`. Plugin will not start or it will be 'unmatched'. **-** instead of **0**.
**%b**
size of response in bytes, excluding HTTP headers. In CLF format, i.e. a **'-'** rather than a 0 when no bytes are sent.

Recommended format 
`LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\""`
or
`LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined`

**Comment by ktsaou** [comment]
ok. merged it.
