### ISSUE TITLE
option 'performance metrics for mounted filesystems' is not used.

### ISSUE THREAD

**Issue by zeleznikm** [firehol/netdata#1780]
Hello,
I would like to collect performance metric just for disk which are mounted...
option performance metrics for mounted filesystems = yes in netdata.conf was ignored
version : netdata 1.5.1_master

**Comment by ktsaou** [comment]
Unfortunately, we had to split the disk data collector in 2 parts: performance metrics and space metrics, since disk space data collection is tends to depend on various parameters and was slowing down netdata under certain cases).

So, they are configured independently. This setting in unfortunately lost.

**Comment by ktsaou** [comment]
accidental reference to irrelevant commit. Sorry.
