### ISSUE TITLE
Does Netdata have its own dashborads rather connecting to backend ?

### ISSUE THREAD

**Issue by arulvelu21** [firehol/netdata#1924]
As far netdata , it supports real time time monitoring of the devices. If u want to see the archived data , then we go for the backend  configurations. In my case i am going to use netdata at remote device say a gateway. Is there any way netdata provides any UI kind of thing to see directly instead of using backend.

**Comment by ktsaou** [comment]
Install netdata, then go to:

```
http://your.gateway.ip:19999/
````

netdata is autonomous. The backend is only for archiving...

**Comment by l2isbad** [comment]
I may be wrong but I think that the guy wants to see archived data (stored on the backend) directly in the netdata ui.

**Comment by arulvelu21** [comment]
l2isbad .. you are correct . I wanted to see the archived data directly in the netdata UI. Is there any way for this ?

**Comment by l2isbad** [comment]
No. [How netdata works in two words](https://github.com/firehol/netdata/issues/1907).
...
web dashboards, query this (**own**) database to retrieve data, which then are passed to javascript visualization libraries to render them on screen.

Keep in mind you can increase netdata history size ( # history = 3600 - default. 1 hour. 3600 update inrevals. default update interval - 1 sec) by changing` history` or `update every`.[ You can calc the amount of ram you need to store all data for history size you need](https://github.com/firehol/netdata/wiki/Memory-Requirements).
[Also read this](https://github.com/firehol/netdata/wiki/Memory-Deduplication---Kernel-Same-Page-Merging---KSM).
Another way is to store all data on ssd instead of ram 

[From here](https://github.com/firehol/netdata/issues/1311)
> If the central netdata has SSD disks, I suggest to user memory mode = map. This will constantly write data on disks (I measured that for each host it needs a few KB/s), but it will immediately make the RAM size irrelevant. map works like swap. If you have enough disk space, use it all for netdata...
> 
> I have already figured out how to lower the amount of data written with memory mode = map to 1/3 of what is today, but this will require another refactoring.

**Comment by arulvelu21** [comment]
I have a query regarding the  type of graph we use to create our dashboards in web folder. Does the chart type supports line graph. Lets day i want to show  CPU and RAM usage using line graph where x axis  represents time and y axis represents  percentage. is this possible when creating our own dashboard ?

Sorry if i am bugging you much, just want to understand indepth.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, post here.
