### ISSUE TITLE
MySQL Aborted connection - Got an error reading communication packets

### ISSUE THREAD

**Issue by oviliz** [firehol/netdata#1932]
My /var/log/mysql/error.log always reports this when restarting netdata
> Aborted connection 143050 to db: 'unconnected' user: 'netdata' host: 'localhost' (Got an error reading communication packets)

Not sure if this may help to avoid this error log, https://www.percona.com/blog/2016/05/16/mysql-got-an-error-reading-communication-packet-errors/

**Comment by ktsaou** [comment]
Hi, does this happens when netdata starts or randomly after it has been started?

The reason I ask is this: the netdata configuration files provide many alternative ways to connect to the mysql server. Many of them may manage to connect to the database. netdata detects this (they have the same `name` and are successful) and kills all but one. So, I would expect to see such a message when netdata starts, but I would not expect to have any such messages after netdata has started.

If this is the case (you have such messages when netdata starts), I suggest to edit `/etc/netdata/python.d/mysql.conf` and use only one way to collect data from the database.

If you have them randomly, after netdata is started, we will have to investigate this further. It could be the version of `python-mysqldb` you have, or something else.

**Comment by oviliz** [comment]
Hi Costa,

I have already removed everything in that file (to avoid multiple `Access denied for user ''@'localhost' (using password: NO)` or `Access denied for user 'root'@'localhost' (using password: NO)`) except for:
```tcp_netdata:
  name     : 'local'
  user     : 'netdata'
  # pass     : ''
  host     : 'localhost'
  port     : '3306'```
as I have created the netdata DB user.

Still, the above message generates whenever and only when I restart netdata.
Also, in only one server out of the two, I do have random `Access denied for user ''@'localhost' (using password: NO)` too.

Using on both Ubuntu 16.04 LTS while `python-mysqldb` comes from the repo. Python 2.7.12 on both.

**Comment by ktsaou** [comment]
ok. Could you please stop netdata for a while and run the plugin by hand, like this:

```sh
# become user netdata
sudo su -s /bin/sh netdata

# run the plugin in debug mode
/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug mysql
```

If the normal output bothers you, you can redirect it to /dev/null. The stderr contains all debug info.
Can you reproduce it?

**Comment by oviliz** [comment]
Whenever running the plugin in debug mode, I got the reported MySQL error. However, the `/var/log/netdata/debug.log` stays empty. Should I leave it running for a while in debug mode?

**Comment by ktsaou** [comment]
`debug.log` is only used to debug the core netdata daemon.
All plugins running in debug mode print out everything to your console.

So, you have only one database connection in `python.d/mysql.conf`, you are running the plugin in debug mode, it works, but you get the mysql `aborted connection` error on the database server.

@l2isbad any ideas?

@oviliz could you please run it like this and check the time you get the error on the database?

```sh
# become user netdata
sudo su -s /bin/sh netdata

# run the plugin in debug mode
/usr/libexec/netdata/plugins.d/python.d.plugin 30 debug mysql >/dev/null
```

The above will send all data collection output from the plugin to `/dev/null` (so that your screen will not scroll like crazy) and collect data once every 30 seconds.

When do you get the error on the db? before the first collection? after the first collection? on every data collection?

**Comment by l2isbad** [comment]
I don't think the connection terminates properly on the service restart.
Anyway the problem looks cosmetic to me (not an expert 😄 )

I have the same on ubuntu 16.04

> 2017-03-14T01:16:05.254695Z 37 [Note] Aborted connection 37 to db: 'unconnected' user: 'test' host: 'localhost' (Got an error reading communication packets)
> 2017-03-14T01:16:05.254871Z 31 [Note] Aborted connection 31 to db: 'unconnected' user: 'root' host: 'localhost' (Got an error reading communication packets

No errors on debian8/debian9 (mariadb)

**Comment by oviliz** [comment]
Good spot. :)
You're probably right, shouldn't be something to worry about. Thanks for your time guys.
