### ISSUE TITLE
ERROR 100: Cannot load chart library /lib/gauge-d5260c3.min.js

### ISSUE THREAD

**Issue by divgwd** [firehol/netdata#1981]
Hi,
After integrating the new kafka plugin while trying to view the netdata metrics via browser i get the below errors:
Cannot load required JS library: http://172.16.23.16:19999/lib/bootstrap-toggle-2.2.2.min.js
ERROR 100: Cannot load chart library: http://172.16.23.16:19999/lib/gauge-d5260c3.min.js

While compiling the new binary (including kafka) I notice that the binary is placed in /usr/local/sbin
`make[2]: Entering directory /home/divya/Netdata-Kafka_ver_1.1/netdata/src
test -z "/usr/local/sbin" || /bin/mkdir -p "/usr/local/sbin"
  /usr/bin/install -c netdata '/usr/local/sbin'
`
but the script tries to search for the binary in /usr/sbin/ path
`[netdata]# /usr/sbin/netdata -P /var/run/netdata.pid
./installer/functions.sh: line 140: /usr/sbin/netdata: No such file or directory
 FAILED
`
where should I edit so that the command to run the binary searches in /usr/local/sbin not in /usr/sbin ?

**Comment by ktsaou** [comment]
Hi,

1. you must be using an old version of netdata. The [current one](https://github.com/firehol/netdata/tree/master/web/lib) uses `gauge-1.3.2.min.js`.

2. the directory netdata is installed is controlled by `./configure`. So, I guess you re-configured netdata with different settings (the default is to put everything in `/usr/local`).

3. due to the above, the web directory is probably not there or does not have the right permissions. Try hitting the URL by hand and check netdata `error.log` for the issue.

I suggest to use `netdata-installer.sh` to re-install everything.

**Comment by divgwd** [comment]
Hi,
below is the code that was added in the configure.ac

`if test "${enable_plugin_kafka}" = "yes"; then
        pkg-config --libs rdkafka
        if test "$?" != "0"; then
              echo "rdkafka not found!!"
        else
                if test -z "$KAFKA_CFLAGS"; then
                        KAFKA_CFLAGS="pkg-config --cflags rdkafka"
                else
                        KAFKA_CFLAGS="$KAFKA_CFLAGS pkg-config --cflags rdkafka"
        fi
        if test -z "$KAFKA_LIBS"; then
                KAFKA_LIBS="pkg-config --libs rdkafka"
        else
                KAFKA_LIBS="$KAFKA_LIBS pkg-config --libs rdkafka"
        fi
        prefix=pkg-config --variable=prefix rdkafka
fi
        echo "KAFKA_CFLAGS ${KAFKA_CFLAGS}"
        echo "KAFKA_LIBS ${KAFKA_LIBS}"
        PKG_CHECK_MODULES(
               [KAFKA],
               [lrdkafka],
                #[zlib],
                [LIBS="-lpthread"],
        )
        AC_DEFINE([INTERNAL_PLUGIN_KAFKA], [1], [kafka plugin settings])
        OPTIONAL_KAFKA_CLFAGS="${KAFKA_CFLAGS} -I/usr/local/include/"
        OPTIONAL_KAFKA_LIBS="${KAFKA_LIBS} -L/usr/local/lib/"
fi
`

So, the 1.5_rolling netdata+kafka put the binary in the below path:


`make[2]: Entering directory '/home/divya/Netdata-Kafka_ver_1.1/netdata/src'
test -z "/usr/local/sbin" || /bin/mkdir -p "/usr/local/sbin"
  /usr/bin/install -c netdata '/usr/local/sbin'
test -z "/var/cache/netdata" || /bin/mkdir -p "/var/cache/netdata"
 /usr/bin/install -c -m 644 .keep '/var/cache/netdata'
test -z "/var/log/netdata" || /bin/mkdir -p "/var/log/netdata"
 /usr/bin/install -c -m 644 .keep '/var/log/netdata'
test -z "/var/lib/netdata/registry" || /bin/mkdir -p "/var/lib/netdata/registry"
 /usr/bin/install -c -m 644 .keep '/var/lib/netdata/registry'
test -z "/var/lib/netdata" || /bin/mkdir -p "/var/lib/netdata"
 /usr/bin/install -c -m 644 .keep '/var/lib/netdata'
test -z "/usr/local/libexec/netdata/plugins.d" || /bin/mkdir -p "/usr/local/libexec/netdata/plugins.d"
  /usr/bin/install -c apps.plugin '/usr/local/libexec/netdata/plugins.d'
`

And, the 1.5_rolling netdata from github puts it in the below path:


`make[1]: Entering directory '/opt/netdata/netdata/src'
 make[2]: Entering directory '/opt/netdata/netdata/src'
test -z "/usr/sbin" || /bin/mkdir -p "/usr/sbin"
  /usr/bin/install -c netdata '/usr/sbin'
test -z "/var/cache/netdata" || /bin/mkdir -p "/var/cache/netdata"
 /usr/bin/install -c -m 644 .keep '/var/cache/netdata'
test -z "/var/log/netdata" || /bin/mkdir -p "/var/log/netdata"
 /usr/bin/install -c -m 644 .keep '/var/log/netdata'
test -z "/var/lib/netdata/registry" || /bin/mkdir -p "/var/lib/netdata/registry"
 /usr/bin/install -c -m 644 .keep '/var/lib/netdata/registry'
test -z "/var/lib/netdata" || /bin/mkdir -p "/var/lib/netdata"
 /usr/bin/install -c -m 644 .keep '/var/lib/netdata'
test -z "/usr/libexec/netdata/plugins.d" || /bin/mkdir -p "/usr/libexec/netdata/plugins.d"
  /usr/bin/install -c apps.plugin '/usr/libexec/netdata/plugins.d'
make[2]: Leaving directory '/opt/netdata/netdata/src'
`

But, while the starting netdata+kafka  it searches in the /usr/sbin path

`Starting netdata...
[netdata]# /usr/sbin/netdata -P /var/run/netdata.pid
./installer/functions.sh: line 140: /usr/sbin/netdata: No such file or directory
 FAILED
`
but not in the /usr/local/sbin where the binary is put..where does the /installer/functions.sh take the path variable to check the netdata binary from??

**Comment by RiseEarly** [comment]
To give a brief of the above issue :

We are using the latest version of Netdata : 1.5.
We have added the KAFKA plugin, by checking the PKG-config and setting the appropriate KAFKA_CFLAGS and KAFKA_LIBS variables. These are the only changes done in configure.ac file.

Post this, the netdata started installing in /usr/local/sbin, while previously it was getting installed in /usr/sbin.
Before Kafka :            test -z "/usr/sbin" || /bin/mkdir -p "/usr/sbin" 
After including Kafa : test -z "/usr/local/sbin" || /bin/mkdir -p "/usr/local/sbin" 

Because of this, we are unable to start the netdata service. If we manually try to bring this up, we are getting JAvascript bootstrap errors. Not sure what change would have caused us this.  If you can help us in any way, it would save our day !! 

Thanks.

**Comment by ktsaou** [comment]
Well, I am trying to figure a way to help you, but I am not sure how.

What I always do, even when I test new plugins, I compile it with `netdata-installer.sh`, because autoconf dependencies are a nightmare:

1. If you change configure.ac, you need to run `./autogen.sh` again.
2. If you had compiled netdata before with a different `configure.ac`, you need to `make clean`.

So, I would follow this procedure:

1. path the source (makefiles, configure.ac, etc)
2. run the installer

If this still requires `/usr/local/...`, then somehow you are influencing autoconf. I would try to eliminate part of the changes and retry until I narrow it down to the statements that do this.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, just post.
