### ISSUE TITLE
Question - Can netdata monitor iptables?

### ISSUE THREAD

**Issue by jmcconocha** [firehol/netdata#1988]
Hi,
I have a need to monitor some Linux based firewalls. Is there (or can there be) a plug-in to monitor iptables?

The primary information I need to monitor are sessions through the server and iptables packet and byte counts, protocol, source and destination.

i was hoping there was already a plug-in for this... ;-)

Thanks,
Jeff

**Comment by ktsaou** [comment]
Well... given that netdata is a metrics tool, it already monitors plenty of these:

1. netfilter connection tracker: https://registry.my-netdata.io/#menu_netfilter
2. it can monitor netfilter accounting (nfacct - I don't have a demo for it)
3. it can monitor network bandwidth based on classes you configure: https://registry.my-netdata.io/#menu_tc

I understand however, you seek a tool like ntop, which unfortunatelly is not what netdata does...

**Comment by jmcconocha** [comment]
Thanks for the quick reply.
Actually, netfilter will give me what I need. :-)
Is netfilter a module that I need to add?
If so, where do i find it?
Thanks again,
Jeff

**Comment by jmcconocha** [comment]
I get, "errpr: netfilter_acct required but not found"
Where do I find it?

**Comment by ktsaou** [comment]
yeah... documentation...

to enable nfacct you need to install `libmnl-dev` and `libnetfilter_acct-dev`. Depending on your system the names might be slightly different...

Then you need to edit `netdata.conf` and set:

```
[global]
    run as user = root

[web]
    web files owner = netdata
    web files group = netdata
```

If you are on a systemd system, you may also need to edit `/etc/systemd/system/netdata.service` and instruct systemd to start netdata as `root`.

Unfortunately, only root can use these features. It is in my todo list to convert this internal plugin to an independent external plugin that will be setuid to root, so that netdata will continue to run as a non-privileged user.

To see anything related to netfilter accounting, you have to set it up with iptables. netdata will show charts/metrics for all metrics shown by the command `nfacct list`.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, just post.

**Comment by TimoKettunen** [comment]
FYI, this is not fixed. Just installed with kickstart and I get nfacct values only if I update the netdata.service as instructed here. Ubuntu 20.04.
