### ISSUE TITLE
Move python.d to proper module

### ISSUE THREAD

**Issue by Yamakaky** [firehol/netdata#2008]
It could be converted to a `netdata` package in `site-packages`. Also, the pyyaml* could use the version in the package manager of the distro.

**Comment by ktsaou** [comment]
I think netdata will use the pyyaml version of the system before attempting to use its internal. @l2isbad is that right?

We added pyyaml in netdata because a lot of folks had issues installing it and without it the python plugin is entirely disabled.

Then for adding `netdata` in python `site-packages`, I am not sure what will be the benefit. Other applications using the same plugins? All these are netdata specific and probably different versions of netdata may require different versions of them...

**Comment by l2isbad** [comment]
> I think netdata will use the pyyaml version of the system before attempting to use its internal

yes

https://github.com/firehol/netdata/blob/master/plugins.d/python.d.plugin#L28

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, just post.
