### ISSUE TITLE
Allow adding plugins in /etc/netdata

### ISSUE THREAD

**Issue by Yamakaky** [firehol/netdata#2009]

**Comment by ktsaou** [comment]
You mean adding code/scripts in `/etc`?
hm... distributions will complain... but I agree custom plugins should be added somewhere an updated netdata could never overwrite...

@alonbl what do you think?

**Comment by Yamakaky** [comment]
I don't see why they would complain. It's for user-written plugins, not standard ones. The current behaviour of writing code in /lib is not update-safe.

**Comment by alonbl** [comment]
@ktsaou why not have a configuration option where these extra plugins are located?

if a user wishes to have these in /etc so be it, I would have put it in /usr/local/.

however, better to be able to put plugins in /usr/lib/xxx /usr/libexec/xxx so that other packages may add more plugins by using managed packages.

**Comment by Yamakaky** [comment]
yes, /etc or /usr/local is only for user-written plugins.

**Comment by cransom** [comment]
Being able to specify multiple directories (not just hardcoded to /usr and /usr/local) would be useful to me. I run NixOS and pointing the plugins directories at a single path is much more complex to manage than having something like `plugins directory = /nix/store/netdata-custom-plugins/plugins.d/ /usr/libexec/netdata/plugins.d/`

**Comment by ktsaou** [comment]
ok, here it is: #2900

**Comment by ktsaou** [comment]
@cransom please test it.

**Comment by ktsaou** [comment]
merged it.
