### ISSUE TITLE
Netdata thinks it's out of date

### ISSUE THREAD

**Issue by blaines** [firehol/netdata#2026]
I can't explain the condition around this, but I was being prompted even though I appear to have the latest version! I'm using the docker version if that helps at all.

![screen shot 2017-03-27 at 9 09 50 pm](https://cloud.githubusercontent.com/assets/47128/24388798/f4095d72-1331-11e7-9906-89706d15e2b3.png)

**Comment by ktsaou** [comment]
Hi,

netdata gets new code every day. Since the main distribution is still by source, netdata checks the github repo for new commits.

This check is made once every 8 hours. So, most probably your netdata is always old...

`netdata-installer.sh` suggests a `ln -s` command when it is done. If you run it, and you have a working cron system, netdata will automatically be updated once per day. The command suggested is smart enough not to print anything when run from cron. So, if there is an update (there will be), and the script successfully installs the latest netdata, you will not get an email from cron. You will only get an email from cron, if the script cannot update netdata.

The reasons for the script to fail are:

1. it cannot fetch the github repo
2. the new netdata requires a package that is not available on your system
3. the new netdata fails to be compiled for some reason (compiler uninstalled, something else installed on the system that brakes netdata, etc)

Although there is a risk with automatic updates like that, a lot of users use it to keep their netdata updated.

On our part, just a few people control code merges. 99.9% of them are made by me. We carefully review all code merges to ensure code is of high quality and well tested before reaching the main repo.

Still, mistakes do happen, and there is some risk. Automatic updates means trust. You will trust this repo to install code on your systems. So, although we are very careful, this is entirely your decision and we cannot be held responsible if any issues arise.

**Comment by blaines** [comment]
I guess the issue I was experiencing was that the message was telling me I had commit `d67bc79` and the latest commit was also `d67bc79`. By that logic wouldn't I already be up to date?

**Comment by ktsaou** [comment]
oops! I missed that little detail. Sorry...
i will retest this functionality now...

**Comment by ktsaou** [comment]
hm....

firefox:

![image](https://cloud.githubusercontent.com/assets/2662304/24578042/1bb4417c-16e1-11e7-92c7-8045211b81a4.png)

chrome:

![image](https://cloud.githubusercontent.com/assets/2662304/24578049/34c84258-16e1-11e7-9aa0-f12a6089a4d5.png)

Linux chromium:

![image](https://cloud.githubusercontent.com/assets/2662304/24578057/5411cea4-16e1-11e7-8995-1a9fcd0bc4b0.png)

Opera:

![image](https://cloud.githubusercontent.com/assets/2662304/24578069/83d6d6c0-16e1-11e7-8c01-1a58da4d686e.png)

Edge:

![image](https://cloud.githubusercontent.com/assets/2662304/24578085/ca400870-16e1-11e7-8cb5-e19063470a34.png)

Safari 10:

![image](https://cloud.githubusercontent.com/assets/2662304/24578109/574ee11e-16e2-11e7-97ac-5a3ef3ff6e88.png)

Safari 9.1:

![image](https://cloud.githubusercontent.com/assets/2662304/24578113/7a8ffa50-16e2-11e7-9189-dc6807abca31.png)

Safari 8:

![image](https://cloud.githubusercontent.com/assets/2662304/24578123/a0ca6be2-16e2-11e7-9e8b-faf9fe6e086f.png)

hm... which browser do you use?
You may have a browser plugin that interferes somehow...

**Comment by blaines** [comment]
Interesting. Maybe there's a separate issue I'm not realizing.

![screen shot 2017-04-03 at 9 55 03 pm](https://cloud.githubusercontent.com/assets/47128/24641910/43a46b5c-18b8-11e7-83ed-8319f3d86716.png)

I did notice this message in my chrome debug console when selecting the update button.
```
GET http://netdata/version.txt?_=1491281607238 net::ERR_INCOMPLETE_CHUNKED_ENCODING
```
and confirmed it:

![screen shot 2017-04-03 at 9 56 45 pm](https://cloud.githubusercontent.com/assets/47128/24641948/7cf6cdc8-18b8-11e7-9c64-e134cf54f284.png)

Perhaps my security or other settings are too strict.

**Comment by blaines** [comment]
Do you think this is a bug with netdata?

**Comment by ktsaou** [comment]
Could you please check the file `/usr/share/netdata/web/version.txt` ?
Does it have anything in it?

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, just post.
