### ISSUE TITLE
Can we change Unit for IPv4 Inbound and IPv4 Outbound and the name fort the first system Overview

### ISSUE THREAD

**Issue by Misteralex007** [firehol/netdata#203]
Hi !

First, good job ! I like the design, it's easy to install, great job really.
But i want to kow if we can change the units for IPv4 Inbound & Outbound because i prefere to have these information in MB/s or at least Mbps.

![ss 2016-04-09 at 08 15 31](https://cloud.githubusercontent.com/assets/5701579/14405468/e2a58f9a-fe8f-11e5-9d22-f1d0c68b7e72.png)
](url)

So if we can change, tell me where in the configuration file.

Regards,
Misteralex007

**Comment by ktsaou** [comment]
Thanks!

It can be done by editing `/etc/netdata/netdata.conf`. Unfortunately, it is controlled per dimension, so you will have to edit several settings.

In all charts you are interested, find the `divisor` for each dimension and multiply it by 1000. You can also change the unit of the charts (to show Mbps instead of Kbps).

Yes, I know this is not efficient enough...

**Comment by Misteralex007** [comment]
Yo
![ss 2016-04-09 at 08 15 31](http://puu.sh/oc8VK/e764d00cab.png)
I change two lines but i don't find the lines to change the name Kbps and i'm not sure that the line that i change are the good.

**Comment by ktsaou** [comment]
What you are changing is the `drops` chart.
Not this one. Find its exact name from the dashboard.

**Comment by paulfantom** [comment]
@Misteralex007 did you manage to solve this?

**Comment by Misteralex007** [comment]
Not yet. I have not been trying since the answer.
And you ?

**Comment by ktsaou** [comment]
ok. I am closing this. @Misteralex007 if you need help, just post, we will re-open it.
