### ISSUE TITLE
Can't change oom_killer value

### ISSUE THREAD

**Issue by zcatbear** [firehol/netdata#2036]
The oom_killer value is unable to be changed post start which causes problems.  

Netdata isn't the first thing I want to die when the oom_killer comes looking for something to kill. Netdata as a system monitor has great values in introspection into why things are running out of memory and if it is the first thing to die then you lose valuable insight into what the problem might be, along with it's alerting capabilities. 

The oom killer value can only be adjusted after it has already been started which is less than advantageous. The textbook answer is to have a `netdata.service.d` directory with a `netdata.conf` file inside it that sets the desired oom killer value (or uses a default). 

I know my environment file is being loaded because a partial output from `systemctl cat netdata` returns:  
```
# /usr/lib/systemd/system/netdata.service.d/netdata.conf
[Service]

Environment=OOMScoreAdjust=-1000
```
All of these changes become moot however due to the daemon.c file. 

https://github.com/firehol/netdata/blob/5e362d7fafd11d6d582482565362169e25852fa9/src/daemon.c#L158

That function specifically sets the oom killer value to 1000 which almost invariably means that it will be the first process to die, and thus lose all alerting capability. 

The remedy should be something either configurable via command line flag to set the number myself in the ExecStart command or able to be overridden via the service file method I tried.  

This was all done on a CentOS 7.3 server.

**Comment by ktsaou** [comment]
Hi, check your `netdata.conf`. It should have (among other things):

```
[global]
	# OOM score = 1000
```

So, just set it in netdata.conf.

Keep in mind that processes can lower their OOM score only if they run as root. Netdata does this before switching to the netdata user, but it has to be started as root. The `netdata.service` shipped with netdata starts netdata as non-root, so it will not be able to lower it. In this case, either instruct systemd to start netdata as root (netdata will switch to the user defined with `run as user` in netdata.conf), or set the same oom score to both netdata.service and netdata.conf.

hm... it sounds complicated... I didn't had in mind systemd when I developed this. I guess I could make it accept the value `as-is` or `no-change` in `netdata.conf`, so that netdata.service will do the job alone...

I could also support the environment variable `OOMScoreAdjust`...

Let me fix that...

**Comment by ktsaou** [comment]
ok, here it is.

Now netdata uses the variable `OOMScoreAdjust` too. Also non-numeric values in `netdata.conf` make it leave its OOM score unchanged.

Keep in mind you can set any `netdata.conf` value from the command line, using this:

```sh
netdata -W set global "OOM score" "-50"
```

You can append as many `-W set` as needed.

**Comment by ktsaou** [comment]
merged it.
The issue closed automatically.
If something is missing, let me know.
