### ISSUE TITLE
Failed to discover init service on Centos 6.6

### ISSUE THREAD

**Issue by pol** [firehol/netdata#2056]
Here's what the installer printed out:

```
 --- Install netdata at system init ---
I don't know what init file to install on system 'CentOS release 6.6 (Final)'. Open a github issue to help us fix it.
 FAILED  Cannot install netdata init service.

 --- Start netdata ---
[/root/build/netdata]# /sbin/service netdata stop
netdata: unrecognized service
 FAILED

[/root/build/netdata]# /sbin/service netdata restart
netdata: unrecognized service
 FAILED

[/root/build/netdata]# /sbin/service netdata start
netdata: unrecognized service
 FAILED
```

I have done this successfully on Centos 6.8, so I am not sure what the difference is or why it would fail on this machine.  I am going to do the manual method of service installation.

**Comment by ktsaou** [comment]
Hi.

This happens because we are not sure what it the proper init file for centos 6.6. This is the code that does this: https://github.com/firehol/netdata/blob/543f65452d55a0d30b22214c6e1ee299c160b87b/installer/functions.sh#L421-L427

So, you can try to copy the same file used for centos 6.8.
If it works, I would appreciate it if you report this back, so that we will whitelist it to be enabled automatically in the future.

**Comment by pol** [comment]
I did copy the file, and it does work.  You can whitelist it for use in centos 6.6.

**Comment by ktsaou** [comment]
Thanks! Added it.

**Comment by ktsaou** [comment]
merged the change
