### ISSUE TITLE
disk_backlog, packet storm, packets dropped, server unaccessible

### ISSUE THREAD

**Issue by slrslr** [firehol/netdata#2085]
Hello,

this night i received Netdata e-mails:

> 10min disk backlog - disk_backlog.dm-0
> 10min disk backlog = 5632 ms
> average of the kernel estimated disk backlog, for the last 10 minutes Alarm
> / Family

dm0 is HW Raid 1 volume out of two 7000RPM HDDs. 3 minutes later i received another e-mail:

> 10s received packets storm - net_packets.venet0
> 10s received packets storm = 189424769%
> the % of the rate of received packets in the last 10 seconds, compared to the rate of the last minute

venet0 is the network interface made for OpenVZ virtual servers (VPS's).

some hours after that there is other e-mail:

> net_packets.venet0
> outbound packets dropped ratio = 223.1%
> the ratio of outbound dropped packets vs the total number of sent packets of the network interface, during the last 10 minutes

A few hours later i logged in via SSH and the connection was interrupted, server do not respond icmp, can not connect it.

Please what might be the problem in this case? What can be relation of the disk_backlog to the packet storm / packet dropping? What do you suggest please?

**Comment by ktsaou** [comment]
It may be many things:

1. You run a backup or something very intensive
2. You are under attack
3. Your service provider is facing difficulties

So, you have to examine the charts and your logs to find out what exactly is happening. Usually, I increase netdata history to 8 or 10 hours, so that I have the time to examine the charts later...

You can also mirror metrics from all hosts to a central netdata that has a few days of history with `memory mode = map` (check this: https://github.com/firehol/netdata/wiki/Memory-Requirements#running-a-dedicated-central-netdata-server)

Or, you can archive all metrics to opentsdb/graphine/influxdb/prometheus and use grafana to visualize them.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, just post.
