### ISSUE TITLE
Custom Chart Range

### ISSUE THREAD

**Issue by wankbank** [firehol/netdata#213]
I'm not sure if this is within the scope of how data is able/intended to be presented, although is it possible to specify a longer range for a particular charts data to be displayed at once?

For example, I would like to show 12 hours of load average in one view:

![load](https://cloud.githubusercontent.com/assets/7131680/14473353/7870ca26-00ac-11e6-9145-68b3d027c82d.png)

In some circumstances it would help to see an extended range of time beyond five minutes (eg. to quickly view when there was a spike in load during the past 12 hours, etc.); is there a setting to change the range of time viewable?

**Comment by ktsaou** [comment]
You can zoom out the charts, but the default history is an hour.

The default DB for netdata is just one hour. You can increase this by editing the configuration `/etc/netdata/netdata.conf` and setting `history` to the number of seconds you need. Please read the wiki page [Memory Requirements]() before you do this.

The latest version of netdata, has some more buttons to help you understand how to use the charts.

**Comment by wankbank** [comment]
@ktsaou. thanks for the infomation, although I believe that I tried that and it still only displayed five minutes at a time in the current view, and I had to swipe left or right to go beyond a five minute time period. 

I'm trying to condense 12 hours of data on the single view without having to scroll left/right. I'm guessing this isn't really possible?

**Comment by ktsaou** [comment]
ok. Here it is:

![image](https://cloud.githubusercontent.com/assets/2662304/14477937/0a35d394-011a-11e6-8440-965db6f8a69f.png)

It can be done. But you have to learn how.
Go to http://netdata.firehol.org

Each chart has this at its lower right corner:

![image](https://cloud.githubusercontent.com/assets/2662304/14477954/3706fd6c-011a-11e6-812c-0c77ef845284.png)

Press the ` - ` to zoom out. It will zoom out.

If your netdata does not have this button, it is because I added it to netdata yesterday. You have to re-install it. If you already have re-installed it but the button is not there, just press Control-F5 on the dashboard, to force your browser update its cache.

Even on older versions, you can zoom out using your mouse wheel, if you use Chrome or Opera (sorry - It does not work on Firefox and IE). To zoom out, press SHIFT and then roll the mouse wheel while your mouse is over the chart you are interested.

**Comment by wankbank** [comment]
That's exactly what I was looking for! It seems as if you almost literally read my mind by adding those new buttons.

I'll grab the latest version — thanks for the quick response all the great work  :)

**Comment by ktsaou** [comment]
ok. I close this.

**Comment by svrnwnsch** [comment]
I have another question about this.
After zooming out the dashboard does not get refreshed with new data. How can I change that behavior?

**Comment by cakrit** [comment]
UI help button:
```
Once a chart is zoomed, auto refreshing stops for all charts. To enable it again, double click a zoomed chart.
```
Clicking the play button under the legend does the same thing.

**Comment by svrnwnsch** [comment]
Yes, but this play button also zooms back in again. I want to see the chart zoomed out and have it updated with new data.

**Comment by cakrit** [comment]
#5613 created.
