### ISSUE TITLE
netdata on Mac OS Sierra (10.12)

### ISSUE THREAD

**Issue by XBeg9** [firehol/netdata#2152]
Using this guide: https://github.com/firehol/netdata/wiki/Installation#macos
netdata installer can't create user group and user itself... I am running command with `sudo`, no lack :(

here is log:
```
--- Add user netdata to required user groups --- 
Adding netdata user group ...
Failed to add netdata user group !
 FAILED  The installer does not run as root. 

 --- Install logrotate configuration for netdata --- 
 --- Read installation options from netdata.conf --- 
 --- Fix permissions of netdata directories (using user 'netdata') --- 
[/Users/*****/netdata]# chown -R netdata:netdata /Users/*****/opt/netdata/etc/netdata 
chown: netdata: illegal group name
 FAILED
```

**Comment by ktsaou** [comment]
hm... strange... could you please add the netdata group by hand and retry?

**Comment by ktsaou** [comment]
@vlvkobal any ideas?

**Comment by XBeg9** [comment]
@ktsaou I don't know how it worked in previous, but in Mac OS to add user to group we need this `sudo dseditgroup -o edit -a $username_to_add -t user admin`, we don't have common `useradd`, `groupadd` commands.

**Comment by ktsaou** [comment]
Wow! I didn't know this.

netdata installer uses [6 bash functions](https://github.com/firehol/netdata/blob/8be402dd43160d0974deb9f5475ce26237c76513/installer/functions.sh#L182-L324) to do the job:

1. `portable_check_user_exists()`
2. `portable_check_group_exists()`
3. `portable_check_user_in_group()`
4. `portable_add_user()`
5. `portable_add_group()`
6. `portable_add_user_to_group()`

Can you help me write them for macos?

**Comment by dkmansion** [comment]
We had the same group errors on install in Sierra.  I did this...

```
dscl . -create /Groups/netdata
dscl . -create /Groups/netdata UniqueID “400”

dscl . -create /Users/netdata
dscl . -create /Users/netdata UserShell /bin/bash
dscl . -create /Users/netdata RealName “netdata” 
dscl . -create /Users/netdata UniqueID “400”
dscl . -create /Users/netdata PrimaryGroupID 400
dscl . -create /Users/netdata NFSHomeDirectory /Users/netdata
dscl . -passwd /Users/netdata "somePassw0rdHere"

dscl . -create /Groups/netdata GroupMembership netdata
```
You may need to specify a different ID for user and group instead of my 400 which is listed.
Might not need NFSHomeDirectory really for everyone else.

**Comment by alexncus** [comment]
Also having same error in Sierra (MAC OS X):

>  --- Add user netdata to required user groups --- 
> Adding netdata user group ...
> Failed to add netdata user group !
>  FAILED  The installer does not run as root. 
> 
>  --- Install logrotate configuration for netdata --- 
>  --- Read installation options from netdata.conf --- 
>  --- Fix permissions of netdata directories (using user 'myuserid') --- 
> [/Users/master/netdata]# chown -R myuserid:myuserid /Users/myuserid/opt/netdata/etc/netdata 
> chown: myuserid: illegal group name
>  FAILED

**Comment by alexncus** [comment]
Got it to work on Sierra MAC OSX:

1. added a new group in System Preference -> Users & Groups -> Group -> netdata
2. changed all of the FAILED "chown -R myuserid:myuserid" to sudo "chown -R myuserid:netdata"

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.

**Comment by aizaimenghuangu** [comment]
We had the same group errors on install in Sierra. I did this...

As sudo ie

sudo su
dscl . -create /Groups/netdata
dscl . -create /Groups/netdata UniqueID “400”

dscl . -create /Users/netdata
dscl . -create /Users/netdata UserShell /bin/bash
dscl . -create /Users/netdata RealName “netdata” 
dscl . -create /Users/netdata UniqueID “400”
dscl . -create /Users/netdata PrimaryGroupID 400
dscl . -create /Users/netdata NFSHomeDirectory /Users/netdata
dscl . -passwd /Users/netdata "somePassw0rdHere"

dscl . -create /Groups/netdata GroupMembership netdata
You may need to specify a different ID for user and group instead of my 400 which is listed.
Might not need NFSHomeDirectory really for everyone else.

after that,check the error.log 
the error like 
2017-09-03 11:26:54: netdata ERROR: 3: File '/Users/XXXXX/opt/netdata/usr/share/netdata/web/' is owned by group 501 (expected group 20). Access Denied.

just  : sudo chown -R 501:20  /Users/XXXXX/opt/netdata/netdata/
