### ISSUE TITLE
Performance issue when proxied behind lighttpd

### ISSUE THREAD

**Issue by mz2212** [firehol/netdata#2186]
I'm running netdata on my Raspberry Pi with lighttpd, and the client connection counter is [really strange](https://lh3.googleusercontent.com/-5ZOZp76BB5Q/WRexOxG8H9I/AAAAAAAADro/3mB9AiQAgRUmxYnjKMBoz8epz1X_NvT7QCHM/s0/firefox_2017-05-13_19-22-07.png) and it seems to use a ton of CPU (20-30% while the page is focused). 
Without the lighttpd proxy/url rewrite, the client connections generally stay [around six](https://lh3.googleusercontent.com/-meUzd3qfdv4/WRe09GQtiPI/AAAAAAAADr8/wm4uO9YQYdsjn781gSGNZAypna0IA5r3ACHM/s0/firefox_2017-05-13_19-38-00.png) and the CPU usage is much lower (1-5% while focused).

OS: `Rasbian Jessie`
netdata version: `1.6.1_rolling`
lighttpd version: `1.4.35 (ssl)`

Thanks for any help you might be able to provide!

**Comment by ktsaou** [comment]
Your lighttpd server does not send HTTP `keep-alive` to netdata, so a new connection is created for every chart refresh.

Unfortunately, I don't know how to do this with lighttpd.

**Comment by mz2212** [comment]
That does make sense, it looks like that was a planned feature of `ModProxyCore` however the branch that the feature was a part of is [now dead](https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModProxyCore).
Looks like nginx might be better suited to this job, thanks!

**Comment by gstrauss** [comment]
Besides lighttpd, haproxy and nginx are also excellent choices for reverse proxies.

Unfortunately for lighttpd, most versions of Debian (including Jessie) run criminally old versions of lighttpd.  (lighttpd 1.4.35 in Jesse is over 3 years old.)  The latest version of lighttpd is 1.4.45, and lighttpd 1.4.46 is coming soon.

Still, even the current version of lighttpd, mod_proxy does not keep persistent connections to backends.  I would be surprised if the new socket connection were the bottleneck instead of the chart generation, but am interested if you have found otherwise.

**Comment by ktsaou** [comment]
> I would be surprised if the new socket connection were the bottleneck instead of the chart generation, but am interested if you have found otherwise.

With `[web].mode = multi-threaded`, for each connection, netdata spawns a thread. So, every connection is autonomous. If keep-alive is not available, netdata spawns a thread for each chart refresh. This increases the load.

If keep-alive is not available, the best is to set netdata web mode to single-threaded.

**Comment by gstrauss** [comment]
@ktsaou that sounds like the bottleneck is in netdata.

As you mentioned, netdata web mode "single" or "single-threaded" is recommended if the connecting client (or proxy) does not support keep-alive.  Single-threaded mode is probably also a good idea on smaller devices, e.g. a Raspberry Pi.

To remove the bottleneck, and place an upper bound on thread creation, what do you think of the following?  If netdata were to do a single-threaded accept() and web_client_receive(), then web_client_process_request() could be dispatched to a thread in a thread-pool of one or more persistent processing threads.  The main thread could handle web_client_send() when the processing was completed.  A simple implementation could remove read/write interest from client fd while the response was being generated.

**Comment by ktsaou** [comment]
Yes, that could be done. Actually linux has a nice signalfd feature that allows the workers to be synchronized without pipes and locks.

Still, the lack of keep-alive is a problem for web applications like netdata, where each client makes thousands of requests. Accepting a new socket requires a lot of work, including a lot of memory allocations, while serving an existing socket introduces minimal overheads.

**Comment by gstrauss** [comment]
> each client makes thousands of requests

Wow.  That sort of activity might be more efficient if done via HTML5 websockets rather than keep-alive requests.  You'll get "keep-alive" for free with a websocket connection.  With basic HTTP keep-alive, thousands of requests still far exceed the default value for the most popular web servers.  Unless otherwise configured, Apache and nginx default to allow 100 keep-alive requests from a client before closing the connection, and the next version of lighttpd (lighttpd 1.4.46) will, too.

**Comment by ktsaou** [comment]
websockets are nice, but:

1. they do not work under all conditions
2. for the netdata case they will be quite hard to implement (since the server will need to keep track of the charts in the current viewport of the browser in order to push metrics only for these charts)
3. they will only save some of the http headers exchanged with each request, so no significant bandwidth savings either.

So, yes it will be ideal to use websockets, but I am not sure they justify the complexity.

Another improvement would be to incrementally update the charts. Now the whole charts are transferred on each chart refresh. This wastes bandwidth. But I preferred not to do any processing on chart data at the browser. The server is sending exactly whatever each chart library expects, in JSON. Incremental transfers would be nice, to save some bandwidth (the chart libraries do not support incremental updates - they always refresh the whole chart, so there will be no processing benefit at the browser).

**Comment by ktsaou** [comment]
btw, re-opening a socket every 100 requests is ok. The average page has 10 charts, the browsers these days open 6 sockets. So, 6 sockets * 100 = 600 chart refreshes / 10 charts refreshed per second = 60 seconds. So, the sockets will be re-opened once per minute. It is ok...
