### ISSUE TITLE
Display backend archived data directly in netdata

### ISSUE THREAD

**Issue by nicolasbadia** [firehol/netdata#2228]
First let me say that I find Netdata pretty awesome! Thanks a lot for your work.

I believe it would be even more awesome if by default, netdata would install a backend (prometheus for example) and store long term history in it.
Netdata would continue to store precise short term metrics in memory, but as soon has you would go back in time, it would start querying the backend to display archived data.

Is there any plan to do that?

**Comment by viewty** [comment]
I'm not a dev so can't speak for them but I suspect the answer will be along the lines of:

No because if you want to store to a backend, then picking which one and the parameters of the storage should be up to the user, not automated. It also adds additional complexity as Prometheus is actively developed so things change (the upcoming 2.0 release will break quite a few things in the existing 1.* branch).

Adding a backend is not overly complex, they have documented using a few different ones.

**Comment by ktsaou** [comment]
It could be a solution.

My strategy however, is to improve host autonomy to the maximum.

I plan to provide a new memory mode, that will use some RAM as cache, and a large disk file, bundled with deduplication and compression. Something like `memory mode = map` but netdata controlled and more feature rich (`memory mode = map` is kernel controlled, like swap memory).

A major re-work of netdata could also allow it to use variable step memory pages, so that older data have less detail than newer data (ie. data will fade out).

The idea with netdata is to distribute monitoring as much as possible, be very fast, very efficient, very detailed and just a little bit on all servers...

**Comment by ktsaou** [comment]
Cleaning up.
