### ISSUE TITLE
how to add a custom plugin by C 

### ISSUE THREAD

**Issue by Ran2ger** [firehol/netdata#2268]
Hey guys :
I would like to try to use C language to write a plugin ( using the native netdata plugin API), I have read the [document](https://github.com/firehol/netdata/wiki/External-Plugins), but less with C language.
I'm a rookie,forgive me for such a stupid question.

**Comment by ktsaou** [comment]
There are many examples already in the code.
To give you directions, is your plugin going to need a separate thread? If it needs to have control of the execution all the time, or data collection is expected to be time consuming, you will need a separate thread. Otherwise you can hook it to an existing thread.

**Comment by Ran2ger** [comment]
Well, I guess it needs a separate thread.
I'm considering to use it to display the serial input data.
Is there any C example to display the Example Charts ,I wanna take it for a reference.
Tank you!

**Comment by ktsaou** [comment]
ok.

1. You can add another thread here: https://github.com/ktsaou/netdata/blob/793dcded1f97a5493375bb241c8903587426ce39/src/main.c#L59-L59 - I have selected statsd that is a standalone thread.

2. `statsd_main()` is a good example for a plugin, since it has everything (read configuration variables, setup a few charts and update charts with values): https://github.com/ktsaou/netdata/blob/fe7a0a04cf739a46ceea27a8722d47cc21497368/src/statsd.c#L1719-L1719

3. You can add a new file in netdata makefiles by adding it here: https://github.com/ktsaou/netdata/blob/5f6dfc9ee8cd469c33e647a6f4957e97619faa67/src/Makefile.am#L124-L124

Generally, statsd is a good example, since it is pretty an isolated plugin. You can grep the code for `statsd` or `STATSD` to find what else was added for it to netdata.

**Comment by Ran2ger** [comment]
Hi,
I grep statsd in the configuration file,and I found it is only exit in the netdata.conf .And I have read this [document](https://github.com/firehol/netdata/wiki/statsd#gauges)
 I get some troubles. 
1. I change a chart's title in statsd.c,and use #make after change.But after the restart netdata, it still show the previous title.
2.In order to display the input data, can I directly change statsd.c? If so, where to change the value of the input.
Thank you!

**Comment by Ran2ger** [comment]
Hi,
I grep statsd in the configuration file,and I found it is only exit in the netdata.conf .And I have read this document

I get some troubles.
1. I change a chart's title in statsd.c,and use #make after change.But after the restart netdata, it still show the previous title.
2. In order to display the input data, can I directly change statsd.c? If so, where to change the value of the input.

Thank you!

**Comment by Ran2ger** [comment]
Hi,
I grep statsd in the configuration file,and I found it is only exit in the netdata.conf .

I get some troubles.

1. I change a chart's title in statsd.c,and use #make after change.But after the restart netdata, it still show the previous title.

2. In order to display the input data, can I directly change statsd.c? If so, where to change the value of the input.

Thank you!

**Comment by ktsaou** [comment]
hm... I am not sure I understand. You should not change the statsd plugin. This is dangerous. The right way is to add your own. I suggested statsd as an example of how the internal API works.

If this is too hard for you, I suggest to use an external plugin. BASH (charts.d) is the simplest and requires minimal knowledge. python is best these days. C is the hardest and you should only use it when it is absolutely necessary.

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
