### ISSUE TITLE
sudo 'validate' command not allowed

### ISSUE THREAD

**Issue by deurk** [firehol/netdata#2435]
Since I installed netdata on a Debian Jessie, I have now a few times a day the following error popping in my SSH sessions:

`netdata : command not allowed ; TTY=unknown ; PWD=/etc/netdata ; USER=root ; COMMAND=validate`

I have not been able to find out what `validate` command should be available, can you point me towards a package I should install?

Thank you.

**Comment by ktsaou** [comment]
Hi,

There are a few plugin that can only work as root. These plugins attempt to execute `sudo -n some_command`. `-n` stands for `validate`. If you have not configured sudoers to allow user netdata execute these commands, they fails at the validation state.

Currently only the samba plugin does this. It needs to execute `smbstatus` which is only allowed to run as root (it cannot even be give the setuid bit).

Normally, you should have just 1 such log, every time netdata is restarted. If it is not restarted, there should not be any.

Unfortunately, the developers of samba have not allowed any alternatives. So, for netdata to autodetect samba, has to do this.

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.

**Comment by shmocs** [comment]
Hello.
with latest update (6832ce4) even if I set samba = no in netdata.conf in  plugin section... it still gives me this:

`[root@vivresn3 netdata]# service netdata status
Redirecting to /bin/systemctl status netdata.service
● netdata.service - Real time performance monitoring
   Loaded: loaded (/etc/systemd/system/netdata.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2018-08-01 15:50:12 EEST; 1min 36s ago
  Process: 12483 ExecStartPre=/bin/chown -R netdata:netdata /var/cache/netdata (code=exited, status=0/SUCCESS)
  Process: 12481 ExecStartPre=/bin/mkdir -p /var/cache/netdata (code=exited, status=0/SUCCESS)
 Main PID: 12486 (netdata)
   CGroup: /system.slice/netdata.service
           ├─12486 /usr/sbin/netdata -P /run/netdata/netdata.pid -D
           ├─12559 bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
           ├─12561 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
           └─12575 /usr/libexec/netdata/plugins.d/apps.plugin 1

Aug 01 15:50:11 server1.mydomain.ro systemd[1]: Starting Real time performance monitoring...
Aug 01 15:50:12 server1.mydomain.ro systemd[1]: Started Real time performance monitoring.
Aug 01 15:50:14 server1.mydomain.ro sudo[12823]:  netdata : command not allowed ; TTY=unknown ; PWD=/etc/netdata ; USER=root ; COMMAND=validate
Hint: Some lines were ellipsized, use -l to show in full.`

**Comment by ammgws** [comment]
Are you sure you edited the correct file? It should be in `/etc/netdata/python.d.conf`.
