### ISSUE TITLE
Differences in RAM utilization display

### ISSUE THREAD

**Issue by xfakt-pj** [firehol/netdata#2461]
Why is it that the circular ram usage gauge on top of the netdata dashboard shows me the following RAM usage:

![2017-07-14 12_29_38-xfakt-virt-host-0 netdata dashboard](https://user-images.githubusercontent.com/24892191/28208888-44d15224-6890-11e7-974d-4fcf3cf354f8.png)

While the badge shows a lower amount:

![2017-07-14 12_30_07-xfakt-virt-host-0 netdata dashboard](https://user-images.githubusercontent.com/24892191/28208889-44d1e1f8-6890-11e7-976a-8add7b27074b.png)

What the badge shows corresponds with what the proxmox dashboard (Virtualisation hypervisor) shows on the same server at roughly the same time.

I also added the following graph from the same time period:

![2017-07-14 12_29_52-xfakt-virt-host-0 netdata dashboard](https://user-images.githubusercontent.com/24892191/28208887-44cffd84-6890-11e7-855e-41d897707610.png)

I then calculated: (using the values from the graph)
![2017-07-14 12_39_24-calculator](https://user-images.githubusercontent.com/24892191/28209215-e2749e0e-6891-11e7-93d4-95da97e5c2ff.png)

But the top circular gauge shows a value of 82.8%, which amounts to ((total_ram = 24100)/100) * 82.8 = 19954.

Is something going wrong here? Am I not doing my math correctly?

**Comment by ktsaou** [comment]
Hi,

The alarm shows a different percentage because it ignores memory used by zfs arc.
This has been done at the alarm to prevent it from sending low-memory alarms just because all the memory is used by zfs arc.

However, the memory is really used, at least as far as the kernel is concerned. So the chart shows whatever all console tools show.

(btw `(17728−4096) × 100 ÷ (17728 − 4096 + 3220 + 930) = 76.67`, not `17.782`)

**Comment by xfakt-pj** [comment]
My bad indeed. I have stepped away from ZFS on this host for now, so no further testing is required. Thanks for the explanation though!
