### ISSUE TITLE
badge questions

### ISSUE THREAD

**Issue by cgoze** [firehol/netdata#2508]
Hello,

I'm trying to create a badge. I read the wiki page on it, it's quite clear on how to do it. I can have one with my browser, but I don't understand which file I have to modify to display my badge on the dashboard.

Also, I understood that a badge is tied to a chart, is it possible to hide the chart but still display the badge ?

Thanks for your answer !

**Comment by ktsaou** [comment]
Hi,

Badges are good for embedding them in third-party sites and custom dashboards.
So, you can add it, the same way you add an image, to any web site.

The [wiki](https://github.com/firehol/netdata/wiki/Generating-Badges#how-to-create-badges) says that if you want your badge to autorefresh, instead of `<img src=...`, you can use this:

```html
<embed src="BADGE_URL" type="image/svg+xml" height="20" />
```

and of course, add `&refresh=SECONDS` to the URL.

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
