### ISSUE TITLE
[Discussion] Expert opinion needed in a discussion on Grafana community

### ISSUE THREAD

**Issue by kmonsoor** [firehol/netdata#2515]
I have raised an issue to add Netdata as a listed collector for Grafana dashboard. 
Link:  https://community.grafana.com/t/please-add-netdata-as-a-collector/1978

Now, the concern is about Netdata's plugin structure for proper configuration on dashboard in contrast with StatsD or Apache log-collector. It is discussed to make the enlistment proper.

I have inputted what I could as a limited user. However I think, further expert opinion (for integration with Grafana) would be great for both community.

**Comment by vbonline** [comment]
The concerns from the Grafana side are valid. 
Why do you want Grafana in the first place? Because netdata collect WAY to fast (once per second) for historical data (like six month). So you have to average the data over lower sampling frequency. This is what backends in netdata are for...
So collect with netdata, forward with lower frequency (120 sec. in our case (80+ linux servers)) to influxdb via opentsdb and build a Grafana dashboard for the influx database.
Due to the autodetection of plugins you'll never be able to generate a common Grafana Dashboard for all netdata instances

**Comment by ktsaou** [comment]
Hi,

hm... I am not sure I get the problem. In more detail I am not sure I understand this:

> Now, the concern is about Netdata's plugin structure for proper configuration on dashboard in contrast with StatsD or Apache log-collector. It is discussed to make the enlistment proper.

Could you please explain the problem a bit more?

**Comment by kmonsoor** [comment]
@ktsaou hi, i'm sorry for this extra-long ambiguous sentence. Possibly, I was high on caffeine.

In summary what I was trying is to draw expert attention to the thread I mentioned in the initial comment.

**Comment by ktsaou** [comment]
ok, thanks. I joined the discussion there.
