### ISSUE TITLE
How to configure stream with HTTPS and authentication?

### ISSUE THREAD

**Issue by simonszu** [firehol/netdata#2590]
Hi,

i have set up netdata behind a reverse proxy with TLS and http auth. This works fine for accessing the graph dashboard. 
Now i have some problems with configuring some slaves to stream to this node. I have made this configuration in the stream.conf of the node: 

```
[stream]
    enabled = yes
    destination = https://username:password@netdata.myhost.de:443
    api key = foobar
```

However, this results in lots of "Connecting - Failed to connect..." errors in the log file. So i was wondering, is the netdata streaming logic capable of streaming via HTTPS? Can it be used with HTTP auth? Or is it just a problem with my config?

**Comment by ktsaou** [comment]
Hi,

unfortunately the streaming protocol is not HTTP. We should convert it to web sockets ( #2507 ).
So, currently you have to bypass the proxy for it to work.

For the authentication, the API key does the job. API keys are random GUIDs.

**Comment by MaikStohn** [comment]
Hi,

I just had the same question. I want to stream (headless) from several servers from the internet to a collector in a secure way. The API key is not a real security feature since it can be sniffed from transmissions easily.

The obvious thing would be to add TLS.
==> You do not need to speak HTTP(S). Just every socket connection can add TLS on top of it. OpenSSL has great examples for it (https://github.com/openssl/openssl/tree/master/demos/bio  check server and client samples).

Is this something you would consider to add in the future or are your plans to rewrite the streamer to use web sockets?

BTW: This project is great. It was just a bit hard to find for me when looking for "Remote Server Monitoring".

Maik

**Comment by ktsaou** [comment]
Hi,

yes, to both questions: I plan to add SSL to netdata (also support HTTPS natively) and convert the stream protocol to web sockets (so that it will be proxy friendly).

**Comment by ktsaou** [comment]
Cleaning up. If you need more help, just post here.
Both requests are already in my todo list.

**Comment by netchild** [comment]
Any news about this? SSL is working for streaming, but what about http authentication? Reason for me: netdata behind a reverse proxy (nginx) with basic authentication configured. So netdata on site A is supposed to open a TLS connection to nginx on site B, use http basic authentication and then deliver to the netdata master.

**Comment by larbi-ishak** [comment]
you can try this, its netdata behind nginx auth
https://hub.docker.com/repository/docker/larbizyoisco/netdata/general
