### ISSUE TITLE
some confuses about netdata.conf

### ISSUE THREAD

**Issue by zhangxin0112** [firehol/netdata#2594]
my pc node1's netdata.conf  plugins : 
![image](https://user-images.githubusercontent.com/8244097/29259643-a8084f22-80f6-11e7-81dc-457020d48d6f.png)
I brower my 19999 : 
![qq 20170814134750](https://user-images.githubusercontent.com/8244097/29259774-aab8239a-80f7-11e7-85e7-d9b376e201c4.png)

but in my other pc the same netdata.conf as pc node1 the web 19999:
![qq 20170814134855](https://user-images.githubusercontent.com/8244097/29259770-9aac5d4a-80f7-11e7-8cfc-91dfc73dc0ef.png)

**# why the same conf show the different charts ?**

**Comment by ktsaou** [comment]
Hi,

the config enables or disables things, it also changes their settings, but netdata always autodetects what can be collected or not. So, enabled plugins that cannot collect data, do nothing.

For each data source that cannot be collected, you should have error lines in `/var/log/netdata/error.log`.

There can be many reasons for not collecting data:

1. system permissions (for example, a kernel with grsecurity prevents most of netdata system data collection)
2. kernel versions (kernels v2.6 expose a lot less information compared to 3.x and 4.x)
3. third party applications permissions (ie, to monitor postgres, your postgres must allow netdata to connect)

So, check `/var/log/netdata/error.log`. You can remove that file and restart netdata, so that you will have a clear log of the last session.

**Comment by ktsaou** [comment]
Cleaning up. If you need more help, just post here.
