### ISSUE TITLE
[FeatureRequest] Add installer/updater hooks

### ISSUE THREAD

**Issue by BrainDoctor** [firehol/netdata#2597]
It would be nice if it's possible to add custom commands/scripts when updating or installing netdata. Use cases:

* restart a specific service before/after installing/upgrading
* download or install additional packages/plugins/files before service start
* other?

maybe execute all scripts in a dir called `upgrader.d` or something. Or call specific files named after installation steps (pre/post-install/upgrade, or pre/post-service-start)

those scripts should be unaffected by updates/git pulls

**Comment by Knot3n** [comment]
uhm, why do you need to restart a service before netdata is updateing ?

**Comment by BrainDoctor** [comment]
I don't. Maybe others do?

But I would like to install a custom plugin that I develop by and for myself but don't want to maintain officially in the netdata repo.

I can still install it manually or with script if it isn't worth it, no problem. Something simple as a `wget` is already sufficient.

**Comment by ktsaou** [comment]
hm...

Options:

1. netdata will execute something when it starts - it will run as user `netdata`.
2. netdata-installer will execute something when it installs netdata - it will run as the user the installer runs - when? before install, after install but before netdata restart, or the last thing?
3. netdata-updater will execute something - it will run as the user the updater runs - when? before updating or after updating netdata?

Possible solutions (currently):

- You can create a `.plugin` BASH file in `/usr/libexec/netdata/plugins.d` that will run whatever you like and just print `DISABLE`. netdata will execute it once when it starts.

- Instead of using the netdata-updater.sh directly, create your script that does whatever you like to be done and calls the real netdata-updater script to update netdata.

- install your own `netdata.service` that executes whatever else you need to be executed. This is probably the best solution (this is what systemd is for afterall).

Of course, it is not much work to add something like that in netdata, but we need to figure out why is needed and why it is better that alternatives.

**Comment by BrainDoctor** [comment]
solution 2 seems to the easiest.
