### ISSUE TITLE
multi-os alarms at netdata master

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#2608]
The way alarms are handled for different O/Ses, it is impossible for a netdata master to process alarms for multiple operating system types (linux, freebsd, macos). Today a different set of alarms is installed, depending on the operating system.

Ideally, netdata should support an `os` match on alarms and allow the same alarm to be loaded multiple times, each for different conditions (families, os, etc). So, O/S should be a runtime decision.

CC: @simonnagl (we had discussed this in the past, and I had agreed with your suggestion - but unfortunately, it now limits netdata so we have to turn this around).

**Comment by simonnagl** [comment]
> for a netdata master to process alarms for multiple operating system types (linux, freebsd, macos)

I do not understand why a metadata master needs to cannot process alarms for multiple operation system types, without supporting an `os` match on alarms. I think I have read a post of you ( @ktsaou ) how you plan to implement a netdata master (flow of data, etc. ) but I cannot find it now.
I do not want to say with it you are wrong. I am pretty sure you are right, but I want to understand why. Maybe you can clarify why this is needed or just point me to related issues.

> Ideally, netdata should support an os match on alarms and allow the same alarm to be loaded multiple times.

This is nothing which bothers me. In the mentioned discussion of the past I complained adding such a thing mainly, because I do not think on a macOS machine a user wants to see linux specific alarms (which are never applied).
Only installing required alarms for an OS did not require an `os` match any more.

I do not think the decision of the past limits netdata now. I think maybe now is the time to add the `os` match. Installing not required alarm files on a standard netdata servers should not be needed anyways.

**Comment by ktsaou** [comment]
Well, I think the reason of this confusion comes from another decision of mine: alarm definitions are just one set for each netdata, independently of the number of hosts mirrored to it.

So, today netdata has a list of alarm definitions and another list of alarm template definitions. These lists are then checked against the charts of each host and the ones matching are applied to the charts.

When multiple netdata hosts are mirrored to a master netdata, the same alarm definitions are checked against the charts of each hosts and the matching ones are applied.

If netdata master is linux, if has alarm definitions for linux (only these are installed). If the mirrored hosts are linux, freebsd and macos, they all get the alarms of linux, which is wrong.

So, the only solution I can see, is to install all alarms for all operating systems and add an `os` match in them so that they will only be applied to hosts matching their os.

**Comment by simonnagl** [comment]
Ahh, sorry. Now I now what you mean with central netdata. I first. thought you mean your plans mentioned in #2466.

> So, the only solution I can see, is to install all alarms for all operating systems and add an os match in them so that they will only be applied to hosts matching their os.

I agree with you.

For alarms applied to multiple `os` I would put into the same file.

```
template: 10min_cpu_usage
      on: system.cpu
      os: linux
  lookup: average -10m unaligned of user,system,softirq,irq,guest
   units: %
   every: 1m
    warn: $this > (($status >= $WARNING)  ? (75) : (85))
    crit: $this > (($status == $CRITICAL) ? (85) : (95))
   delay: down 15m multiplier 1.5 max 1h
    info: average cpu utilization for the last 10 minutes (excluding iowait, nice and steal)
      to: sysadmin

template: 10min_cpu_usage
      on: system.cpu
      os: macOS
  lookup: average -10m unaligned of something,different,from,above
   units: %
   every: 1m
    warn: $this > (($status >= $WARNING)  ? (75) : (85))
    crit: $this > (($status == $CRITICAL) ? (85) : (95))
   delay: down 15m multiplier 1.5 max 1h
    info: average cpu utilization for the last 10 minutes (excluding iowait, nice and steal)
      to: sysadmin

template: 20min_steal_cpu
(...)
```

and not split it.

**Comment by ktsaou** [comment]
I also added a `hosts: *` match, allowing a central netdata to apply alarms only to hosts matching these patterns.

**Comment by ktsaou** [comment]
merged it.
