### ISSUE TITLE
Critical - out of cache space time

### ISSUE THREAD

**Issue by Nirjonadda** [firehol/netdata#2611]
Hello,

I am getting lot of netdata notification about critical - out of cache space time - memcached_local.cache, Please let me know that how to fixing on this issue? I am using CENTOS 7 with cPanel v66.

````
memcached_local.cache - Chart
--
out of cache space time = 1h, estimated time the cache will run out of space, if the system continues to add data with the rate of the last hour - Alarm
cache - Family
CRITICAL  -  Severity
Sun Aug 20 17:47:19 +06 2017   -  Time
````

**Comment by ktsaou** [comment]
Hi,

you are using memcached and it is about to be completely full, so you are going to loose data from the cache.

You have 2 options:

1. Ignore this alarm - you can disable it / remove it. The alarm you get mentions the file and line this alarm is defined. Just comment it out and restart netdata. It will not bother you again.

2. Use your memcached (or cpanel) documentation to settle this issue.

Keep in mind that since memcached is usually used for caching data, this alarm is not always as important. It depends on the data stored in the cache and the ability of the software to handle this data loss.

I am very sorry I can't help you more. Your action plan depends on your use case.

@LucaDev if you can help more, please do so...

**Comment by ktsaou** [comment]
Cleaning up. If you need more help, just post here.
