### ISSUE TITLE
Is netdata consuming too much resources than expected?

### ISSUE THREAD

**Issue by elfgoh** [firehol/netdata#2621]
<img width="1276" alt="screen shot 2017-08-23 at 7 31 45 pm" src="https://user-images.githubusercontent.com/491688/29614264-215c1150-883c-11e7-8669-5f4b16448065.png">

Netdata seems to be consuming more ram than reported. In the screenshot it consumes 70.8 MB on the graph but on the sidebar, it claims to only consume 21MB.

Unsure if the CPU is high. But right now it goes above 10% at times based on the graph.

**Comment by ktsaou** [comment]
ok, let me explain:

1. netdata is a multi-process application. The systemd chart you check counts everything, the entire process tree (including external plugins).

2. the memory shown in the lower right corner of the dashboard is only for the database of the specific host. If you are mirroring / streaming more databases their memory is not included. Also, the memory used by external plugins is not included. You can get a break down per netdata process at the next section: "Applications".

3. the CPU shown at the systemd charts includes all the processes too. The next section ("Applications") has a breakdown per netdata process too.

   Keep in mind that the CPU time reported is influenced by the clock of the processor. So, 10% reported when the processor is running at 50% its clock, is actually 5% cpu. You can see this clearly happening under heavy load. On many of my systems netdata gets 4-5% CPU while the system is idle, but when the system does something CPU intensive, netdata falls to 1-2%.

4. To my observations cgroups CPU accounting (the technology used for the systemd chart) is not very accurate on the little things (or it can be dependant on things I don't really understand).

   Check for example this server: http://build.my-netdata.io/
   It runs 20+ netdata in containers. Nothing else. 20+ lxc containers just running netdata. The total CPU time of the system is 5-10% for all them:

   ![image](https://user-images.githubusercontent.com/2662304/29615645-5e6aee88-8817-11e7-9ec8-3203026c9111.png)

   Now check the CPU consumed by a single container out of the 20:

   ![image](https://user-images.githubusercontent.com/2662304/29615612-45265e3a-8817-11e7-8e1f-d72cba49c8f9.png)

   Even between the 2 charts there are discrepancies. The CPU accounted per core, is more fine grained than the CPU reported for the whole container.

   Now check what systemd cgroups are reporting for the master netdata (the one running at the host):

   ![image](https://user-images.githubusercontent.com/2662304/29615925-585d03fe-8818-11e7-9330-aa0174f821f0.png)

   It reports that the whole CPU of the system is spent on this netdata! It cannot be happening. There are 20+ of them running on this system (in containers). Check also the "Applications" section. In this section `apps.plugin` running at the host, accounts to `netdata` all the netdata running on this system (it runs at the host, and it sees the whole process tree, even the ones running in containers). The 2 numbers are roughly equal. So, systemd at the host accounting just one netdata, reports about the same CPU utilization apps.plugin reports for 20 of them!

I have to admit though that your CPU is probably too high. Could you please post the same chart from the Applications section?

**Comment by elfgoh** [comment]
For context, prometheus has been integrated with netdata and is running on a Beaglebone black which has a 1Ghz ARM v7 CPU and 512 MB ram.

<img width="1121" alt="screen shot 2017-08-24 at 11 53 53 am" src="https://user-images.githubusercontent.com/491688/29648852-fb019192-88c2-11e7-8b21-438401a9ea60.png">
<img width="1101" alt="screen shot 2017-08-24 at 11 53 23 am" src="https://user-images.githubusercontent.com/491688/29648851-fafed51a-88c2-11e7-837c-6471164f60ae.png">

**Comment by elfgoh** [comment]
You didnt comment about the memory consumed. So is 70MB expected?

**Comment by ktsaou** [comment]
oh... its an IoT...

No it is not expected. I didn't comment on mem, because I was expecting to see python.d.plugin or node.d.plugin to consume a lot of memory. But they don't run in your case.

---

This is from an RPi 2 (quad core):

![image](https://user-images.githubusercontent.com/2662304/29656960-d12f84d6-88be-11e7-884f-f6cdfbc95853.png)

And as reported by cgroups (the whole netdata process tree):

![image](https://user-images.githubusercontent.com/2662304/29657037-0a8a07f6-88bf-11e7-947c-a684907de2a7.png)

---

And this from an RPi 1 (single core, it has `update_every = 2` to cut netdata CPU usage in half, everything else is at defaults):

![image](https://user-images.githubusercontent.com/2662304/29657315-dcbc3410-88bf-11e7-9d8d-d35068406a17.png)

---

I also see your apps.plugin is facing difficulties to keep up (it gives gaps on the charts).

hm... I would love to investigate these problems. Are you interested to help?

**Comment by LeeNX** [comment]
I am interested in doing some internet monitoring with netdata and Raspberry Pi, for nice real-time feedback. Suggestions on lite builds always welcome. I am thinking of basing my PoC off the OpenHAB Raspberry Pi setup - http://docs.openhab.org/installation/openhabian.html and/or http://docs.openhab.org/installation/rasppi.html  
  
Been thinking of using netdata and passing averages back to OpenHAB, but that might be overkill.

**Comment by ktsaou** [comment]
@LeeNX I use netdata on RPis all the time. I have given special attention for netdata to be IoT friendly.

For tips on configuring netdata for IoT check this: 
https://github.com/firehol/netdata/wiki/netdata-for-IoT

It is not an overkill to run netdata on IoT. If the device is too weak, it is overkill to collect thousands of metrics per second, so just lower that a bit and you will be fine (i.e. either collect all metrics less frequently or collect fewer metrics by disabling plugins you don't need).

RPi 2 and 3 are not that weak. I run netdata with the default settings on them. The only thing that can be overkill on them is `apps.plugin`. This plugin is more CPU demanding than netdata itself. But you can keep everything per second and configure apps.plugin to run with `update every = 2` (to cut its CPU usage in half).

**Comment by elfgoh** [comment]
@ktsaou Am interested to help. This is integrated with Prometheus, if it is of any relevance. It was installed with all plugins enabled. I switched out the "afflicted" card but am happy to boot in again

**Comment by elfgoh** [comment]
As an aside, on a different install, I can get much better performance by disabling all plugins except the ones I need:
- proc
- diskspace
- cgroups

**Comment by elfgoh** [comment]
Interesting I did a fresh install using `bash <(curl -Ss https://my-netdata.io/kickstart.sh)  --dont-wait` without `all` and `prometheus`, and netdata seems much lighter. Is this significant in anyway?

**Comment by ktsaou** [comment]
Does it monitor less metrics now?

prometheus can only stress netdata if it queries netdata too frequently. Otherwise it does not affect netdata.

What can affect netdata CPU and memory on IoT is the number of clients accessing the dashboard. So, if you plan to have a custom dashboard on a TV with per second updates, this will influence both CPU and memory on the weak device.

This is why I always suggest to evaluate the CPU consumption of netdata, only when there are no clients accessing (i.e. leave netdata running for a while without web clients and then check what was the CPU utilization during that time).

**Comment by elfgoh** [comment]
For clarity I have different microSD cards with slightly different installations of netdata, build at different times

> Interesting I did a fresh install using `bash <(curl -Ss https://my-netdata.io/kickstart.sh)  --dont-wait` without `all` and `prometheus`, and netdata seems much lighter. Is this significant in anyway?

This is just netdata out of the box just now on Debian. Systemd isnt enabled. Prometheus absent

First screenshot showing high resource consumption: netdata installed some time back with prometheus on Debian on a different microSD


> As an aside, on a different install, I can get much better performance by disabling all plugins except the ones I need:
> - proc
> - diskspace
> - cgroups

This is the same microSD that was shown in the first screenshot, but now modified to only have certain plugins enabled. Prometheus is still present

**Comment by ktsaou** [comment]
I suggest to disable netdata log files on IoT. Leave them open for debugging, but close them when you are done. If you have a central syslog server, netdata can push all logs to syslog too.

If the IoT devices are in a controlled environment, I suggest to go diskless. On my home for example, I have 6 RPIs (3 x RPi1 + 3 x RPi2). The SD card is used only to boot (it only has the /boot partition) and `/` is mounted via NFS.

The rest of the SD is used as swap, but with sysctl `vm.swappiness=1` so that is used only when absolutely necessary.

This way, you do not depend on the SD card. The first RPi I installed, runs like that for 4-5 years now.

For the NFS server I use a J1900 machine with 2x SSD in software RAID-1 (celeron quad core at 2GHz, 8GB RAM, it consumes just 10W of power, which saves a lot on electricity bills).

This makes RPis a lot faster and provides enough flexibility (all RPis offload many things to this server, dns, routing, mail, backup, etc).

Also, it is just a simple setting to boot any O/S you like on the RPis (just mount a different directory from the NFS server).

**Comment by elfgoh** [comment]
>` Leave them open for debugging, but close them when you are done.`

Sorry, didnt quite understand this portion

> I suggest to disable netdata log files on IoT

I understand what is stated for this. But unsure why

**Comment by elfgoh** [comment]
> If the IoT devices are in a controlled environment, I suggest to go diskless. On my home for example, I have 6 RPIs (3 x RPi1 + 3 x RPi2). The SD card is used only to boot (it only has the /boot partition) and / is mounted via NFS.

The beaglebone black has only 512 MB ram. And the device is deployed on a low bandwidth environment. I am unsure if using NFS will be suitable

**Comment by ktsaou** [comment]
cleaning up. If something is pending, just post here.
I hope netdata is good on your IoT...

**Comment by webrockey** [comment]
hello....plz can some one tell me.... what minimum server configuration required for install netdata on VPS

 i have
2 core
4GB RAM
KVM
is that ok for install netdata

thank you

**Comment by ilyam8** [comment]
@webrockey yes, it is ok (if it is not master/slave config and the server is master)
