### ISSUE TITLE
Pidfile missing & RAM usage

### ISSUE THREAD

**Issue by nanom1t** [firehol/netdata#2641]
Hi,

How can I get netdata pidfile in /var/run directory? I'm using Ubuntu 16.04 LTS and netdata 1.7.1.

I've tried to add different options in /etc/systemd/system/netdata.service, but it does not help.
```
ExecStart=/usr/sbin/netdata -D -pidfile /var/run/netdata.pid
ExecStart=/usr/sbin/netdata -D -P /var/run/netdata.pid
```
It would be awesome if I can specified pidfile param in /etc/netdata/netdata.conf.

Thanks

**Comment by nanom1t** [comment]
Also netdata takes more than 50 Mb of RAM with default configuration:
user@node3-vm:/usr/local/src$ sudo service netdata status
● netdata.service - Real time performance monitoring
   Loaded: loaded (/etc/systemd/system/netdata.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2017-08-28 10:09:16 BST; 55s ago
 Main PID: 31046 (netdata)
    Tasks: 18
   Memory: 82.5M
      CPU: 1.607s
   CGroup: /system.slice/netdata.service
           ├─31046 /usr/sbin/netdata -D -P /var/run/netdata.pid
           ├─31068 /usr/libexec/netdata/plugins.d/apps.plugin 1
           ├─31069 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
           └─31072 bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1

Aug 28 10:09:16 mobinode3-vm systemd[1]: Stopped Real time performance monitoring.
Aug 28 10:09:16 mobinode3-vm systemd[1]: Started Real time performance monitoring.

**Comment by ktsaou** [comment]
Hi,

## pidfile

On systemd netdata does not produce a pidfile. The reason is that systemd starts netdata as user `netdata`, so netdata cannot write to `/var/run`. You can edit `netdata.service` to start netdata as `root`, and change it to `forked`. netdata will still drop privileges and switch to user `netdata`, but in this case netdata will be able to produce its pidfile in `/var/run`. Alternatively you can instruct netdata to create a pidfile in `/tmp` or somewhere it has write access to.

Your netdata `error.log` should have logged the failure to write the pidfile.

## memory

Well... systemd is lying...

Check this:

```sh
# systemctl status netdata
● netdata.service - Real time performance monitoring
   Loaded: loaded (/etc/systemd/system/netdata.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-08-29 00:23:56 EEST; 8min ago
 Main PID: 1966 (netdata)
    Tasks: 25 (limit: 4915)
   Memory: 130.6M
      CPU: 41.541s
   CGroup: /system.slice/netdata.service
           ├─1966 /usr/sbin/netdata -D
           ├─1976 bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
           ├─1987 /usr/libexec/netdata/plugins.d/apps.plugin 1
           └─1993 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1

Aug 29 00:23:56 ktsaou-laptop systemd[1]: Started Real time performance monitoring.
```

but, cgroups reports this, for the whole process tree:

![screenshot from 2017-08-29 00-33-27](https://user-images.githubusercontent.com/2662304/29794684-b42ebf5a-8c51-11e7-941f-883835973016.png)

apps.plugin reports this, by tracking the individual processes (this reports a little higher than cgroups, because apps.plugin does not correlate shared memory - it counts this memory to each process):

![screenshot from 2017-08-29 00-34-40](https://user-images.githubusercontent.com/2662304/29794727-e8cb09bc-8c51-11e7-9e3e-2de5795aa81a.png)

and netdata database uses these:

![screenshot from 2017-08-29 00-37-43](https://user-images.githubusercontent.com/2662304/29794834-5c708f36-8c52-11e7-9e63-6f85f6315e44.png)

To be honest, systemd is not lying, but I guess it includes system caches related to the process. netdata does not need these caches, they are completely useless to it, but the system used these caches while starting netdata. Eventually, when the the system will need the additional memory, it will get these caches back.

**Comment by ktsaou** [comment]
btw, it seems that restarting netdata after some time, systemd manages to report the valid values:

```
# systemctl status netdata
● netdata.service - Real time performance monitoring
   Loaded: loaded (/etc/systemd/system/netdata.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-08-29 00:48:44 EEST; 3min 42s ago
 Main PID: 9973 (netdata)
    Tasks: 26 (limit: 4915)
   Memory: 59.3M
      CPU: 21.979s
   CGroup: /system.slice/netdata.service
           ├─9973 /usr/sbin/netdata -D
           ├─9980 bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
           ├─9990 /usr/libexec/netdata/plugins.d/apps.plugin 1
           └─9996 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1

Aug 29 00:48:44 ktsaou-laptop systemd[1]: Started Real time performance monitoring.
```

I guess this is because the caches are not accounted to netdata now. The caches were already there...

**Comment by nanom1t** [comment]
Thanks for your response. It seems that systemd reports approximately correct values, but it does calculation of sum for all running processes in CGgroup. For example:
```
  Memory: 58.6M
      CPU: 39.984s
   CGroup: /system.slice/netdata.service
           ├─2941 /usr/sbin/netdata -D -P /var/run/netdata.pid
           ├─3333 bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
           ├─3342 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin
           └─3343 /usr/libexec/netdata/plugins.d/apps.plugin 1
```
![screen shot 2017-08-29 at 9 23 23 am](https://user-images.githubusercontent.com/6481192/29807252-ccaff068-8c9b-11e7-9749-a67fdb8ee543.png)
If we calculate the sum of used RAM by /usr/sbin/netdata, tc-qos-helper.sh, python.d.plugin and apps.plugin we will get around 53 Mb of RAM. Maybe I'm wrong, but it looks like true.

Netdata is a great monitoring tool. I have only 1024 Mb of RAM on my server, so I'm trying to count each hundred of megabytes.

Thanks

**Comment by ktsaou** [comment]
> If we calculate the sum of used RAM by /usr/sbin/netdata, tc-qos-helper.sh, python.d.plugin and apps.plugin we will get around 53 Mb of RAM. Maybe I'm wrong, but it looks like true.

systemd shows the whole process tree + caches
If you enable the systemd charts at netdata, you will get the same values reported by systemd, but netdata removes the caches from the charts.

> Netdata is a great monitoring tool. I have only 1024 Mb of RAM on my server

- Disable netdata plugins you don't need
- Lower data collection frequency and half the netdata history. For example `update every = 2` and `history = 1800` will still give you 1 hour of data, but both CPU and memory consumed by netdata will be half
- Enable KSM. This will give you 50% savings on the database.

**Comment by nanom1t** [comment]
I've tried `history = 1800`, `update every = 2` and it works better (netdata uses 28 Mb of RAM, python.d.plugin uses around 40 Mb of RAM). 
![screen shot 2017-08-29 at 12 43 15 pm](https://user-images.githubusercontent.com/6481192/29814962-c4e382ca-8cb7-11e7-9889-b19e4ace83e8.png)
> Disable netdata plugins you don't need
I'm just using all default plugins + nginx.conf, redis.conf, mysql.conf and phpfpm.conf from `/etc/netdata/python.d` directory.
May I just remove unused plugins (like, postgres.conf, varnish.conf, apache.conf, etc) from `/etc/netdata/python.d` directory? How can I disabled unused plugins properly?

Thanks

**Comment by ktsaou** [comment]
You can disable python plugins by editing /etc/netdata/python.d.conf

Are you sure python.d.plugin doubled its RAM after the frequency of netdata was increased to 2? Could you please revert it back to check?

**Comment by nanom1t** [comment]
Yes, sure.
```
	history = 3600
	update every = 1
```
![screen shot 2017-08-29 at 1 06 12 pm](https://user-images.githubusercontent.com/6481192/29815903-ef1710e0-8cba-11e7-8d4c-607a11bb282a.png)
The python.d.plugin RAM is the same as it was previously.

**Comment by ktsaou** [comment]
ok, so this does not seem to be influenced by `update every`. Right?

it would be nice if you could disable the python plugins you don't need to see if this memory will be lowered. netdata starts them all on start, so some increased memory may be need due to this fact.

**Comment by nanom1t** [comment]
Yes. It looks like python.d itself eats 40 Mb of RAM. I've disabled all plugins in `/etc/netdata/python.d.conf` except few ones:
```
enabled: yes
logs_per_interval: 200
log_interval: 3600
default_run: no

cpufreq: yes
cpuidle: yes
fail2ban: yes
postfix: yes
nginx: yes
phpfpm: yes
redis: yes
mysql: yes
```
```
history = 1800
update every = 2
```
![screen shot 2017-08-29 at 2 51 56 pm](https://user-images.githubusercontent.com/6481192/29819538-c904f9da-8cc9-11e7-966b-352dbd0d2f12.png)
Thank you a lot.

**Comment by ktsaou** [comment]
ok. This is strange since on my setup it does not need that much mem.

Could you please try to find the offending one by disabling them one by one? Wild guess: I think it is probably `mysql` (since this depends on a quite complex third party library that could require a lot of memory - have you used mymysql or py-mysqldb?).

**Comment by nanom1t** [comment]
I see the same picture with python.d on my another Linode server. 
![screen shot 2017-08-30 at 9 17 34 am](https://user-images.githubusercontent.com/6481192/29857995-2905ddc8-8d64-11e7-8df2-93314bf5a2ab.png)
I'm not using mymysql or py-mysqldb on my server directly, but I've installed python-yaml and python-mysqldb apt packages on my Ubuntu 16.04 LTS during Netdata installation.

> Could you please try to find the offending one by disabling them one by one?

I've tried to disable pythod.d plugins one by one and I've got next results. If I disable all plugins in `/etc/netdata/python.d.conf` except `cpufreq: yes` and `cpuidle: yes` than everything goes good. Python.d eats around 1-2 Mb of RAM. However, when I enable **only one** of these plugins:
```
fail2ban: yes
postfix: yes
nginx: yes
phpfpm: yes
redis: yes
mysql: yes
```
then python.d continue to eat around 40 Mb of RAM.

Thanks

**Comment by ktsaou** [comment]
hm... I think there is something else wrong here.

On http://london.my-netdata.io/#menu_apps_submenu_mem (debian 8) with `mysql`, `postgres`, `nginx` and `web_log`, python needs 6MB.

On http://build.my-netdata.io/#menu_apps_submenu_mem (ubuntu 16.10) with `squid`, `nginx`, `web_log`, python needs 44MB.

On my laptop (fedora 26), with just `postfix` and `sensors`, it needs 17MB.

On an ubuntu 14.04 I have, with `squid`, `sensors`, `web_log`, it needs 13MB.

On an Arch Linux I have, with `squid`, `web_log`, `sensors`, `postfix`, `mdstat` it needs 14MB.

On a gentoo box, with `squid`, `web_log`, `sensors`, `postfix`, `mdstat`, `apache`, `dovecot`, `dhcpd`, `mysql`, it needs 59MB.

For sure these are not consistent, but it seems system related. The same code under different distros needs different amount of ram.

I don't know how to trace the root cause of this.
@l2isbad any ideas?

**Comment by Ferroin** [comment]
As a couple of extra data points:

On a Gentoo VM with just `nginx` enabled, it's using 3MB
On a different Gentoo box with `cpufreq`, `cpuidle`, and `sensors`, it's using 13MB

**Comment by ktsaou** [comment]
I found an ubuntu 16.10 container that has this issue.

I started python.d.plugin with just cpufreq enabled and python 2.7.12+ takes 49MB.
Stopped it and started it with python 3.5.2+ and it takes 19.5MB.

hm...

**Comment by nanom1t** [comment]
There is Python 2.7.12 installed on my Ubuntu 16.04 LTS servers. Does it make a sense to update it to 3.5+ version?

**Comment by ktsaou** [comment]
> There is Python 2.7.12 installed on my Ubuntu 16.04 LTS servers. Does it make a sense to update it to 3.5+ version?

You could try it. netdata supports both versions, so you should check the other applications you may have.

**Comment by Ferroin** [comment]
On Ubuntu 16.04, you can definitely install Python 3, but you probably can't get id of 2.7 without breaking your system (because some of the core system functionality depends on Python, and I don't think 16.04 works with Python 3.x).  That said, all major distros support at minimum installing a 2.x and 3.x version at the same time (and most support having multiple 3.x versions installed simultaneously too).

**Comment by ktsaou** [comment]
Cleaning up. If you need more help, just post here.
