### ISSUE TITLE
Metrics getting lost under 100% CPU load (HPC environment)?

### ISSUE THREAD

**Issue by mikerenfro** [firehol/netdata#2652]
I'm running netdata in an HPC environment, where compute nodes may be (ideally, *should be*) at 100% CPU load for extended periods of time.

I get gaps in my netdata metrics under heavy load, as seen below.

![screen shot 2017-08-29 at 1 54 25 pm](https://user-images.githubusercontent.com/1451881/29838784-c432e5e6-8cc1-11e7-8747-0566aaa641ec.png)

This should be an out of the box install of netdata. Single 250 GB 7200 rpm SAS 6Gbps drive in each compute node.

**Comment by ktsaou** [comment]
netdata runs with the idle process scheduler, which of course results to this.

The following `netdata.conf` settings control this:

```
[global]
    process scheduling policy = idle
    process scheduling priority = 0
    process nice level = 19
```

The policies supported by netdata are `idle` (the netdata default), `other` (also as `nice`), `batch`, `rr`, `fifo`. netdata also recognizes `keep` and `none` to keep the current settings without changing them.

For `other`, `nice` and `batch`, the setting `process nice level = 19` is activated to configure the nice level of netdata. Nice gets values -20 (highest) to 19 (lowest).

For `rr` and `fifo`, the setting `process scheduling priority = 0` is activated to configure the priority of the relative scheduling policy. Priority gets values 1 (lowest) to 99 (highest).

For the details of each scheduler, see `man sched_setscheduler` and `man sched`.

When netdata is running under systemd, it can only lower its priority (the default is `other` with `nice level = 0`). If you want to make netdata to get more CPU than that, you will need to set in `netdata.conf`:

```
[global]
    process scheduling policy = keep
```

and edit `/etc/systemd/system/netdata.service` and add:

```
CPUSchedulingPolicy=other | batch | idle | fifo | rr
CPUSchedulingPriority=99
Nice=-10
```

**Comment by ktsaou** [comment]
Add the above to the wiki: https://github.com/firehol/netdata/wiki/Configuration#netdata-process-priority

**Comment by Ferroin** [comment]
In general, you will see this behavior regardless unless you use one of the realtime scheduling policies (`rr` and `fifo`), even if you give netdata a nice value of -19 and the computational app a nice value of 20, because the Linux scheduler is explicitly designed to prevent a low priority process from not getting any CPU time because of a higher priority process.  You probably also should not be using one of the realtime scheduling policies, as I doubt netdata has been properly tested to run under those (it's not an issue of 'will it run', it's an issue of 'will it accidentally monopolize CPU time').

As an alternative to both, you could dedicate a processor core for everything but your computational application using cpusets (or more likely, control groups), which has a number of other benefits in addition to probably fixing this (namely that you can do things like backups or system management without impacting the computations).

**Comment by ktsaou** [comment]
> as I doubt netdata has been properly tested to run under those (it's not an issue of 'will it run', it's an issue of 'will it accidentally monopolize CPU time').

Well, I haven't tested for sure, but netdata on Linux is heavily I/O bound, even for data collection (it reads files from `/proc`).

@mikerenfro if you can test this on a non-critical machine with such load, it would be very nice to know how netdata behaves.

**Comment by mikerenfro** [comment]
I'm ok with the gaps existing, just would like to minimize them. I'll switch to the `nice` scheduler and load up a machine to see what happens. Ganglia running on the same boxes with the default nice values ends up taking under 1% of a single core, so I don't think I'll impact my users' jobs in any meaningful sense with netdata under the same policy.

**Comment by ktsaou** [comment]
I see systemd has a few settings for controlling the CPU resources allocated to processes. They may be handy if you decide to give a realtime priority to netdata: https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html

**Comment by ktsaou** [comment]
How did it go? How do you run netdata finally?
