### ISSUE TITLE
Path disclosure during security scans

### ISSUE THREAD

**Issue by cheribral** [firehol/netdata#2658]
This is a bit of an eye-roller, but if you go to http://host:port/some-rubbish, netdata says that it couldn't find anything at a path on the server's file system.  This path disclosure shows up as a red flag in internal security scans.  I realise that this is pretty benign, but thought I would mention it since a fix could prevent netdata from being flagged as a security problem by typical security scanners.

We've fixed it for ourselves by replacing the path with a humourous message, but perhaps this error message should not be shown at all by default?

**Comment by ktsaou** [comment]
You are right and it was like that (without the path) initially,

But, there were dozens of support requests from people seeking for help. Once I added that path there, the issues are gone (people can find out).

Since netdata does not allow `../` in URLs and checks the ownership of the files that serves, exposing the real path I think is harmless.

Of course, if you someone can show a case that this information can be abused somehow, we will have to remove it.

**Comment by cheribral** [comment]
Yep, that sound pretty harmless to me too.  Like I said, this was more simply for information, but if you know about it already, then there is no need!  :)

I'm happy to close this.
