### ISSUE TITLE
inaccurate disk inode usage for cephfs since cephfs does not set max inodes

### ISSUE THREAD

**Issue by nightwend** [firehol/netdata#2664]
> df -i
> Filesystem                 Inodes  IUsed     IFree IUse% Mounted on
> 192.168.20.7:6789:/          5079      -         -     - /mnt/cephfs
>

Inodes avail is showed as -1 in netdata.

Alarms:
> disk_inodes._mnt_cephfsChart
> --
> disk inode usage = 100%current disk inode usageAlarm
> /mnt/cephfs
>

**Comment by ktsaou** [comment]
Could you please post a screenshot of the chart?
What do you suggest should be done in this case:

1. disable the chart - this will automatically disable the alarm too. We should do this, only if the chart does not provide any useful info. We could also disable a specific dimension of the chart.

2. disable only the alarm

**Comment by Ferroin** [comment]
I think this is an issue with how CephFS reports inode usage.  As far as I can tell, there is no _actual_ artificial limit on how many inodes you can allocate on a given cluster because they are allocated dynamically, but they thought there was a need to provide data in the inode used field (instead of doing the correct thing for a filesystem that dynamically allocates inodes and returning nothing there).  It might be worth opening a bug upstream with CephFS to at least clarify this.

**Comment by ktsaou** [comment]
@nightwend please help me fix this issue. Save this little program as `statvfs.c`:

```c
   #include <stdio.h>
   #include <sys/statvfs.h>
   
   int main(int argc, char **argv) {
   const char *mount_point = "/mnt/cephfs", *disk = "undefined";
   
   struct statvfs buff_statvfs;
   if (statvfs(mount_point, &buff_statvfs) < 0) {
       fprintf(stderr, "Failed statvfs() for '%s' (disk '%s')", mount_point, disk);
       return 1;
   }
   
   printf("'%s': STATVFS: "
       "f_frsize=%llu "
       "f_bsize=%llu "
       "f_bavail=%llu "
       "f_blocks=%llu "
       "f_bfree=%llu "
       "\n"
       , mount_point
       , (unsigned long long)buff_statvfs.f_frsize
       , (unsigned long long)buff_statvfs.f_bsize
       , (unsigned long long)buff_statvfs.f_bavail
       , (unsigned long long)buff_statvfs.f_blocks
       , (unsigned long long)buff_statvfs.f_bfree
       );
   
   // taken from get_fs_usage() found in coreutils
   unsigned long bsize = (buff_statvfs.f_frsize) ? buff_statvfs.f_frsize : buff_statvfs.f_bsize;
   
   fsblkcnt_t bavail         = buff_statvfs.f_bavail;
   fsblkcnt_t btotal         = buff_statvfs.f_blocks;
   fsblkcnt_t bavail_root    = buff_statvfs.f_bfree;
   fsblkcnt_t breserved_root = bavail_root - bavail;
   fsblkcnt_t bused;
   if(btotal >= bavail_root)
       bused = btotal - bavail_root;
   else
       bused = bavail_root - btotal;
   
   printf("'%s': BYTES  avail=%llu, used=%llu, reserved_for_root=%llu\n", mount_point, (unsigned long long)bavail, (unsigned long long)bused, (unsigned long long)breserved_root);
   
   return 0;
   }
```

compile it with `gcc -o statvfs statvfs.c` and run it.

Here is mine:

```sh
# gcc -o statvfs statvfs.c 
# ./statvfs 
'/': STATVFS: f_frsize=4096 f_bsize=4096 f_bavail=2927046 f_blocks=12868728 f_bfree=3586502 
'/': BYTES  avail=2927046, used=9282226, reserved_for_root=659456
```

Could you please post the output here?

**Comment by nightwend** [comment]
Sorry for not replying sooner:  
> '/mnt/cephfs': STATVFS: f_frsize=4194304 f_bsize=4194304 f_bavail=8879 f_blocks=58650 f_bfree=8879 
> '/mnt/cephfs': BYTES  avail=8879, used=49771, reserved_for_root=0
> 

In case you want to test it your self, install docker and run following as root to build a demo cephfs env:  
```
mkdir /etc/ceph /var/lib/ceph
chcon -Rt svirt_sandbox_file_t /etc/ceph
chcon -Rt svirt_sandbox_file_t /var/lib/ceph

docker run -d  --name "ceph_demo" --net=host -v /etc/ceph:/etc/ceph -e MON_IP=$ip -e CEPH_PUBLIC_NETWORK=$network ceph/demo
docker ps
mkdir /mnt/cephfs
mount -t ceph $ip:6789:/ /mnt/cephfs  -o name=admin,secret=$(cat /etc/ceph/ceph.client.admin.keyring|grep key|cut -f 3 -d\ )
```

**Comment by ktsaou** [comment]
merged the fix.

**Comment by hoopty** [comment]
I can't tell if #2786 applies to ZFS as well.  If not, can I request a follow-up to also not to report inodes on ZFS filesystems.  Thanks!

**Comment by ktsaou** [comment]
@hoopty under Linux it will apply to all filesystems that report total inodes as `-1`.
Can you post a screenshot of your inodes chart?

**Comment by hoopty** [comment]
@ktsaou, I have attached a screenshot. Unfortunately, it's not that simple as ZFS does report inodes (they are allocated on demand), but it would never run out.  If there is a configuration setting I can apply to exclude inode collection & reporting for zfs filesystems, that would work.  We may even want to make that option enabled by default on FreeBSD.

<img width="1079" alt="screen shot 2017-09-27 at 4 38 40 pm" src="https://user-images.githubusercontent.com/552149/30939248-6b08991e-a3a2-11e7-8b3d-82f41aae12e4.png">

**Comment by ktsaou** [comment]
There are several options available at netdata.conf under section `plugin:freebsd:getmntinfo`.

However, I see it reports inodes. Why do you want to disable the chart? I mean, the fact that zfs auto-scales its inodes, does not imply that the charts are wrong. So, what is the problem you have with them?

**Comment by hoopty** [comment]
OK, that's fine - I'll see how to exclude them in ```plugin:freebsd:getmntinfo```

**Comment by Ferroin** [comment]
There are a number of filesystems these days that dynamically allocate inodes (in fact, UFS and ext* are the only widely used ones I know of that don't do dynamic allocation), maybe it would make some sense to just have  way to determine this, and not show the max value for filesystems that do dynamic allocation (and of course disable any alarms for that too).

**Comment by ktsaou** [comment]
> it would make some sense to just have way to determine this

If they report available inodes as `-1` it will be disabled automatically (netdata already does this).
I don't know if there is any other heuristic, apart from blacklisting filesystems by name...

**Comment by Ferroin** [comment]
I would think that whitelisting by name might be a better option.  As I said, I'm pretty sure that only ext*, UFS, and whatever MINIX calls their filesystem (and possibly XFS and GFS2) are the only ones in any wide usage today that don't dynamically allocate inodes.  Even FAT32 does dynamic allocation of directory entries.  Put slightly differently, there are a handful of filesystems that are known to use fixed inode allocations, and I think it's less likely to cause issues going forwards if netdata assumes that a filesystem does dynamic allocation unless it's told otherwise than the other way around (you can safely assume any new filesystems are going to use dynamic allocation of inodes, there is no longer any significant advantage to static allocation on modern hardware).

At a minimum, it would be nice to have a way to tell netdata to not report the max inodes value (and thus also disable the inode usage alarm inherently) on a per-filesystem basis.

**Comment by ktsaou** [comment]
ok, I will add a new setting:

```
[plugin:proc:diskspace]
    enable inodes reporting on filesystems = *
```

This can have both positive and negative matches.

Could you please provide a sane default?

**Comment by roker** [comment]
With zfs you can imagine a filesystem as a directory and is also exactly that simple to create or destroy it (zfs create, zfs destroy). They occupy space on pool and actually share it. I have just stubled on this thread as i am throwing things into config file but without any success. 

I think that the proper way to code this would be to allow something like:
`
[disk_space./jails/*]
        enabled = no
[disk_inodes./jails/*]
        enabled = no
`
I have tryed to disable it this way but the '*' is not working and creating those blocks for each filesystem that is mounted is not practical, i have like 30 of them.

**Comment by ktsaou** [comment]
I understand it is somewhat complex.
netdata configs are actually hierarchical.

For disk space monitoring:

## enable / disable the plugin

```
[plugins]
	diskspace = yes
```

## main diskspace plugin configuration

```
[plugin:proc:diskspace]
	update every = 1
	remove charts of unmounted disks = no
	check for new mount points every = 15
	exclude space metrics on paths = /proc/* /sys/* /var/run/user/* /run/user/* /snap/* /var/lib/docker/*
	exclude space metrics on filesystems = 
	space usage for all disks = auto
	inodes usage for all disks = auto
```

These 2 are exclusion patterns:

```
	exclude space metrics on paths = /proc/* /sys/* /var/run/user/* /run/user/* /snap/* /var/lib/docker/*
	exclude space metrics on filesystems = 
```

and these 2 allow you to select different strategies. They are the default settings for each disk (default means you can still control it per disk, below).

```
	space usage for all disks = auto
	inodes usage for all disks = auto
```

- `auto` means: **by default add disk space metrics if the collected values are not zero**
- `yes` means: **by default add disk space metrics if you can collect values**
- `no` means: **by default do not add disk space metrics**

## for each disk

Based on the above, netdata adds for each disk this:

```
[plugin:proc:diskspace:/]
	space usage = auto
	inodes usage = auto
```

Both of these get the default value of whatever you configured at the previous section `... for all disks`.

So, you can follow either of these strategies:

1. enable all by default, and disable specific disks
2. disable all by default, and enable specific disks

---

This issue is about adding another setting:

```
[plugin:proc:diskspace]
    enable inodes reporting on filesystems = *
```

**Comment by rcsheets** [comment]
Still seeing this issue using ceph-fuse, which reports zero free inodes. Is this to be considered a ceph bug because it should report -1 rather than 0, or is there a possibility of having this issue fixed in netdata?
