### ISSUE TITLE
Heatmap for apache and nginx

### ISSUE THREAD

**Issue by tl87** [firehol/netdata#2719]
I've been thinking that it would be nice to have a simple heatmap for apache and nginx, that shows a map of the world and the visitors, by looking at the IP's in the access.log for apache and nginx.

Something like:
![image](https://user-images.githubusercontent.com/5989314/30278615-269cc802-970b-11e7-8423-07d4a655f79c.png)

**Comment by Ferroin** [comment]
Personally, I think this is probably out of scope for netdata.  This is something I'd expect from a full featured log analyzer, but the web_log plugin seems to be more about performance metrics than demographic information.

@ktsaou can correct me if I'm wrong.

**Comment by tl87** [comment]
It would still be nice to have an all-in-one solution to work with :-)

.. and it is just a simple feature request :-)

**Comment by Komic** [comment]
On one hand it would pretty cool to implement some sort of geographical representation for fail2ban or apache logs, on the other hand a heatmap is probably indeed out of netdata's scope. Maybe a simple pie chart?

**Comment by ktsaou** [comment]
Hi,

this is a nice request. But I think it is too far in our future.

My current focus is to significantly improve the backends of netdata (plugins, database management, health monitoring, etc). Of course there is a whole world of improvements on the frontends too and I'd love to work on them.

I close this, only because open issues management consumes my time (eg. today I have spend my entire day revisiting and organizing issues).

During the next year we will be able to significantly improve and enhance netdata visualization and I am sure we will revisit all ideas like this one.

Thanks!
