### ISSUE TITLE
InfluxDB (opentsdb) backend not receiving data.

### ISSUE THREAD

**Issue by SarangBalbix** [firehol/netdata#2733]
Hello,

My netdata install was working correctly and I was able to see all data being sent to InfluxDB backend. Since about couple of months, I'm not receiving the aggregated data for system.ipv4.InOctets, system.ipv4.OutOctets. This data appears correctly on local netdata :19999 port, it is only when we are sending the data out.

Some debugging ( could be wrong here ) leads to backends_main() [ backends.c: 706 ] -> format_dimension_stored_opentsdb_telnet() [ backends.c: 297 ]  -> backend_calculate_value_from_stored_data() [ backends.c: 126 ] where NAN is returned, I believe this why the data is not sent. Debugging why it is so, we get called with before (1505342076) > after (1505342066) which is why it looks that data is not being sent.

Could you please let us know if this is correct, and how could we fix it?

**Comment by ktsaou** [comment]
Hi,

about 2 months ago we made a change in netdata #2430. There were cases that the metrics sent to backends were sent with low-level internal names, instead of the user friendly ones appearing on the dashboard.

We added a settings to control which of the 2 will be sent (ids or names) but we have set the default to `names`, unfortunately penalizing old users vs new users.

So, `system.ipv4.OutOctets` should now be `system.ipv4.sent`.

You can switch netdata back to sending the internal IDs, by setting in `netdata.conf`:

```
[backend]
	send names instead of ids = no
```

btw, you can verify netdata sends everything as it should, using the `prometheus` interface. Just fetch:

```
http://your.netdata.ip:19999/api/v1/allmetrics?format=prometheus?help=yes
```

and search for the **chart** you are interested. This interface uses the same functions backends use, so if something is not shown on this, it is not sent to backends either, and vice versa.

**Comment by ktsaou** [comment]
did you solve it?

**Comment by SarangBalbix** [comment]
Yes, thank you, I changed it to 'sent' and received. Thanks again for timely help!
