### ISSUE TITLE
Monitor docker host's network from within container without --net=host

### ISSUE THREAD

**Issue by byrnedo** [firehol/netdata#274]
Thanks for the great tool firstly!

I'm running netdata from within docker (https://github.com/titpetric/netdata) but can't set the container network to `host` due to my setup. Is it possible that netdata could monitor the host's network even though?

**Comment by ktsaou** [comment]
I think @titpetric has a solution for this.

**Comment by byrnedo** [comment]
Sorry, I hadn't seen he'd updated this issue: https://github.com/titpetric/netdata/issues/5
That looks like it's not possible then.

**Comment by titpetric** [comment]
Yes, unfortunately it's not possible due to limitations of how linux namespacing works. The more I find out about it, the more I see how ill suited netdata is for running inside a container.

Officially (however unofficial my opinion is), I'm recommending to use the docker image just for evaluation, before setting up netdata outside of containers. Due to isolation features you're much better off running netdata on dedicated instances. That being said, running netdata in docker is not entirely useless, but you're missing out on some killer features which are very difficult to expose to the container (like `mysql`, and other plugins which don't rely on proc/sys filesystems).

**Comment by byrnedo** [comment]
I think I'll switch over then, just was very convenient to just add it into my docker swarm without having to touch the hosts.

**Comment by titpetric** [comment]
There's still some work to be done, for it truly being useful in monitoring a Docker fleet, as the same isolation principles apply... :)

**Comment by ktsaou** [comment]
Cleaning up. I am closing this. If we need it open, please post.
