### ISSUE TITLE
Alarm notification url without netdata registry

### ISSUE THREAD

**Issue by funkyremi** [firehol/netdata#2763]
Hi,
I want to configure my netdata alarm notification to redirect to `myserver.com:1234` and not `https://registry.my-netdata.io/goto-host-from-alarm.html?host=myserver.com...`
I tried to manually change the hostname value and the registry url without success. How can I do this?
Thanks

**Comment by ktsaou** [comment]
Hi, any netdata can be a registry. So, configure your netdata to be a registry too.
Check this: https://github.com/firehol/netdata/wiki/mynetdata-menu-item#every-netdata-can-be-a-registry

**Comment by funkyremi** [comment]
Thanks but I tried every options in the documentation without success. The alert link keeps redirecting to registry.my-netdata.io even after restarting computer.
Is there anything else I can try to redirect to the good url?
[registry]
    enabled = yes
    registry to announce = http://myurl:19999

**Comment by ktsaou** [comment]
At the registry netdata:

```
[registry]
   enabled = yes
   registry to announce = http://myurl:19999
```

At all your **other** netdata:

```
[registry]
   enabled = no
   registry to announce = http://myurl:19999
```

If it still does not work, please post the registry section of both your registry and another netdata, by fetching `http://your.netdata.ip:19999/netdata.conf`.

**Comment by funkyremi** [comment]
It still doesn't work. I've got an Nginx in front of netdata for password protection.
Here's the only changes I've done in my netdata.conf
```
[web]
        bind to = localhost:19999
[registry]
   enabled = yes
   registry to announce = http://myurl:1234
```
Maybe I'm not doing the right thing, I just want that alert link to point to myurl:1234 (url with password protection) and a different link for each server like server2.myurl:1234.

**Comment by ktsaou** [comment]
Whatever you put as `registry to announce = http://myurl:1234` has to be accessible directly.

So, if you fetch `http://myurl:1234` with your browser, you should get the dashboard of the netdata that has `[registry].enabled = yes`.

To debug the issue, you can press F12 on your browser and switch to the console tab. You will see the errors there.

**Comment by funkyremi** [comment]
If I understand, there's no way to protect my netdata dashboard with nginx/password and use the netdata as registry as it is not accessible directly?
When I fetch myurl:1234 I access the netdata dashboard but I have to enter my credentials first.
Is there any workaround to change manually the alert link? I tried many options by following the doc but the link is every time https://registry.my-netdata.io/go...

**Comment by ktsaou** [comment]
@funkyremi you want to password protect your netdata.

Since netdata is a distributed application, to effectively password protect it, you have to proxy all your netdata through the same web server, with URLs like:

- http://web.server.ip/netdata1/
- http://web.server.ip/netdata2/
- http://web.server.ip/netdata3/

That way, when you access any netdata, you will have to be authenticated at the web server. Once you are authenticated, the registry request will go through.

If you use a different web server to proxy each of your netdata, then when you will be authenticated for netdata1 when you access netdata1, but you will not be authenticated for registry if the registry is not netdata1, the registry requests will fail.
