### ISSUE TITLE
Netdata with ephemeral monitoring behind Nginx

### ISSUE THREAD

**Issue by edwade3** [firehol/netdata#2828]
I might be missing something blindingly obvious here, but I setup netdata on a Cloud VM and served it using Nginx as a proxy (so no access via 19999) secured using HTTP Basic auth.

What I want is to be able to monitor IoT devices (RPi's) with them streaming their data (rather than serving it as they'll be on 4G sim card with dynamic IP's and therefore, no inbound access).

I tried setting the destination on the "slaves" as the domain of the netdata install, but this didn't work - I've currently opened port 19999 and the system is working, however, if possible I'd like to close this port (as it means people can view my dashboard bypassing the auth).

EDIT: All of my "slaves" will be using the same API Key if that changes anything!

Any help, greatly appreciated!

**Comment by ktsaou** [comment]
Nice request.

I had to re-organize the access lists a bit to all this to happen.

So, for your setup your will need in `netdata.conf`:

```
[web]
	allow connections from = *
	allow dashboard from = YOUR.NGINX.IP
	allow streaming from = *
```

This is what these do:

1. `allow connections from` controls who can connect to the netdata port. We allow everyone to connect, since we need your slaves to be allowed to connect.

2. `allow dashboard from` controls who can fetch the dashboard. We allow only your nginx IP.

3. `allow streaming from` controls who can push metrics. We allow everyone, since this will use the API keys to validate the requests.

The acl `allow dashboard from` was missing. I added it with PR #2838 
I need to test this a bit.
If you want to test it (please do), on the master netdata, `git clone https://github.com/ktsaou/netdata.git` and the run `./netdata-installer.sh` from it.

**Comment by ktsaou** [comment]
btw, if your nginx is at localhost, use `localhost` for `YOUR.NGINX.IP`.

**Comment by ktsaou** [comment]
I have tested and it works.
Merged it, so just install the latest netdata.

**Comment by edwade3** [comment]
Amazing work! Super speedy response!! I'll be updating this tomorrow! Thank you soooo much!
