### ISSUE TITLE
[question] disk utilization explanation?

### ISSUE THREAD

**Issue by p1hr** [firehol/netdata#288]
Hi,
can someone please provide me with an explanation of disk utilization time (disk_util) on the dashboard and how it is calculated?
Graphs on one of my servers go up to 100% 90% of the time even though the server is equipped in high performance FusionIO card so I want to understand the logic behind it

Thanks

**Comment by ktsaou** [comment]
It is **the time the disk was busy vs the total time**.

So, the system sends commands to the disk and waits for responses. `disk_util` is the time percentage the disk spent being busy with something. This is irrelevant of its data throughput. This metric does not care what the disk did. Only that it was doing something.

The system is also able to merge operations, when these can be merged. So, even if util is 100% the disk may have some throughput more to give. But generally, when `disk_util` is 100%, the disk is 100% busy doing something.

**Comment by ktsaou** [comment]
And of course, if it is a magnetic disk, disk utilization is high and the throughput is low, then it seeking too much.

**Comment by ktsaou** [comment]
Keep in mind your fusion card may be able to execute parallel requests to the disk. So this setting says nothing. Your disk may be 100% of the time busy, but it might be perfectly capable of executing a lot more requests in parallel.

For magnetic disks, things are different.

**Comment by ktsaou** [comment]
Can we close this?
Thanks!

**Comment by fayak** [comment]
Hi @ktsaou !
Sorry for digging up a buried question, but does it mean that if my disk utilization is indicating 100%, even if the throughput is way under its maximum, I am limited by I/O  ?

Thanks !

**Comment by mfundul** [comment]
> 
> 
> Hi @ktsaou !
> Sorry for digging up a buried question, but does it mean that if my disk utilization is indicating 100%, even if the throughput is way under its maximum, I am limited by I/O ?
> 
> Thanks !

Not necessarily.

I/O is complicated, device performance may hit limits of:
- latency
- sequential/random throughput (bytes/second)
  - separately for reads and writes
- I/O requests per second throughput (IOPS)
  - regardless of the I/O request size
- even seemingly random events such as a storage system performing:
   - garbage collection
   - tiering
   - deduplication
   - compression
   - encryption etc.

The only conclusion you can draw from disk utilization is the percentage of time your block device was not working on host I/O requests (for 100% utilization that would be 0% of the time).

Let me give you an example. Let's say you have a device capable of throughput of 1000 I/O requests per second (1000 IOPS). Moreover, this device has a latency of 2 seconds.

One scenario with this device is the host sending it 1000 I/O requests at `t0`. With these device characteristics, all the requests will be completed at `t0+2`. If the host sends 1000 requests per second for 1000 seconds it will have completed 1M I/Os after ~1000 seconds, which means that the device was performing at its limit, because it was serving 1K I/Os per second on average. This is obviously a 100% disk utilization scenario.

Imagine now the host sending 1 request per second for 1000 seconds. The first request will be sent at `t0` and will complete at `t0+2`. The second request will be issued at `t0+1` and will be completed at `t0+3` etc. This means there will *always* be at least 1 outstanding request in the device queue. Since the device never has an empty queue this is *also* a 100% disk utilization scenario. However, this device is operating at 0.1% of its capacity since it's only serving 1 I/O per second on average.

**Comment by fayak** [comment]
woaw thanks for the detailled answer @mfundul !
It does make a lot of sense
