### ISSUE TITLE
"spotty" charts

### ISSUE THREAD

**Issue by carsten-AEI** [firehol/netdata#2913]
Hi

I'm not sure if I missed a similar issue browsing here or if this is just because the server is quite busy. I just started with netdata today installing 1.8.0 (backported to Debian 8/Jessie) on a busy server. As can be seen from the attached screenshot, some graphs look fine (like load/disk) but some like cpu are sparse.

![busy_a0101](https://user-images.githubusercontent.com/16311083/31894238-1758a626-b80e-11e7-8071-40d71054c762.png)

As I'm new to netdata, my question is if this is an issue on the server side or from within my browser and which knobs I should look at to make it become better.

netdata shows me
> netdata on a0101, collects every second 10,458 metrics, presented as 882 charts and monitored by 73 alarms, using 168 MB of memory for 1 hour, 6 minutes and 36 seconds of real-time history.
as a brief summary of the host.

![system_a0101](https://user-images.githubusercontent.com/16311083/31894407-aa43568e-b80e-11e7-9ebe-907649c1859f.png)

**Comment by ktsaou** [comment]
Hi,

By default netdata runs with the `idle` process scheduling policy. This means it get CPU only when all the other programs do not need it.

Since your server is very busy, I suggest to change that.

I just created a wiki page to explain how to do it: https://github.com/firehol/netdata/wiki/netdata-process-priority

I suggest to set netdata scheduling policy to `rr` and then experiment with the scheduling priority (I think 99 will work without much experimentation).

**Comment by carsten-AEI** [comment]
Thanks for the quick and long reply and wiki page. I've prepared the changes (systemd variant) but this morning the system's load was different and not "spotty" anymore - so far I was also not able to trigger this state artificially by running _stress_ or similar tools. I'd say, let's close the issue as it enhanced the documentation and I and others should have a place to start working from!
