### ISSUE TITLE
Performance optimization of key netdata daemon components

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#292]
ok. The netdata daemon is pretty fast already!

However there are key components in the netdata daemon that can be optimized further. Optimizing these components could lower netdata CPU utilization even more.

Which are these components?
1. lookup for a chart (`rrdset_find()`, `rrdset_find_bytype()`, `rrdset_find_byname()`)
   
   These calls are used in many places:
   - in data collection to find the chart that needs to be updated
   - in API calls to find the chart the user wants to fetch data for
   
   A netdata without any web clients is performing a few hundreds of these calls per second.
   
   Internally these calls use b-trees indexes (`avl.c`) so their performance is already quite good (all string comparisons in the b-tree are already made using `uint32_t` hashes first, and only when the hashes match, the string comparison is made), however `avl.c` uses locks to prevent searching and modifying the index in parallel.
   
   We need a) to measure the performance of these calls and b) either find ways they can be further optimized or prevent such calls were possible (in data collection it is possible for several modules).
2. `storage_number.c` has encoding and decoding functions for numbers from `calculated_number` to `storage_number` and vice versa. These calls are executed thousands of times per second (at least one encoding for each dimension and hundreds of decoding calls for each web chart refresh).
   
   The performance of chart generation could also be affected by `print_calculated_number()`. Netdata is already 10 times faster than a normal `snprintf()`, but this does not mean we cannot do it 20 times faster.
3. In #263 @fredericopissarra suggested that we can do all internal calculations using `double`, or `float` instead of `long double` (it is just a `typedef long double calculated_number` in `storage_number.h` and the whole of netdata can be compiled using the new format). This might have a significant impact in performance. We need to measure this.
4. In #255 @fredericopissarra showed that date to javascript dates conversion can be done using half the resources. His suggestion is merged with #299 . Similar "obviously not optimal" cases may exist. We need to fix all these.

So, what we need is:
- measure the performance of the components, as-is
- implement a few unit tests that will allow us to change them / experiment with them, without breaking something
- experiment with alternative ways of optimizing them

Once we have all these, it would also be nice the difference in netdata performance between gcc options `-O2` and `-O3`.

**Comment by fredericopissarra** [comment]
Here some further thoughts about using double.. Any integer value between 0 and 9007199254740991 (53 bits '1') can be precisely encoded in a double. Since the upper limit, as defined in STORAGE_NUMBER_POSITIVE_MAX, is 167772150000000.0, with one less leftmost decimal algarism, double is enough.

As I understand (I am still studying the code) storage_number.c encodes floating point's "mantissa" in 24 bits, reservind 3 bits for a "flag", to accomodate two special cases: overflows and "empty" values. I think the "not a number" (NAN) can be used as "empty" value. The overflow could be encoded as +inf or -inf, but of course one can check for the absolute upper limit.

I'm still trying to see if accuracy checking is that important in the cenario... trying to undestand the details of rrd.c and rrd2json.c... ;)

[]s
Fred

**Comment by ktsaou** [comment]
@fredericopissarra thanks for commit #299 . It is merged! I updated the description to reflect this. Thanks!
