### ISSUE TITLE
Send calculated data to backend.

### ISSUE THREAD

**Issue by vaheminasyan** [firehol/netdata#2948]
Hi.
We have about 70-80 servers, from which we collect metrics and send them to Graphite backend and then visualize their data in Grafana.
The problem is that we have to do a lot of math to get cpu usage, Memory usage, etc (almost for every metric). 
For this reason our graphite backend falls under high load and doesn't return data to dashboards.
How can this problem be solved?
Is there a way to do math on Netdata side?

**Comment by ktsaou** [comment]
Hi,

are you pushing metrics from netdata `as collected` or as `average`?

If you push averages, netdata does the math. So, at graphite you will see the values, as they appear on netdata dashboards. All metrics will be gauges at graphite. No counters.

Will this help?

**Comment by vaheminasyan** [comment]
Hi. 
I'm pushing metrics as `average`
Sorry but that doesn't help, and here is why. 

For example, I want to see RAM usage by percent, but for doing that, I have to calculate total RAM, then calculate which percentage is being used.

For CPU I have to add all the metrics besides 'idle'.
And so on, almost all metrics have to be transformed.

**Comment by ktsaou** [comment]
So, you say that you need netdata to also push a few summarized metrics: the percentage of used ram, or the percentage of CPU used as a total.

netdata can do such calculations (it does already), via its API. So, it more or less follows the same principle (if grafana is the netdata dashboard and graphite is the netdata server, then grafana instructs graphite to make the calculation and return it).

I think the problem you have is probably due to to graphite. In graphite, each metric is autonomous. I have seen people working with prometheus that have much better results in terms of query simplicity. 

When netdata pushes metrics to prometheus, it pushes a metric per chart (i.e. `system.cpu` is 1 prometheus metric) with all the dimensions (`user`, `system`, `idle`, etc) as tags (check #2436). So, in prometheus you can say: give me `system.cpu` without its `idle`.

On the other hand, graphite gets a metric per dimension (the graphite protocol does not support anything else).

So, you are probably hitting a limitation of graphite.

PS: opentsdb is also capable for tags, but netdata sends the metrics like it does in graphite. I have an issue open to fix that for opentsdb #2690

**Comment by vaheminasyan** [comment]
Thanks for the answer.We'll also check prometheus.

**Comment by ktsaou** [comment]
ok nice. I am closing this, but you can still post.
