### ISSUE TITLE
Filter Alarm Notifications

### ISSUE THREAD

**Issue by scragg0x** [firehol/netdata#2965]
I know it's possible to just send "critical" alarms via email.  Can the same thing be done with discord for example?

**Comment by ktsaou** [comment]
Yes, exactly the same way: just append `|critical` to the recipients you want to send critical alarms only.

**Comment by scragg0x** [comment]
@ktsaou The `recovered` message comes through, is there a way to filter that?

**Comment by ktsaou** [comment]
Well the recovered message comes only when the critical has been sent. So, CLEAR -> WARNING -> CLEAR does not send anything to critical recipient. But, if critical is sent, then the next transition (WARNING or CLEAR) will update the critical recipients too. I think this is the right thing to do. Otherwise critical recipients will never get notified that something is not critical any more.
