### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by jasonbronson** [firehol/netdata#2989]
I have netdata installed and running. I want to link up to https://newyork.my-netdata.io/#menu_apps;theme=slate;help=true to have my servers show up here.

I currently get from the alarms "Sorry... your account is not linked to a netdata server named:ubuntu"
I don't really want to open up incoming ports for 19999 on my machines, I'd rather just view alarms at the main registry but not sure why my servers do not show in the list.

any help here?

**Comment by ktsaou** [comment]
Hi,

The button on the email notifications should divert you on the server dashboard. But since you do not open 19999 on your servers, there is no dashboard to view.

There are many alternative ways to get the dashboard:

1. Do not open port 19999 on any server, but use `ssh` to forward remote port 19999 to local port 19998. So, to access a dashboard you will have to first ssh to it and then access `http://localhost:19998/`.

2. Open port 19999 on all servers, but configure access lists at netdata.conf to allow an nginx of yours proxy the dashboards. So you will just need an nginx with static IP. This will also allow you to have user authentication and single sign-on.

3. Use `gvpe` or `tincd` to create a mesh management VPN on all your servers. This way your laptop or PC will join the VPN and provide you access to all your administration apps.

4. Open port 19999 on at least one of your servers. If you open up just one, you can stream metrics from all your other servers to the one you opened. Then you will have all the dashboards of all your servers published by that one server. Of course you can mix this setup with any of the above.

I am sure there are more ways to do it.

We are building a free online health monitoring service, so that you will be able to view alarms and basic dashboards for all your servers centrally, at one of our servers, but this is not ready yet.

**Comment by jasonbronson** [comment]
Got it I didn't realize this was not ready yet from the documentation it appeared as if the GUID allowed us to view it on your server.
Thanks can't wait until you update it to view on your servers. Also is there anyway to update the notifications to use a custom url so we can open it on our servers but the email link points to the right URL?

**Comment by ktsaou** [comment]
> Also is there anyway to update the notifications to use a custom url so we can open it on our servers but the email link points to the right URL?

it should learn by itself. Access the dashboard on any URL, even multiple URLs and the registry will learn.

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but if you need help just post.
