### ISSUE TITLE
netdata under docker: names for other docker containers (instead of IDs)

### ISSUE THREAD

**Issue by dmnc-net** [firehol/netdata#2995]
I've installed NetData as a container in RancherOS. In NetData I can see containers but they are labeled with their Container ID:
![image](https://user-images.githubusercontent.com/2069874/32660151-fcf3f07a-c621-11e7-8d7b-f3cb69673c2d.png)

Is it possible to have Container names which I can see in the `docker ps` output? I mean some global rule which can do that dynamically because I don't want to modify configuration with every change within containers.

Note, this is not a duplicate of #329, but kinda similar.

**Comment by dmnc-net** [comment]
Maybe #2973 has some clues, now I'm finding out how to edit the netdata.conf ... I'm in the container shell but `/etc/netdata/netdata.conf` contains just one line:
`# Get config from http://127.0.0.1:19999/netdata.conf`

**Comment by ktsaou** [comment]
Hi,

netdata already does this.

netdata comes with a script that takes care of consulting docker for container names: https://github.com/ktsaou/netdata/blob/b4fdb9658e7f1aee3b0a450cb34b94515989a71f/plugins.d/cgroup-name.sh#L77-L95

However, to work it needs access to the `docker` command, or `/var/run/docker.sock`.

The problem is that you run netdata in a container. Neither of these are available inside a container.

I see @titpetric [has documented](https://github.com/titpetric/netdata#monitoring-docker-container-metrics) that you can create the netdata container with `-v /var/run/docker.sock:/var/run/docker.sock`, so that the `docker.sock` will be available at the netdata container. Check also the options he suggests.

If you install netdata at the host, it will find out by itself.

**Comment by dmnc-net** [comment]
Thanks @ktsaou, it makes sense. I've tried that but with no difference (IDs are still untranslated):
```
docker run -d --name NetData --cap-add SYS_PTRACE \
 -v /proc:/host/proc:ro \
 -v /sys:/host/sys:ro \
 -v /var/run/docker.sock:/var/run/docker.sock \
 -p 19999:19999 \
 firehol/netdata
```
but option is effective: `srw-rw---- 1 root 1101    0 Nov 10 08:28 docker.sock`

**Comment by ktsaou** [comment]
I think you now have a permissions issue:

```
srw-rw---- 1 root 1101 0 Nov 10 08:28 docker.sock
```

is not accessible by user `netdata` inside the container.

Unfortunately I don't know how to fix that. @titpetric any ideas?

**Comment by titpetric** [comment]
The permissions are the same as the host. In order to access the socket,
you'd have to be either root, or the user id 1101. I think the main issue
here is that netdata, as it runs in the container, doesn't run as root, and
the group ID doesn't match with the host?

1. You could use either https://github.com/titpetric/docker-proxy-acl to
create a globally readable docker.sock which would be read-only and could
be used by netdata,
2. You could just make your docker.sock `chmod a+rw docker.sock` but I'd
recommend against that because you'd give everyone access to docker, even
possible non-privileged users,
3. Install netdata outside of the container. The docker.sock permissions
would then stay the same.

Unfortunately there's nothing that netdata can do about this, it's all in
your domain as the sysadmin.

Best,
Tit

**Comment by dmnc-net** [comment]
Thanks Tit,

I did a quick (successful) test by `chmod` but you're right, this is very bad idea. Because I'm using RancherOS and there a lot of system services even runs as a container, one have two options:
1. stick with RancherOS architecture/idea and go with `docker-proxy-acl` in a container (because ROS is withou Go)
2. install on top of the ROS which is working too (my choice at this moment because another container for the proxy takes next resources)

Thank you guys for you advice.
