### ISSUE TITLE
Recomended conditionals in custom alerts

### ISSUE THREAD

**Issue by shellshock1953** [firehol/netdata#3082]
In most of defaults Netdata alerts, there are such warn and crit conditionals:
```
warn: $this > (($status >= $WARNING)  ? (75) : (85))
crit: $this > (($status == $CRITICAL) ? (85) : (95))
```
I know about [alerting expressions](https://github.com/firehol/netdata/wiki/health-configuration-reference#expressions), but the question is: Does such conditionals make much sense and do I need to use this as recommended when creating custom alerts?

**Comment by Ferroin** [comment]
It's being used to provide hysteresis, which is generally something you want when tracking stuff like this.  For a technical explanation, Wikipedia has a good article about [Hysteresis](https://en.wikipedia.org/wiki/Hysteresis), but the short explanation is that the thresholds for triggering an alert with hysteresis are higher than those for resetting it, so that if the value oscillates around the threshold it won't repeatedly trigger the alert.

Using the quoted lines as an example, the given alarm will behave according to the following conditions:

1. If the alert state is not warning, switch to warning state when the value goes above 85.
2. If the alert state is not critical, switch to critical state when the value is above 95.
3. If the alert state is warning, return to normal state when the value goes below 75.
4. If the alert state is critical, return to warning state when the value goes below 85.

In effect, this means that:
* While the value is rising, it will trigger a warning when it exceeds 85, and a critical alert when it exceeds 95.
* While the value is falling, it will return to a warning state when it goes below 85, and a normal state when it goes below 75.
* If the value is constantly switching between 80 and 90, then it will trigger a warning _the first time_ it goes above 85, but will remain a warning until it stops oscillating and goes below 75 (because of the combination of conditions 1 and 3 above).
* If the value is constantly switching between 88 and 98, then it will trigger a critical alert _the first time_ it goes above 95, but will remain a critical alert until it stops oscillating and goes below 85 (because of the combination of conditions 2 and 4 above).

**Comment by shellshock1953** [comment]
@Ferroin thank you.
Great explanation!

**Comment by l2isbad** [comment]
@Ferroin ye, gj 👍 .
 it would be great if you updated the [wiki page](https://github.com/firehol/netdata/wiki/health-configuration-reference#expressions)

**Comment by Ferroin** [comment]
@shellshock1953 Glad I could help!

@l2isbad I'll look into doing so later today, as that should get much better visibility than this.
