### ISSUE TITLE
Snapshots

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#309]
I find this idea quite interesting. Snapshots could be used to save chart data for a specific timeframe and a specific detail.

For example, when you have an incident you just ask for a snapshot and all (or a few of) your chart data are dumped. Then, on the dashboard you could just load these chart data back to inspect them.

These snapshots could also be triggered programmatically (a command line or an API call - although the later requires SSL and API authentication).

**Comment by pjlegato** [comment]
With this, one could easily write a little script that rotates the snapshots into a remote S3 store (or similar) to get a continuous archive of all past states.

**Comment by FallingSnow** [comment]
[Zstd](https://github.com/Cyan4973/zstd/blob/master/README.md) and its training mode may be of use in storing all these snapshots.

**Comment by raedah** [comment]
Here is an example of what I am referring to for long term view.
http://demo.munin-monitoring.org/munin-monitoring.org/demo.munin-monitoring.org/open_inodes.html

**Comment by mo0nsniper** [comment]
If there will be the option to save data at minute interval this will make the data compress better than at second interval because there will be smaller difference between data points.

**Comment by pjz** [comment]
A colleague pointed out that the lack of being able to save history remotely means that it's useless for monitoring ephemeral hosts (think auto spun up/down EC2 hosts) because if one crashes there's no help figuring out why/how.

**Comment by ktsaou** [comment]
> A colleague pointed out that the lack of being able to save history remotely means that it's useless for monitoring ephemeral hosts (think auto spun up/down EC2 hosts) because if one crashes there's no help figuring out why/how.

The next version of netdata will propagate all its alarms in realtime to a central netdata. I am also trying to add alarms for everything imaginable (and I need your help for that - even if you don't know how to write alarms - open issues to suggest ones - I'll write them).

I would love to have the alarm sync to include an update of key system metric, once every 30 seconds (this will also allow us to detect that a host crashed, it will not check-in - or that a host rebooted).

Netdata could also push some or all of its data to a graphite, opentstdb, influxdb, etc if you really want it. The code missing for that is not that complex, but I really need someone to get ownership of this functionality.

**Comment by thinrope** [comment]
Yep, snapshots are really the first step towards being able to actively tune performance.
The second is being able to compare snapshots (basically adding ΔT to the first and displaying them together is a good start).
So, run a command, record the execution, snapshot, run again with different parameters, snapshot, diff/analyze.

I just discovered the API, so pulling the data (in CSV), then using gnuplot it is possible.

Adding re-sampling (averaging) will provide for (lossy) data archiving (e.g. store at 1min instead of 1s), while snapshots should retain full data (lossless).

While I understand somewhat the architecture/ideas behind netdata's way to store data on the source, having options for data shipping, or at least batch moving to another host is critical in short-lived environments.

**Comment by ktsaou** [comment]
Client side snapshots have been implemented with PR #3000 !

So,this can be considered complete, with the exception that snapshots are saved on your computer (not the server) and cannot be triggered programmatically.
