### ISSUE TITLE
customize dashboard_info.js error!

### ISSUE THREAD

**Issue by hhgzxn** [firehol/netdata#3104]
I followed this [instruction ](https://github.com/firehol/netdata/wiki/Overview#customizing-the-standard-dashboards), and pasted 'custom dashboard_info.js = dashboard_info_custom.js' under [web] section of netdata.conf;but when I restart the system,the index.html popped up an error 'Cannot load required JS library:http://192.168.31.194:19999/dashboard_info_custom.js'

I do have 'dashboard_info_custom.js' under path '/usr/share/netdata/web',so what's the problem?

**Comment by ktsaou** [comment]
Hi,

2 possible issues:

1. The file is not served at all (due to wrong filename or permissions). To verify it is served, press F12 on your browser and check the network tab. If it has status 200 it is served. You can also try to download it by the URL you pasted above.

2. The file is served, but the browser finds a syntax error in it (json is very strict). You can verify your file is valid json using a jslint service, like http://www.jslint.com/ or https://codebeautify.org/jsvalidate or https://jsonlint.com/

**Comment by hhgzxn** [comment]
@ktsaou It's the permission problem, I changed the file owner to netdata and solved. thx very much!
