### ISSUE TITLE
how to disable some of the alarm config?

### ISSUE THREAD

**Issue by hhgzxn** [firehol/netdata#3153]
is there any place I can disable the alarms like what it did for plugins?

**Comment by ktsaou** [comment]
Many options:

1. You can disable all the alarms by disabling health monitoring at netdata.conf

2. You can disable all alarms in a given file by replacing that file with an empty one. Do not just delete it, because a netdata update will re-install it. If the file is there but is not the original shipped by netdata, the installer will not overwrite it.

3. You can disable individual alarms by commenting them out (each alarm email and the dashboard says where).

4. You can silence individual alarms by changing their `to:` line to `to: silent`. The alarm will be shown on the dashboard, but it will not send any notifications.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.

**Comment by nyetwurk** [comment]
Is there a way to override alarms without editing the upstream installed configuration files? I.e. override only a few items from default?

**Comment by cakrit** [comment]
> Is there a way to override alarms without editing the upstream installed configuration files? I.e. override only a few items from default?

See #3414. I expect it will be finished next week.

**Comment by nyetwurk** [comment]
> > Is there a way to override alarms without editing the upstream installed configuration files? I.e. override only a few items from default?
> 
> See #3414. I expect it will be finished next week.

Not really what I'm looking for... more this:
https://github.com/netdata/netdata/issues/5669#issuecomment-481455138
