### ISSUE TITLE
Some questions about volume of hard disk, bandwidth and SNMP Data Collector's scalable.

### ISSUE THREAD

**Issue by talkyy** [firehol/netdata#3194]
Hi, I am using netdata to monitor a number of Switch via SNMP Data Collector. I need some information about netdata:
1. How many MB does netdata take on hard disk? (I think it is not large but I need a specific number).
2. I collect metrics via SNMP, that mean netdata will take a volume of bandwidth of network. How can I know the volume of bandwidth that netdata take?
3. How many SNMP devices that I can add to? Is it possible to add 100 or 1000? What does it depend on?  (Now I only add 26 devices).
4. This is a question a bout InfluxDB and Grafana. In default dashboard, a few dimensions are showed by percentage (in chart `apps.cpu`). When I use InfluxDB to store metrics and show them by Grafana, it is not in percentage. How can I change them to true format?
This is in default dashboard:
![image](https://user-images.githubusercontent.com/26269505/34455416-6f8c862c-edb1-11e7-9288-e40e64bc9884.png)

This is in Grafana:
![image](https://user-images.githubusercontent.com/26269505/34455439-fc93b0f4-edb1-11e7-81f7-7dc29eb6bfd9.png)

Thank you for make a awesome tool!!!

**Comment by ktsaou** [comment]
> How many MB does netdata take on hard disk? (I think it is not large but I need a specific number).

Check the wiki page memory requirements. The amount of RAM is also used for disk. netdata needs some additional disk for log files.

> I collect metrics via SNMP, that mean netdata will take a volume of bandwidth of network. How can I know the volume of bandwidth that netdata take?

I suggest to setup FireQoS on your netdata server. This way you will be able to classify traffic from/to the machine any way you like it and netdata will provide nice real-time charts. Actually, I always setup fireqos on all servers, even if not directly needed. The reason is simple: fireqos + netdata provide perfect insights and the overhead is ignoreable.

> How many SNMP devices that I can add to? Is it possible to add 100 or 1000? What does it depend on? (Now I only add 26 devices).

It depends on your CPU. snmp data collection is done with node.js. Node.js is single-threaded, so you can add more nodes as long as the `node.d.plugin` at the `Applications` CPU chart (apps.cpu) is below 100%. If it reaches 100% you can still add more nodes, if you lower the data collection frequency.

> This is a question a bout InfluxDB and Grafana. In default dashboard, a few dimensions are showed by percentage (in chart apps.cpu). When I use InfluxDB to store metrics and show them by Grafana, it is not in percentage. How can I change them to true format?

Set `data source = average`. Now you have `data source = as-collected`.

**Comment by talkyy** [comment]
Thank you for your respond. This can be close now. :)
