### ISSUE TITLE
GSoC '18

### ISSUE THREAD

**Issue by luserx0** [firehol/netdata#3294]
Will netdata participate in this year's GSoC under the GFOSS umbrella?
If so, could there be labels for issues related to GSoC interested students?
Are there any existing ideas on projects?
Also is there any Contributor interested in mentoring a student?

Thanks,
Harry

**Comment by luserx0** [comment]
SO netdata is participating on GSOC '18 under GFOSS.
@ktsaou any directions as to what netdata would like to be accomplished?

**Comment by ktsaou** [comment]
Hi, sorry for the delay.

Unfortunately I cannot participate as a mentor this year.

I have already received a few requests from students, which I had to reject.

The folks at GFOSS have requested to propose other mentors that could participate in GSOC '18 for netdata, under the GFOSS organization.

@l2isbad @Ferroin I think you can do this, if you want to do it of course.
Are you interested? GSOC is generally a nice experience for both mentors and students.

The idea is to participate as a mentor. You will receive proposals to improve netdata in certain areas (may be new plugins, documentation, or whatever netdata related - you can influence this), then you will pick the best proposal and finally help the student that proposed it, to build it / make it happen.

**Comment by Ferroin** [comment]
While I would love to, I can't really consistently commit enough time to do so, and I would much rather not risk making it a bad experience for someone because of me suddenly not being available for week or two.  I've been lucky during the past few months that I haven't been busy,  but there's a very real possibility that things will get sufficiently chaotic at work that I'll effectively be offline for an extended period of time.

**Comment by ktsaou** [comment]
ok, thanks!
I guess this is not our year. I'll try to participate next year.
