### ISSUE TITLE
Question: VM alarms

### ISSUE THREAD

**Issue by pavlpap** [firehol/netdata#3302]
Hello, 

I have an issue with my VMs that are running on a CentOS7 host (where the netdata is running). I have checked the [wiki](https://github.com/firehol/netdata/wiki/health-configuration-reference) and I haven't find any solution. What I already know (thanks to Costas) is that in case I am running a netdata daemon on each VM, then I will also get the relevant alarms that I want. What happens in case of a Windows machine? Also, as far as I can understand on the wiki page, the configuration files under the /etc/netdata/health.d directory can be ran only on Linux, MacOS or FreeBSD. 
So my question is, in case of a VM that I want to have alarms from a VM (Windows or Linux), is that possible without a netdata daemon?

Thank you in advance guys.

Pavlos

**Comment by pavlpap** [comment]
So guys, any feedback? If it's possible, just point me to the right direction. :)

**Comment by Ferroin** [comment]
It sounds like SNMP might be able to do part of what you want, albeit with some effort required for setup in each of the VM's, and a much more limited list of things you can monitor.  As a general rule, you can most likely track disk utilization and network interface counters via SNMP, and depending on the system you may be able to track other data.

Unfortunately, putting this together is _really_ involved, and the required information is scattered across multiple locations:

* Configuration info for the Netdata SNMP plugin can be found [here](https://github.com/firehol/netdata/blob/master/conf.d/node.d/snmp.conf.md).
* For Windows guests, you need to enable the SNMP Agent service and configure it.  Unfortunately, I have been unable to find single link on this that I feel comfortable posting here (largely because how you do this depends on the exact version of Windows), if you just search 'windows snmp service configuration' on your favorite search engine and check a handful of the results, you should be able to find info for your version of Windows.
* For UNIX guests, you need to install and configure an SNMP agent.  On Linux, you want [net-snmp](http://www.net-snmp.org/), which should be packaged by your distribution (also, their site has some great tutorials that cover the basics of SNMP pretty well, I would suggest reading through those).  For other UNIX systems you can still use net-snmp if you want, but some of them may have a pre-installed SNMP agent (for example, FreeBSD has [bsnmpd](https://www.freebsd.org/cgi/man.cgi?query=bsnmpd&sektion=1)).

**Comment by pavlpap** [comment]
Hello @Ferroin and thank you very much for the reply and for the sources.
I will check out your answer and check it.
Thanks again.
Cheers!
