### ISSUE TITLE
help|how can I change http://domain.com:19999 to http://sys.domain.com

### ISSUE THREAD

**Issue by fmzz** [firehol/netdata#3336]
I can access http://domain.com:19999 and see the dashboard , but if I creat a vhost named http://sys.domain.com and set it's root to /wwwroot/netdata/usr/share/netdata/web , a 405 error will appear , it says "Cannot download charts index from server: http://sys.domain.com/api/v1/charts".
What should I do? help me plz, and thanks a lot.

**Comment by Ferroin** [comment]
About 95% of the actual netdata dashboard id dynamically generated by netdata itself on access through the internal web server, while your design assumes it's static data generated by netdata than written to disk.  Instead of trying to serve things yourself, you need to proxy access through your vhost to the netdata URL.

Check:
* [Here](https://github.com/firehol/netdata/wiki/Running-behind-nginx) if you're using nginx.
* [Here](https://github.com/firehol/netdata/wiki/Running-behind-apache) if you're using Apache.
* [Here](https://github.com/firehol/netdata/wiki/Running-behind-lighttpd) if you're using lighthttpd.
* [Here](https://github.com/firehol/netdata/wiki/Running-behind-caddy) if you're using Caddy.
