### ISSUE TITLE
Authentication Options

### ISSUE THREAD

**Issue by s3w47m88** [firehol/netdata#3372]
I read in the Wiki this is the proper place to request support.

I have read through some of the docs, and search the Issues here, and Google to find information on how to set up authentication so the monitoring isn't open to the public but I'm not finding _any_ information. 

Is implementing authentication up to the user to decide? Or is there a built in utility for this?

Thank you for your time.

**Comment by Yaser-Amiri** [comment]
I found two way:
1- Using Nginx as a reverse proxy and setting up HTTP basic authentication on it. (there is a tutorial about this in wiki)
2- Using Nginx as a reverse proxy and authentic user with your own HTTP server [Link](https://medium.com/@Yaser_Amiri/add-django-authentication-to-netdata-ed3a800ccc43)

**Comment by Ferroin** [comment]
Netdata itself does not support authentication, as it's primarily designed to serve data on the loopback interface or to trusted networks.

If you want authentication, the methods recommended by @Yaser-Amiri in his comment are what I would suggest for doing so.  Make sure though that you're serving it over HTTPS from Nginx though, as otherwise your authentication credentials are visible to anyone with a packet capture tool on the network.

**Comment by l2isbad** [comment]
Not authentication but netdata has basic filtering mechanism

```
For netdata v1.9+ you can also use netdata.conf:

[web]
	allow connections from = localhost 1.2.3.4
```

thought it worth to mention

**Comment by s3w47m88** [comment]
Great thank you everyone! I'll reprot back the exact steps I take to set this up in case others in the future want to know.

**Comment by ktsaou** [comment]
I am closing this, but you can still post.
