### ISSUE TITLE
Wrong disk space metrics

### ISSUE THREAD

**Issue by vaheminasyan** [firehol/netdata#3390]
Hi all.
One of our netdata instances periodically doesn't report 'available' space on the partition, which causes false alerts.
![screen shot 2018-02-05 at 11 47 08 am](https://user-images.githubusercontent.com/20648927/35793328-9cbf7afc-0a6a-11e8-9625-8f150a0423a0.png)

**Comment by ktsaou** [comment]
hm... this is strange.
Which filesystem?

netdata uses the `statvfs()` call to get these statistics. The interesting part is that from the chart it seems the call succeeds (there is no gap in the chart, only the available space is gone), so netdata did collect it.

The code is straight forward: https://github.com/firehol/netdata/blob/98d08bc77c815a01bbda6f29af64423062872aff/src/plugin_proc_diskspace.c#L209-L217

`bavail` is the reported available and is passed to the chart, without any processing at all: https://github.com/firehol/netdata/blob/98d08bc77c815a01bbda6f29af64423062872aff/src/plugin_proc_diskspace.c#L277

So, my understanding is that this is what the system reports. Since it happens for quite some time, and you get an alert, could you please run `df -h` while this happens?

**Comment by vaheminasyan** [comment]
I've done it and df -h shows true stats at that  time.
But anyway, after a day or two the problem went away.
I'm closing the issue. If it happens again, I'll reopen and try to give more info.
