### ISSUE TITLE
Ephemeral question

### ISSUE THREAD

**Issue by Vartkat** [firehol/netdata#3408]
Hello,

I read "Real-time performance monitoring for ephemeral nodes" (https://github.com/firehol/netdata/wiki/Monitoring-ephemeral-nodes).

I have three different machines with Netdata installed, nothing ephemeral here, and I know this is not the primary purpose of Netdata but I was wondering if I could use this feature to be alerted when one of the machines goes down.
As Netdata is monitoring the machine on which he's running, if the machine goes down (or even offline from the Net), as he is also dead or isolated, he has no mean to alert.

I plan to make A master for B and C, B master for A and C, C master for A and B, with an different API_Key for each master.

What if on masters I put 
` 
    health enabled by default = yes
 `
in /etc/netdata/stream.conf ?

I assume I will receive three alarms for each problem when a service is having problem, but I was wondering if I would receive two alarms (3 minus 1 dead) if one of the machines goes completly down or even offline from the Net ?

Is it the right way to get where I want ?
Am I missing something ?
Do I have to build a custom dashboard to see each machine's chart ?
Thanks for your help

Regards

V.

**Comment by ktsaou** [comment]
> health enabled by default = yes

You will receive a lot of alerts when this is set to `yes` instead of `auto`.
Try it. But, if you have short network disruptions, you will still receive such alarms.

A more efficient way (no data replication, lower cpu and memory usage) would be to configure the fping plugin to ping the others servers you want to monitor. This will also provide latency information, packet loss, etc.

I am also thinking of adding a tcp-ping plugin, that will connect to any tcp port and disconnect immediately, so that it will monitor any tcp service you like.

**Comment by Vartkat** [comment]
I confirm, ping plugin is a better solution, thanks a lot.

Regards

V.
