### ISSUE TITLE
IRC notifications

### ISSUE THREAD

**Issue by io7m** [firehol/netdata#3435]
Hello!

I notice from reading the wiki that there are a lot of ways to send notifications to the current trendy messaging services (Discord, Slack, etc).

Is there no way to send alerts to an IRC channel for those of us still living in the previous century?

**Comment by ktsaou** [comment]
Is there a command line that can post an iirc message to a channel? If yes, the fix is very simple.

You can edit https://github.com/firehol/netdata/blob/master/plugins.d/alarm-notify.sh and copy-paste-rename one the existing methods to call that command line.

Once you do this, please make a PR.

**Comment by Ferroin** [comment]
I think supporting irker would be nice (and actually should be insanely easy to do), but it would also be nice to not need yet another daemon running somewhere if that is at all possible.

The problem is that IRC is very much a stateful connection-oriented protocol designed to idle as efficiently as possible at the cost of connection setup.  It's not the type of protocol that you can easily just connect to send a single message and then disconnect, and expect to do so at a potentially very high frequency.  irker works as well as it does because it maintains a persistent connection to the server.

**Comment by io7m** [comment]
There is this thing:

https://tools.suckless.org/ii/

It exposes a filesystem-based IRC client. Sending a notification to a channel is achieved by writing a message to a named pipe in the filesystem.

I'll do a bit of experimenting.

**Comment by ktsaou** [comment]
yes
