### ISSUE TITLE
Wire protocol documentation?

### ISSUE THREAD

**Issue by aigr** [firehol/netdata#3456]
I have a situation where I need to collect metrics from hosts on which I cannot install NetData. I can connect to these hosts over the network and use different APIs to gather the metrics.

My first thought was to write some plugins for NetData that did just that. Connect over the network to these other hosts and gather the metrics.

The problem with that is that the metrics now look like they originated from the NetData host.

From what I gather, plugins cannot "impersonate" other hosts when outputting metrics.

Another way could possibly be to write an application that mimics the way NetData streams data from one instance to another.  Then I assume that it would be possible to specify the "hostname".

Is there a good starting place to find out more about the wire protocol that NetData uses between instances?

**Comment by h0lzi** [comment]
Well just send the data you need via statsd?
https://github.com/firehol/netdata/wiki/statsd

**Comment by aigr** [comment]
Perhaps I misunderstand the statsd protocol, but as I read it, it's not possible to specify a hostname there either. You can send metrics yes, but they will be stored as if they concern the local host, no?

**Comment by Ferroin** [comment]
While it doesn't let you specify a host name, it does let you specify an arbitrary name for the metrics, and you could therefore just embed the host name in the name of the metric.

**Comment by aigr** [comment]
Yes, it would be possible to embed meta-data in the metric names, but then how would I configure e.g. the NetData UI to "unembed" the hostnames? Wouldn't I have to have special processing in the whole ecosystem, including things like InfluxDB and Grafana?

**Comment by ktsaou** [comment]
## streaming protocol

The plugin and the streaming protocols are exactly the same. So, a remote netdata slave streaming metrics to a netdata master, is actually treated by the master as just one... plugin!

But (the is always a "but"), the initiation of the streaming communication instructs the master netdata to isolate all the metrics to a different host, so that they will never overlap with other hosts.

The communication is not HTTP, but it looks very similar to it:

1. the slave connects to the master port and sends this: https://github.com/firehol/netdata/blob/9d079f6d5d84808645cee339b2dade90f26d8dba/src/rrdpush.c#L359-L372

2. the slave waits for the master to respond with this (yes, I know - but I really preferred this over `netdata streaming protocol v1`): https://github.com/firehol/netdata/blob/9d079f6d5d84808645cee339b2dade90f26d8dba/src/rrdpush.c#L26

3. then the slave starts streaming metrics, like the plugins do over pipes.

I think you can ignore the server response and just push the metrics with `ncat` (haven't tested it). Of course, if you don't send them the right way, the master will disconnect you, so you have to work around disconnects.

It is also important to send the chart definitions on each re-connect.

---

## statsd

if you need host tags on the backend time-series db, then yes, you will need to send them as separate hosts.

What you can do though, is start multiple netdata on the master on different ports. If you disable all plugins except statsd, netdata is extremely lightweight and you can open thousands on the same host, on different ports (pay attention to the paths though - each should have its own - you can achieve this with just a startup script - quite easy).

So, slave host A will send metrics to port 8126, slave host B to 8127, slave host C to 8128, etc.

You can even build a mini-network of netdata on the same host. So, all these statsd-netdata will run with memory mode `none`, and just push their metrics via the netdata streaming protocol on a netdata master running on port `19999`, which will run health checks and send metrics to the time-series db.

This is an example on how to do this -  run it and you will have a very light netdata listening for statsd data on port 8126 and will attempt to stream all metrics to a master netdata on localhost on port 19999.

```sh
host="host1"
port=8126

dir="/tmp/netdata-statsd-${host}"
mkdir -p "${dir}" "${dir}/etc" "${dir}/cache" "${dir}/lib" "${dir}/log" || exit 1

cat >"${dir}/etc/stream.conf" <<EOF
[stream]
  enabled = yes
  destination = tcp:localhost:19999
  api-key = f5b635a3-7a16-4d8c-9b65-b665cb84d333
EOF

chown -R nobody "${dir}" || exit 1

exec netdata -D \
  -W set global hostname "${host}" \
  -W set plugins proc no \
  -W set plugins diskspace no \
  -W set plugins cgroups no \
  -W set plugins tc no \
  -W set plugins idlejitter no \
  -W set plugins nfacct no \
  -W set plugins "enable running new plugins" no \
  -W set web mode none \
  -W set global "memory mode" none \
  -W set global "config directory" "${dir}/etc" \
  -W set global "log directory" "${dir}/log" \
  -W set global "cache directory" "${dir}/cache" \
  -W set global "lib directory" "${dir}/lib" \
  -W set global "error log" system \
  -W set global "access log" none \
  -W set global 'run as user' nobody \
  -W set health enabled no \
  -W set statsd enabled yes \
  -W set statsd "default port" ${port}
```

The above netdata is not maintaining a database and is not listening for web connections - it runs with just 5MB of RAM + the statsd metrics you will send.

**Comment by aigr** [comment]
Ah. Very nice.

It's good to see that it would be possible to "fake" a streaming NetData slave. If not for anything else than as a fallback plan.

I'd much more preferr to work within the "standard way" of things. Starting separate NetData nodes with `global hostname "foo"` seems like a great option!

The example conf that @ktsaou posted would be for a slave with "only" `statsd` functionality. I assume that it would be possible to start up slaves that use some plugins (in conjuction with the `global hostname "foo"`-thingy)? That way I could write my metrics collection code as standard plugins.
