### ISSUE TITLE
Can NOT send alarm without iptables input ACCEPT

### ISSUE THREAD

**Issue by tuanbo91** [firehol/netdata#3466]
I'm using netdata with latest stable CoreOS, everything is fine with only port 19999 allowed within iptables except sending alarm.

I've tried to set default input to ACCEPT and got notification/alarm as normal.

Does netdata need any other ports?

Thanks!

**Comment by tuanbo91** [comment]
I've figure it out, it's required a stateful firewall

**Comment by Ferroin** [comment]
Just to clarify, the issue is that any of the channels Netdata reports are not only over TCP (and therefore you have to accept inbound packets for the outbound connection), but are also done using protocols that require full duplex communication (SMTP or HTTP).  A simple:

    iptables -A INPUT -m state --state ESTABLISHED -j ACCEPT

Should be all that is needed to handle this (and you should actually have that to begin with in almost all cases, otherwise quite a few other things will stop working).
