### ISSUE TITLE
Question: Netdata email logic?

### ISSUE THREAD

**Issue by jeremyjpj0916** [firehol/netdata#3497]
I am curious if anyone is using the Netdata email functionality as I am trying to set that up, currently running on the debian jessie OS netdata has in its docker files. The code has this:

```
# The full path to the sendmail command.
# If empty, the system $PATH will be searched for it.
# If not found, email notifications will be disabled (silently).
sendmail=""
```

Does this string work for postfix as well(which is a newer MTA which is generally considered more user friendly)? I ask this because sendmail gives me a can't connect over localhost errors and I am just trying to see if there are alternative methods here.

Documentation here: https://github.com/firehol/netdata/wiki/email-notifications , leads me to believe that postfix could work since it states: "You need a working sendmail command for email alerts to work. Almost all MTAs provide a sendmail interface."

**Comment by Ferroin** [comment]
Yes, it works fine with postfix (that's what I use on my systems).  The requirement is that the MTA provide a `sendmail` command which allows local message submission (and of course that the MTA is properly configured).

Do note however that you generally need to not have the actual sendmail MTA installed if you're using another MTA, which sounds like what your issue is here.  Classical `sendmail` actually makes a SMTP connection over the loopback interface to the local mail server for message submission.  The postfix version however uses the `postdrop` command to inject the message directly into the mail-queue (kind of, it places the message in mbox format in the maildrop directory and notifies the appropriate postfix component that there's a new message, which results in that component queueing it), so it shouldn't be complaining about not being able to connect.

**Comment by jeremyjpj0916** [comment]
@Ferroin what does your sendmail="" look like if you don't mind me asking when using postfix?

Thanks!

**Comment by Ferroin** [comment]
I've not changed the value of the `sendmail` variable since installing Netdata, so it's empty just like the default.   The `alarm-notify.sh` script uses the regular $PATH logic in bash to find the command in that case, with PATH set by default to look in `/bin`, `/sbin`, `/usr/bin`, and `/usr/sbin`, so if you've installed postfix through your package manager, you shouldn't need to change anything (IIRC,, the `sendmail` command bundled with postfix gets put in `/usr/bin` on Debian, just like it is on my Gentoo systems).

**Comment by jeremyjpj0916** [comment]
@Ferroin thanks for taking some time this morning to answer my queries, you rock. Will test this out today. Closing topic.

**Comment by jeremyjpj0916** [comment]
@Ferroin When I run netdata slaves that send all data to a master node, only the master needs email populated to send alarms right?

**Comment by Ferroin** [comment]
@jeremyjpj0916 As far as I know, that's correct.  I've done very little with streaming though (99% of the systems I monitor need to operate completely independent of each other, so I can't really use streaming with them), so I'm not 100% certain.

**Comment by cakrit** [comment]
You control the slave health checks in `/etc/netdata/netdata.conf`. 
See https://docs.netdata.cloud/streaming/#configuring-the-slaves
You would need to set the following to disable health checks in the slaves:
```
[health]
    enabled = no
```
