### ISSUE TITLE
cPanel and exim/mysql charts missing

### ISSUE THREAD

**Issue by XGhozt00** [firehol/netdata#3552]
Anyone else have this issue? I searched around but I didn't see anything. I'm sure it's just a matter of configuring a few things so netdata can monitor mysql and exim properly on a cPanel server (CentOS 7).

I did see this in the log:

```2018-03-17 23:06:31: python.d ERROR: mysql: tcpipv4_netdata: Can't establish connection to MySQL: (1045, "Access denied for user 'netdata'@'127.0.0.1' (using password: NO)")```

Not sure why exim isn't showing, does it not show the chart if there are 0 emails in the queue?

**Comment by cloudz** [comment]
Did you look at the plugin requirements? 

You need to change the user/pass or my.cnf for MySQL in **/etc/netdata/python.d/mysql.conf** 

For exim to be reporting back you will need to add the following rule to **exim.conf** because the command runs **exim -bpc** and this is not permitted to the netdata user by default.

> queue_list_requires_admin = false

Halfway done this page : [https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata](https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata) you can find the configuring part. Run the plugins as the netdata user and see why they fail.

**Comment by XGhozt00** [comment]
Ahh, thanks @cloudz -- I'll setup the config(s).
