### ISSUE TITLE
Defining more than one script for alarms and escalations

### ISSUE THREAD

**Issue by geekhead** [firehol/netdata#3651]
@ktsaou Can you define more than one script in the `exec` line? Also, I see a huge benefit in having the capability to define a custom script that is run when the alarm is first triggered, then runs a second script (aka alarm-notify.sh) if the alarm is still in a warn/critical state after a configurable period of time. 

Basic example of this would be a disk space issue where you want to try to fix the issue first before sending a page off. So lets say you create a script that purges or compresses some known large log files and you want netdata to run that script first when a low disk space alarm is generated. If the alarm clears within a certain period of time than netdata doesn't proceed with running the alarm-notify.sh script and anyone on-call can sleep a little longer 😃. However, if our custom script for whatever reason didn't do it's job and the alarm still hasn't been cleared, then escalate and run the alarm-notify.sh script which will send out a page and other forms of communication defined. 

So you're creating a kind of escalation process using custom scripts but this allows us to be smarter about resolving these alerts before actually paging a human being and creating alert fatigue. You can get even more complex by specifying in the `exec` line an ansible playbook command or curl a rundeck api command to try to auto resolve alerts before running the alert-notify.sh command. 

I just know alert fatigue is a very real thing and having the ability to fix issues automatically before paging humans will go a long way in creating a more dynamic, self healing infrastructure.

**Comment by Ferroin** [comment]
I may be wrong about this, but I'm pretty sure you can only define one script.

However, it's not hard to write a wrapper that would do what you are asking for.  It's trivial to call a script from another script and pass on the exact argument list.  For reference, with most POSIX compliant shells (including bash), you can do this:

    /path/to/script $@

To run another script with the same arguments you were given.

**Comment by geekhead** [comment]
@Ferroin Yup definitely know you can do that in a wrapper but it's a little more involved now as you need to constantly be checking for alarm status conditions by forking api calls to see if anything has changed, checking for errors, etc before proceeding so not as clean but definitely an option. If building something like this isn't on a roadmap then maybe I'll find the time to build this out via a script. Thanks

**Comment by Ferroin** [comment]
Had you considered having the script cache the alarm state?  There's nothing that says you can't write to disk from the script, so each time you see an alarm you could just write out what state it's in (because that is part of what the script gets passed by Netdata when invoked), and compare against that next time you see it.  That would avoid having to make the Netdata API calls, and if you put that on a `tmpfs` mount or ramdisk, it would probably be far faster than the API calls too.

**Comment by ktsaou** [comment]
netdata supports one script per alarm, but each alarm can have its own script.

`alarm-notify.sh` itself allows script hooks via the `custom` delivery method. You can do this role based too (ie. define "fake" recipients for the custom delivery method for each role and handle differently each "fake" recipient at the script).

Each alarm also support hysteresis - a delay, for both rising and falling conditions (`delay: up 1m down 10m multiplier 1.5 max 1h`) - so they are a bit adaptive.

What I think is missing from netdata alarms is something like `repeat: 5m` so that the alarm notification will be repeated every 5 minutes. This is to ensure the on-call guys will wake up eventually :)

So, are the above sufficient for what you want to do?

**Comment by geekhead** [comment]
@ktsaou Yeah I can make that work for what I might need. Thanks!

**Comment by ktsaou** [comment]
ok, nice!
