### ISSUE TITLE
When listening on a unix socket, web server still attempts to set TCP_NODELAY.

### ISSUE THREAD

**Issue by declaresub** [firehol/netdata#3682]
When listening on a unix socket, web server still attempts to set TCP_NODELAY, resulting in error 95.  The problem is that the log fills up with error messages until a message threshold is triggered.

**Comment by Ferroin** [comment]
I can confirm this, and agree that it's rather irritating.  I'm personally of the opinion that the message probably shouldn't be an error message, but a debug message (things do still work if we fail to set this flag, it's just that there will be some more latency in the dashboard), though that would just move the log spam instead of getting rid of it.

For whoever ends up looking into this, the issue is that [`web_client_initialize_connection()`](https://github.com/firehol/netdata/blob/bcdb03ccc2cbedc155d790390c6d08a595917742/src/web_server.c#L336) in `web_server.c` is unconditionally trying to set `TCP_NODELAY`, without checking the socket type first.  I would try to fix this myself, but I'm not all that comfortable poking around there given that I don't have much experience with C (I know enough to read it, just not enough to confidently write it).

**Comment by ktsaou** [comment]
In PR #3691 
Thank you for reporting it!
