### ISSUE TITLE
How set netdata to start at boot on Mac Os?

### ISSUE THREAD

**Issue by directionsystems** [firehol/netdata#3684]
How set  netdata to start at boot on Mac Os?

**Comment by ktsaou** [comment]
hm... I don't know.
If anyone knows how to make init script on MacOS, please help...

**Comment by LucasjHall** [comment]
Best bet would be a LaunchDaemon ([Apple Dev Docs](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html)) setup to launch/keep netdata running. 

If you installed via the netdata [macos install docs](https://github.com/firehol/netdata/wiki/Installation#macos) you've installed netdata into a user space, `~/opt`. For sake of this use case we will start from a clean instal... 

Rather than installing to `~/opt`, installing inside your user directory, you could install to `/usr/local/` or another supported directory [See Apple's SIP Docs](https://support.apple.com/en-us/HT204899), so modified instructions would be:

```
# install netdata in ~/opt/netdata
cd netdata
sudo ./netdata-installer.sh --install ~/usr/local
```
Before moving on, you can just kill netat `sudo killall netdata`

This allows for two things, 1) the creation of a LaunchDaemon outside of the restrictions of a user, 2) ability for the app to run as root. 

A LaunchDaemon, com.github.netdata.plist, could look like this: 
 
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.github.netdata</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/local/netdata/usr/sbin/netdata</string>
    </array>
    <key>KeepAlive</key>
    <true/>
</dict>
</plist>
```

Move that `.plist` to `/Library/LaunchDaemons/com.github.netdata.plist` 
Then update your `launchtl` by loading via `sudo launchctl load /Library/LaunchDaemons/com.github.netdata.plist` 

At this point netdata should be running, and should start up on boot without the need for a user to be logged into the host. 

I hope this helps!

[Daemons and Services Programming Guide | Apple Developer](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html)   
[About System Integrity Protection on your Mac | Apple KB](https://support.apple.com/en-us/HT204899)

**Comment by ktsaou** [comment]
Thank you @lucasjhall !
In PR #3694 your suggestions implemented in netdata. I tested it and it seems to work.

Is there a MacOS way to start/stop the service?

**Comment by ktsaou** [comment]
merged it.

**Comment by ktsaou** [comment]
I also changed the installation wiki page to reflect the changes.
