### ISSUE TITLE
Use bash loadable sleep in tc-qos-helper.sh

### ISSUE THREAD

**Issue by lllusion3469** [firehol/netdata#3754]
Since sleep is not an builtin in bash by default, every (by default) 1 seconds a new process is spawned only to sleep a single second.

One way to improve this would be "bash loadables", which would make `sleep` a builtin,  offered by some distributions:
* in Arch Linux they're included by default with bash
* in Debian they're in an package called [`bash-builtins`](https://packages.debian.org/stretch/bash-builtins)
* in opensuse [`bash-loadables`](https://software.opensuse.org/package/bash-loadables)
* etc. (not sure about fedora)

They're either in `/usr/lib/bash/` (AL,DEB), `/lib/bash`, `/lib64/bash/` (SUSE) (probably symlinked to `/usr/lib/` anyways) apparently and would be loaded using e.g. `enable -f /usr/lib/bash/sleep sleep` and then used how you would usually use sleep.

This is both faster and more precise ([which seems to be important](https://github.com/firehol/netdata/blob/master/plugins.d/tc-qos-helper.sh#L167)).
It is also less annoying when using `execsnoop`, if you're into that (or even htop for that matter).

([some general information about loadables](https://web.archive.org/web/20101127062525/http://cfajohnson.com/shell/articles/dynamically-loadable/))

I would write a pull request but I'm not sure about two things:
* how to specify the location (overridable in `tc-qos-helper.conf`? environment variable?)
* what about the planned CLA? would this even be copyrightable?

e: they were introduced first with bash 2.0 [source](https://www.safaribooksonline.com/library/view/learning-the-bash/0596009658/apc.html)
e2: it might only have taken integer seconds in the past, but doesn't now [source](https://github.com/bminor/bash/blob/master/examples/loadables/sleep.c#L99)
e3: apparently always fractional seconds since bash 2.0 [source](https://github.com/bminor/bash/blame/master/examples/loadables/sleep.c#L99)

**Comment by ktsaou** [comment]
hi,

nice info. I was not aware of this.

all netdata bash scripts use `loopsleep()` defined in https://github.com/firehol/netdata/blob/master/plugins.d/loopsleepms.sh.inc

This file provides a few alternatives for reading time and sleeping.

netdata shell scripts by default sleep with `read -t TIMEOUT`. Only when this fails, they fallback to calling `sleep`.

On which distro you saw the qos helper to run `sleep`?

In PR #3755 support for bash loadable module for sleep.

> what about the planned CLA? would this even be copyrightable?

Of course it will. Your code is your code. What we are trying to do is provide some legal shield for all the contributors and some legal flexibility to the project. So, the code you submit will be yours to do whatever you like with it, your name will be there, visible, but your submissions will also be owned by netdata, so that netdata can be considered "one thing" under a common license, managed by the project alone. This does not remove your rights to do whatever you like with your code. It just allows netdata to do it too.

**Comment by lllusion3469** [comment]
I'm using the one in the Arch Linux repository: community/netdata 1.10.0-1

```sh
$ locate 'loopsleepms.sh.inc'
/usr/lib/netdata/plugins.d/loopsleepms.sh.inc
```
![image](https://user-images.githubusercontent.com/31420484/40575959-15358226-60ef-11e8-9819-f1ae384a7ce7.png)

And regarding the CLA: I only meant because I thought it would be [a fairly minimal change](https://en.wikipedia.org/wiki/Threshold_of_originality)

**Comment by ktsaou** [comment]
I did a few changes to incorporate the serverfault answer.
but still, I am not sure.

**Comment by lllusion3469** [comment]
* There's nothing in particular wrong with your pull request, I just found out about `pkg-config bash --variable=loadablesdir` and `BASH_LOADABLES_PATH`
* I really don't get atm how `/var/cache/netdata/.netdata_bash_sleep_timer_fifo` ends up a regular file.
* I didn't notice you were (trying to use) using `read -t` before making this issue
* I don't think there's much of an point to using the loadable if `read -t` worked

**Comment by ktsaou** [comment]
So, your `/var/cache/netdata/.netdata_bash_sleep_timer_fifo` is a regular file?
This is really weird...

The only problem I have with the PR is how this will interfere with static netdata installations. The static bash v4 compiled by us on alpine will attempt to use the dynamic sleep module of another version of bash... It seems scary...

**Comment by ktsaou** [comment]
I could possible check if `/var/cache/netdata/.netdata_bash_sleep_timer_fifo` is a normal file and move it.

**Comment by lllusion3469** [comment]
I just did ```bash
[netdata@pc]$ rm rm /var/cache/netdata/.netdata_bash_sleep_timer_fifo
# systemctl restart netdata
```
and now it's a fifo and everything works.

trying a restart...

**Comment by ktsaou** [comment]
updated the PR to reflect all findings so far. I think it is ok now.

I searched to history of this file to see if we had a commit with `touch` instead of `mkfifo`. I couldn't find any. So, I can't really tell how you ended up with a normal file there.

Anyway, I added a protection for that too. If the file is a regular file, it is removed and the fifo is recreated.

**Comment by ktsaou** [comment]
Also, now `read` is preferred over `builtin sleep`. This makes it less risky for static builds. So, I think we can merge it.

What do you think?

**Comment by lllusion3469** [comment]
I don't think it can happen anymore, but it seems in the past there was a way for `read -t "${1}" <>"${mysleep_fifo}"` when `${mysleep_fifo}` had just been deleted. This would have caused the shell to create an empty regular file in its place, as you can confirm when running `read -t 5 <> /tmp/foobar` or any nonexistent file.

Your PR seems good and way more rigorous than what I would have done initially

**Comment by lllusion3469** [comment]
oops, I thank was a bit hasty, you'd still have to merge at least the part where you delete it when it's not a regular file

**Comment by ktsaou** [comment]
I think I will merge it as is now (with `builtin sleep` as the second option).
It seems pretty ok to me now.

**Comment by ktsaou** [comment]
merged it.
thank you for reporting it.
