### ISSUE TITLE
Domain Bandwidth Monitor & Services API

### ISSUE THREAD

**Issue by sagargulati** [firehol/netdata#3756]
Would it be more awesome if we can check the status of the total bandwidth used in GB/MB/KB and all?
Apart from that a feature that shows the bandwidth used by **EACH DOMAIN** or application using Nginx or Apache?

Also, what if there is an API that can restart Nginx or Apache or other services on the server.

Thanks!

**Comment by ktsaou** [comment]
Can you explain your setup a bit?

Generally you can monitor the total bandwidth of a port, using FireQoS. netdata provides amazing real-time charts for this. FireQoS allows you to setup classes for any kind of traffic, so this kind of monitoring provides a universal way of monitoring traffic.

To monitor bandwidth per web server domain, we need the cooperation of the web server. This can be achieved today with web_log plugin. If your web server has one log file for each domain, you can configure web_log for all your domains and you will get one full web_log section for each of them.

If all your domains share the same web server log, it can still be done, but it will be tricky, and will not be efficient until we implement #3111 

---

> what if there is an API that can restart Nginx or Apache or other services on the server.

Currently netdata is read-only. It does not alter the system in any way. To support something like this a lot have to be implemented before it.

**Comment by sagargulati** [comment]
Netdata is really awesome however like you said we can monitor bandwidth per domain by using web_log that requires each access log file. But what we have done is we DO NOT use access logs since a large website which have access logs turned ON will slow it down since the process has to write a lot of logs, so to increase the performance, we don't use access logs!
So it there any other way to track the bandwidth each domain?

Explaining it more, we want a system where the users we have on our server should be able to see the bandwidth used by their every domain in their control panel and can upgrade their hosting packages accordingly.

I get about the API part, but do you have something in similar (not netdata) that could help the same way?

**Comment by ktsaou** [comment]
hm... I don't think you can get what you want without a cooperation from the web server.

You have the following options:

1. Enable web server logs and use web_log. This will slow the web server down, only if you have multiple thousand of requests per second.
2. Use a web server that exposes metrics per domain without logs (I don't know any).
3. Build a network of web servers probably with containers on the same host. The web server at the host will be just forwarding everything to a backend web server (one per domain, or one per customer of yours, etc). With this setup you can monitor the host web server and each of the containerized web servers, without log files.

I can't think of any other solution.

> Also for monitoring the total bandwidth, we use vnstat as of now which does the similar task like FireQoS. Right?

No. FireQoS classifies traffic using rules. So you can say that all traffic on eth0 from/to your port tcp/80 and tcp/443 are `web`, while traffic from/to your port udp/53 is `dns`, from/to your port 22 is `ssh`, etc. Then with FireQoS you can limit them (ie. ssh will never get more than 1Mbps) - although limiting is optional. FireQoS can also improve your users experience by favoring new connections over older ones (so that when you have users downloading huge files, other users browsing the site will be snapier). 

Generally, with QoS you can do exotic things.. I strongly suggest to learn it.

netdata will pickup the FireQoS classes (`web`, `dns`, `ssh`) and show the traffic/packets in/out for each class. All the netdata demo sites run QoS. Their config is there: https://github.com/firehol/netdata-demo-site/blob/master/files/etc/firehol/fireqos.conf and you can see the result in netdata here: http://london.my-netdata.io/#menu_tc_submenu_eth0

> I get about the API part, but do you have something in similar (not netdata) that could help the same way?

Sorry... I just use ssh for that... I wouldn't do anything else, especialy on a busy server.

**Comment by sagargulati** [comment]
Great, thank you so much, I'll close this for now and re-open when required to meet the needs.

**Comment by startryst** [comment]
I'm another use of vnstat, just try to bring this topic back again to see if it's possible to add vnstat to netdata?
