### ISSUE TITLE
Unit detection and adaption

### ISSUE THREAD

**Issue by Night1** [firehol/netdata#376]
Hey, is there away to have netdata adapt to units?, so that thresholds for disk/network utilization adapt  to MB/s or even GB/s, 

The maths for it are quickly done in one head so not a pressing need, but it would still be a "nice to have"  feature. 
![111212](https://cloud.githubusercontent.com/assets/9394448/15050601/fee80f24-12f4-11e6-8b0a-a6291769bde3.png)

**Comment by ktsaou** [comment]
Well, this would require for netdata to know what type of data is collecting. Unfortunately it does not know.

Currently the only way to achieve this, is to change the `divisor` and the `units` in `netdata.conf`. However, you will have to do this for all charts and dimension you want to change.

In future versions, the data collectors could report the type of data they collect, so that netdata can adapt them at the presentation layer.

Generally, I have tried to have all charts in these units:

- network bandwidth: kilobits/s
- I/O: kilobytes/s
- memory: MB

I'll mark this as enhancement. We should have a way to adapt these easily.

**Comment by Night1** [comment]
I agree, that is not an quick fix for netdata to know datatype,,  I did notice that space get limited in interface  charts in 1,000,000+.

**Comment by ktsaou** [comment]
A quick hack could be to check for the string of the units. If it is `kilobits/s`, `kilobytes/s` or `MB` then netdata could convert the values and the unit string to something else. But I think this is a hack. I don't like it. Let me think...

**Comment by ktsaou** [comment]
> I did notice that space get limited in interface charts in 1,000,000+.

Can you give a screenshot? Normally, the value will go on top of the dimension name.

**Comment by Night1** [comment]
Never mind it was a zoom issue, when having zoomed in on my phone, on dektop/laptop it still looks great, 
![Uploading Untitled.png…]()

**Comment by ktsaou** [comment]
I have moved all the unit conversion requests to #2745 
So, let's continue this discussion there.
