### ISSUE TITLE
New at netdata and a lot of alarms

### ISSUE THREAD

**Issue by chaosm** [firehol/netdata#3826]
Hi, I'm new on vps and I try to solve many problems.

At nedata i had many events (about 400).
Due to this 
```
# sysctl settings are defined through files in
# /usr/lib/sysctl.d/, /run/sysctl.d/, and /etc/sysctl.d/.
#
# Vendors settings live in /usr/lib/sysctl.d/.
# To override a whole file, create a new file with the same in
# /etc/sysctl.d/ and put new settings there. To override
# only specific settings, add a file with a lexically later
# name in /etc/sysctl.d/ and put new settings there.
#
# For more information, see sysctl.conf(5) and sysctl.d(5).

# Minimizing the amount of swapping
vm.swappiness = 20
vm.dirty_ratio = 80
vm.dirty_background_ratio = 5

# Increases the size of file handles and inode cache & restricts core dumps
fs.file-max = 2097152
fs.suid_dumpable = 0

# Change the amount of incoming connections and incoming connections backlog
net.core.somaxconn = 65535
net.core.netdev_max_backlog = 262144

# Increase the maximum amount of memory buffers
net.core.optmem_max = 25165824

# Increase the default and maximum send/receive buffers
net.core.rmem_default = 31457280
net.core.rmem_max = 67108864
net.core.wmem_default = 31457280
net.core.wmen_max = 67108864

# Enable TCP SYN cookie protection
net.ipv4.tcp_syncookies = 1

# Enable IP spoofing protection
net.ipv4.conf.all.rp_filter = 1

# Enable ignoring to ICMP requests and broadcasts request
net.ipv4.icmp_echo_ignore_all = 1
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Enable logging of spoofed packets, source routed packets and redirect packets
net.ipv4.conf.all.log_martians = 1

# Disable IP source routing
net.ipv4.conf.all.accept_source_route = 0

# Disable ICMP redirect acceptance
net.ipv4.conf.all.accept_redirects = 0
```

i lowered the events at about 40-60

and sometimes pick to 150 

![capture1](https://user-images.githubusercontent.com/15524785/41415267-dc576ec2-6ff0-11e8-99bf-4c1d9d3fa0f4.JPG)

I tried many solutions but nothing works better than these settings.
My main problem is these ipv4 drops

![capture](https://user-images.githubusercontent.com/15524785/41415325-024d14c4-6ff1-11e8-9344-f4fa6538299c.JPG)

My vps is a machine with 12core 124gb ram and 250gb ssd running on centos 7.5

Is something more i have to do?

**Comment by l2isbad** [comment]
> 12core 124gb ram and 250gb ssd running on centos 7.5

great vm btw (except centos :smile: )

**Comment by Ferroin** [comment]
The net_fifo errors are most likely issues with either the network drivers in the VM, or the emulated networking hardware provided by the hypervisor.  I don't know enough about the setup to comment any further than that (it kind of depends on what hypervisor is being used, and what network hardware is being emulated).

The TCP listen drops are a lot harder to pin down a cause for.  They _might_ be a symptom of the net_fifo issues, but it's had to be certain until those are fixed.  That said, I get a small handful on a semi-regular basis on my two VPS nodes (generally fewer than 10 a day, usually spread out evenly throughout the day), and have had no actual issues.  If you aren't seeing any actual issues with whatever applications you are running, then you can probably safely ignore these, in which case you can edit the alarm definition in `/etc/netdata/health.d` to have a higher threshold before the alarm triggers.

The softnet issue is a tricky one.  The alarm fires regularly on almost any otherwise sanely configured system that's seeing lots of network traffic.  While the alarm description is correct that it can be a cause for dropped packets, the point at which it becomes a _likely_ cause of dropped packets is dependent on the system itself.  With that many cores, you're probably looking at needing _thousands_ of events to see any packet drops actually caused by what it's monitoring.  Realistically, you can probably safely bump the trigger point for this one up to at least 500 (unless those spikes over 150 happen to correlate with the TCP listen drops or net_fifo errors, in which case you may have other issues you need to look into).

**Comment by chaosm** [comment]
@Ferroin thanks for your reply.
Is it possible to give the code that i have to add at health.d  to have a higher threshold before the alarm triggers?

Thanks

**Comment by l2isbad** [comment]
[tcp listen drops thread](https://github.com/firehol/netdata/issues/3234)

**Comment by Ferroin** [comment]
For the TCP listen drops, the file should be `/etc/netdata/health.d/tcp_listen.conf`.  That will have two alarm definitions in it, in the second one there's a line that reads `crit: $this > 0` which is what sets the trigger condition.  In your case, I'd suggest doing as I have and updating the line to `crit: $this > 1`, which will require 2 or more drops in a 10 minute interval to trigger the alarm (which should still trigger on DoS attacks such as that mentioned in the thread @l2isbad linked, but won't trigger for single events).

For the softnet stuff, the file should be: `/etc/netdata/health.d/softnet.conf`.  That one will have three alarm definitions in it, with the relevant one here being the second one.  The line that sets the trigger for this is `warn: $this > (($status >= WARNING) ? (0) : (10))`.  This one uses hysteresis to slow down the reset of the alarm.  The first number in parenthesis is what the alarm has to go down to to reset once it's triggered, given that you say you usually see values around 60-80, I'd suggest setting this to somewhere around that (80 should be fine).  The second number in parenthesis is the value the alarm has to exceed to trigger an alert, and in your case I'd say 200 is probably reasonable (that gives you some excess space above your typical max without being insanely high).

The wiki has a very good description of the expected format for defining alarms [here](https://github.com/firehol/netdata/wiki/health-configuration-reference), and some good examples based on actual alarms that ship with netdata [here](https://github.com/firehol/netdata/wiki/health-configuration-examples).  If you have some interest in further customizing the alarms that netdata provides, or even writing your own, they're both worth reading.

**Comment by ktsaou** [comment]
@chaosm for softnet budget run outs, please change `net.core.netdev_budget_usecs`. I managed to stop this issue by setting this to `5000`. This setting exists only on newer kernels. On older kernels you can't do anything - so increase the threshold.

Listen drops are bad. It means that packets sent to one of your application servers running on this machine, are dropped. It has nothing to do with layer 2 or 3 networking - this is purely an application issue (the listening application cannot handle the rate of received packet). Check also the #3234 (as @l2isbad suggested).

**Comment by Ferroin** [comment]
Listen drops can also mean a malformed layer 4 packet though.  That doesn't have anything to do with the application itself, it's just a bad packet coming in.  That's what 99% of the ones I've seen on my VPS nodes are.

For that specific case, adding the following rules to your firewall may help (and is generally good practices anyway):

    iptables -A INPUT -m conntrack --ctstate INVALID -j DROP
    iptables -A INPUT -m tcp -p tcp ! --tcp-flags FIN,SYN,RST,ACK SYN -m conntrack --ctstate NEW -j DROP

The firs one will drop packets the kernel considers completely bogus (they would be dropped anyway, but this way they won't bother your error counters), and the second one blocks TCP packets not associated with an existing connection that aren't trying to establish a new connection.  You can add the same rules through `ip6tables` too.

**Comment by ktsaou** [comment]
As always, @Ferroin is right...

**Comment by chaosm** [comment]
Hi im back
I tried all kernel tcp tunning settings i found on internet,

I had many errors and ipv4 drops

I delete everything and let the server stock (even somaxcon)

Now i have about 160 to 300 events of 10min netdev budget ran outs
and not all the time.

im on centos 7.5 with 3.10.0-862.3.3.el7.x86_64 kernel

**Comment by ktsaou** [comment]
> @chaosm for softnet budget run outs, please change net.core.netdev_budget_usecs. I managed to stop this issue by setting this to 5000. This setting exists only on newer kernels. On older kernels you can't do anything - so increase the threshold.

Did you try the above?

**Comment by ktsaou** [comment]
@Ferroin I checked again the `1m_ipv4_tcp_listen_drops` alarm. Since this may include bogus packets, I think the alarm is too strict.

I can think of 2 solutions:

1. increase the threshold (e.g. ` > 10 packets/min`)
2. make it adaptive (e.g. trigger an alarm if the rate of the last minute doubled compared to the previous minute)

What do you think?

**Comment by ktsaou** [comment]
or even this:

```
    warn: $this > 0
    crit: $this > (($status == $CRITICAL) ? (0) : (60))
```

So, warning when there is at least a packet, and critical if there are 60/min.

**Comment by Ferroin** [comment]
In my case, I've literally just bumped the alarm threshold to require more than one every ten minutes to trigger.  I see an alarm maybe once every few days from it now, instead of about a dozen times a day (and when I do see one, it's usually just a second packet in that 10 minute period).  However, the primary usage of the systems in question is as ntp.org pool members, so YMMV for things like web servers.

I think it probably makes sense to bump the warning level to trigger on at least 2 in the past 10 minutes, and additionally have a critical level that triggers on the equivalent 2-3 every minute (that will catch moderately aggressive network probes that are designed to bypass certain types of firewall, as well as DoS attacks).  Adding a bit of documentation in with the alarm explaining it a bit further might be good too.

**Comment by spirogg** [comment]
@ktsaou 

I still get these emails 10-20 A DAY ?

what is the final fix raise number ?
or add 
```
 # iptables -A INPUT -p icmp -m icmp --icmp-type 3/4 -m conntrack --ctstate NEW -j ACCEPT
# iptables -A INPUT -p icmp -m icmp --icmp-type 3 -j DROP
```

**Comment by Ferroin** [comment]
For what it's worth, the iptables stuff _should_ be safe unless you're doing some really weird stuff with firewall hole-punching.  If it fixes things, you should see the effects in about 10 minutes (the dropped-packet alarms all do 10-minute averages).

Whether you choose to go with the iptables stuff (keep in mind that that also provides some rudimentary protection against certain types of exploits against the system's networking stack) or just bumping up the alarm numbers is up to you.  I'd start with the iptables stuff first (just don't forget to add the same rules to both IPv4 _and_ IPv6, the only differences for the ones I posted should be changing `iptables` to `ip6tables`), and if that doesn't help, then start looking at bumping up the alarm threshold.

**Comment by spirogg** [comment]
@Ferroin. Thank you, 
I will add iptable  and then hopefully the issue is resolved. If not will try to up the alarm.threshold. 
Will report back either way if it works or not.
