### ISSUE TITLE
NUT ups names

### ISSUE THREAD

**Issue by kmlucy** [firehol/netdata#3829]
I need to enter my NUT ups name's as FQDNs, so the charts are rather messy: ``UPS <ups name> <server name> <domain> com``. Is there a way to have the ups name for upsc be separate from the display name?

**Comment by ktsaou** [comment]
hm... not out of the box, but we could evolve the script a bit.

It is here: https://github.com/firehol/netdata/blob/master/charts.d/nut.chart.sh

I think we need to define a new variable here: https://github.com/firehol/netdata/blob/47f1dd0d2f568bd3a1f4ced7657fc84f27cb5c70/charts.d/nut.chart.sh#L26

```sh
declare -A nut_names=()
```

The above variable could also be set that the nut config file `/etc/netdata/charts.d/nut.conf`, like this:

```bash
nut_names["FQDN1"]="alias"
nut_names["FQDN2"]="alias"
```

Then, we will need to change this line: https://github.com/firehol/netdata/blob/47f1dd0d2f568bd3a1f4ced7657fc84f27cb5c70/charts.d/nut.chart.sh#L59

to be:

```sh
if [ ! -z "${nut_names[${x}]}" ]
then
   nut_ids[$x]="$( fixid "${nut_names[${x}]}" )"
else
  nut_ids[$x]="$( fixid "$x" )"
fi
```

So, if there is an alias defined use it, otherwise do what we did before.

Can you make these 2 changes and try it? If it works I'll make a PR.
Or you can make a PR... your call...

**Comment by kmlucy** [comment]
The changes you suggested work perfectly for me. I submitted a PR.
