### ISSUE TITLE
Disable or restrict access to the default dashboards

### ISSUE THREAD

**Issue by armandas** [firehol/netdata#3849]
I wrote a custom dashboard for my server and would like that to be the only dashboard accessible. I initially tried moving all the default html files to an archive, but after an update, they were restored.

What would be the best way to get my custom dashboard loaded by default (as index.html) and prevent users from accessing any other dashboards?

**Comment by ktsaou** [comment]
Well, there is no meaning for this.

The dashboard is acutally a set of static html, javascript and css files. The netdata web server is primarily used for its API, which you can't restrict it since your custom dashboard needs it.

To understand the issue, consider this:

You can use the static html, js, css files of one netdata, while accessing the API of another, like this:

http://server1:19999/#;server=http://server2:19999/

With the above, your browser will load all the static files from server1, but the actual data of the dashboard will come from server2 !

Real-life example:

This shows the newyork netdata demo site:

https://newyork.my-netdata.io

But this shows the toronto netdata site (with the static files of newyork):

https://newyork.my-netdata.io/#;server=https://toronto.my-netdata.io/

You will also get a nice XSS warning by netdata:

![image](https://user-images.githubusercontent.com/2662304/41750636-b0bec406-75c5-11e8-95c3-a03babbe6388.png)

**Comment by armandas** [comment]
@ktsaou Thank you for the answer. Is it at least possible to make my custom dashboard to be loaded by default (as index.html)?

I tried adding the following line to the [web] section in the config, but it did not work.

`custom index.html = my_page.html`

**Comment by ktsaou** [comment]
hm... it will be overwritten at the next update if you replace index.html.

But you can host your custom dashboard on any web server. So, if you run another web server, just host it there and load dashboard.js from the full netdata URL.

**Comment by armandas** [comment]
OK, thank you for your support.
