### ISSUE TITLE
open files on mount point - rclone

### ISSUE THREAD

**Issue by animosity22** [firehol/netdata#3862]
I was trying to use netdata to capture open files on my rclone fuse mount.

I have a couple files open as an example:

felix@gemini:~$ sudo lsof /gmedia
COMMAND    PID USER   FD   TYPE DEVICE    SIZE/OFF                NODE NAME
Plex\x20M 2786 plex   85r   REG   0,54   268243985 6052180743453071958 /gmedia/TV/Zoey.101/Zoey.101.S01E12.mkv
Plex\x20M 2786 plex   94r   REG   0,54 12887580147 6703476971467156836 /gmedia/Movies/X-Men.First.Class.2011.mp4

I was hoping to graph/count/keep that there are 2 open files on that mount.

Is there something that's doable on a fuse mount that I'm missing?

**Comment by ktsaou** [comment]
Hi,

unfortunately does not support this with any of the existing plugins. apps.plugin reports number of open files per process, but no plugin reports number of open files per mount point.

You can of course write a simple bash shell script to do it. You can duplicate this file and adapt it to your needs: https://github.com/firehol/netdata/blob/master/charts.d/example.chart.sh

Remember to increase `update_every` of the plugin, since running `lsof` every second will be heavy.

It is pretty simple to do:

1. copy it as `mountlsof.chart.sh`
2. replace all occurencies of `example_` with `mountlsof_`
3. adapt `mountlsof_get()` to find the number of files open for the mount point
4. make `mountlsof_check()` to always `return 0`
5. adapt `mountlsof_create()` to create the chart the way you like it
6. adapt `mountlsof_update()` to update the right values for the chart you created
7. copy it to `/usr/share/netdata/charts.d/`
8. restart netdata

Full documentation for the `CHART`  lines is here: https://github.com/firehol/netdata/wiki/External-Plugins#chart

**Comment by animosity22** [comment]
I think I'm close, but missing something.

I didn't have a /usr/share/netdata/charts.d so I created that and dropped the file in and I'm assuming I'm missing something very easy as I was trying to model it after the example but not a strong coder.

```
root@gemini:/usr/share/netdata/charts.d# cat mountlsof.chart.sh
# no need for shebang - this file is loaded from charts.d.plugin
# SPDX-License-Identifier: GPL-3.0+

# netdata
# real-time performance and health monitoring, done right!
# (C) 2016 Costa Tsaousis <costa@tsaousis.gr>
#

# if this chart is called X.chart.sh, then all functions and global variables
# must start with X_

# _update_every is a special variable - it holds the number of seconds
# between the calls of the _update() function
mountlsof_update_every=30

# the priority is used to sort the charts on the dashboard
# 1 = the first chart
mountlsof_priority=150000

# global variables to store our collected data
# remember: they need to start with the module name mountlsof_
mountlsof_value=0

mountlsof_get() {
	# do all the work to collect / calculate the values
	# for each dimension
	#
	# Remember:
	# 1. KEEP IT SIMPLE AND SHORT
	# 2. AVOID FORKS (avoid piping commands)
	# 3. AVOID CALLING TOO MANY EXTERNAL PROGRAMS
	# 4. USE LOCAL VARIABLES (global variables may overlap with other modules)

	mountlsof_value=`/usr/bin/lsof /gmedia | wc -l`

	# this should return:
	#  - 0 to send the data to netdata
	#  - 1 to report a failure to collect the data

	return 0
}

# _check is called once, to find out if this chart should be enabled or not
mountlsof_check() {
	# this should return:
	#  - 0 to enable the chart
	#  - 1 to disable the chart

	return 0
}

# _create is called once, to create the charts
mountlsof_create() {
	# create the chart with 3 dimensions
	cat <<EOF
CHART system.rclone '' "/gmedia open files" "open files" openfiles openfiles area $((mountlsof_priority + 1)) $mountlsof_update_every
DIMENSION openfiles '' absolute 1 1
EOF

	return 0
}

# _update is called continuously, to collect the values
mountlsof_update() {
	# the first argument to this function is the microseconds since last update
	# pass this parameter to the BEGIN statement (see bellow).

	mountlsof_get || return 1

	# write the result of the work.
	cat <<VALUESEOF
BEGIN system.rclone $1
SET openfiles = $mountlsof_value
END
VALUESEOF

	return 0
}
```

Something simple I'm missing?

**Comment by ktsaou** [comment]
> /usr/share/netdata/charts.d

my bad: `/usr/libexec/netdata/charts.d` I meant.

**Comment by ktsaou** [comment]
You can test it with:

```sh
/usr/libexec/netdata/plugins.d/charts.d.plugin debug 1 mountlsof
```

You may also need to `sudo` the lsof command. netdata runs unprivileged...

**Comment by animosity22** [comment]
Yep. I added in a sudo line for:

netdata ALL=NOPASSWD:/usr/bin/lsof

and working like a champ. Much appreciated for the quick and easy explanation!

**Comment by animosity22** [comment]
Just in case anyone finds this, I did add a grep to get out the first header row as it was returning one extra all the time :)

```
	mountlsof_value=`/usr/bin/sudo /usr/bin/lsof /gmedia | grep -v COMMAND |  wc -l`

```
