### ISSUE TITLE
After netdata slave is rebooted, timestamp doesn't match

### ISSUE THREAD

**Issue by nathan-liyiming** [firehol/netdata#3966]
After I rebooted the slave box (taking 10 minutes, it still uses the same UUID), I find the metrics didn't match the current time. It just appended the data points without syncing the time. It should be 00:46 not 00:36, which had 10 mins delay. 

<img width="428" alt="screen shot 2018-07-15 at 12 45 50 am" src="https://user-images.githubusercontent.com/3344975/42731749-a5fcc7d8-87c8-11e8-9c40-e5d6d2c32764.png">

The interest thing is that after about 35 mins, timestamp was synced and there was one gap.

<img width="413" alt="screen shot 2018-07-15 at 12 51 30 am" src="https://user-images.githubusercontent.com/3344975/42731796-a21a8c3a-87c9-11e8-9b33-f90a3880902a.png">

Is it a bug? I assume in the data point, it has timestamp information and it should have one gap at the beginning of starting the machine not until 30 minutes later.

**Comment by ktsaou** [comment]
hm... does this happen on all charts or just this one?

**Comment by nathan-liyiming** [comment]
Yeah, happened for all charts. I have tried several times to reboot the machine or reuse one UUID to replay it. It always has some delay. Then, after ~30 mins, the time is synced and there is one gap.

**Comment by ktsaou** [comment]
hm... I can't reproduce this, but I noticed that timings are not aligned either across all charts. So, somehow, charts are getting wrong time under conditions.

So, I mark this as bug to investigate further.

Thank you for reporting it!

**Comment by Ferroin** [comment]
I don't know if this might be relevant here, but I've noticed that for the Python plugins specifically, the plugins often get out of sync in terms of timing if there are consistent unusually long delays in retrieving values.  I've had that happen a number of times when testing plugins that I've written, especially when testing how they handle reconnecting to whatever service the3y are monitoring.

**Comment by ktsaou** [comment]
This is a different case and I think I know why this happens.
The problem is that the slave protocol syncs the time for the first few seconds after a connection and then all charts are assumed to be in sync.

Unfortunately this is not the case, especially due to ephemeral charts, etc. So, if a chart is added after the first few seconds the clock is synced, the master believes the time just continues from where is was last updated, resulting in wrong clock.

In @nathan-liyiming case this is somehow triggered on reboot. I can't reproduce it, but I can reproduce the charts going off time, if I start a container at a slave, stop it after a few minutes, restart the slave (to reconnect to netdata), wait a few minutes (to pass over time sync period), start the same container again at the slave. In that case, the container charts at the master have wrong time.

So, the solution is for the slave to push the exact timestamp of the last collection every time it pushes the chart (and of course the master to use it).

For the moment, I am trying to decide if this should be done for plugins too. It is not relevant to the time lag we experience in a few case for python plugin. I think the problem there is related to the clock used by python.d.

**Comment by ktsaou** [comment]
edited the response above, so please read it on github.

**Comment by nathan-liyiming** [comment]
Thanks @ktsaou for this quick response. For the reboot, I mean the netdata is stopped for about 10 mins before reboot because the machine needs to stop several services (take a long time), which should be similar to what you describe. I have deployed netdata to more than 500 slaves and only one master machine to store all the data. It is super awesome and works very well! Looking forward to seeing this fix.

**Comment by ktsaou** [comment]
I managed to reproduce your case also.
I'll solve this. I hope today...

**Comment by ktsaou** [comment]
ok, found the issue. A condition was `>` but it should be `<`. This was a slave bug.
At the same time, I think the master should be able to detect this bad behavior of the slave and fix it by itself. But it is not. So, let me try to fix this issue too.

**Comment by ktsaou** [comment]
ok, fixed that too.

PR #3979 will solve both issues (slave and master).

**Comment by l2isbad** [comment]
> more than 500 slaves and only one master machine to store all the data

Nice server :+1:

**Comment by ktsaou** [comment]
btw, @nathan-liyiming how much CPU does the master netdata use with 500 slaves?
Which memory mode do you use and long is your data history?

**Comment by nathan-liyiming** [comment]
Nice! Thanks for this quick fix. Now, I have more than 500 slaves. CPU usage is 2% and memory usage is 14GB (including the cached). I only forward 15 kinds of metrics per each host because too many metrics I don't care about. This is very awesome for our product.
