### ISSUE TITLE
Map applications into containers

### ISSUE THREAD

**Issue by titpetric** [firehol/netdata#398]
When traversing the `/proc` filesystem, some applications will be running under containers.

- [ ] group them under container/processes
- [ ] ignore apps_groups.conf in this case

Apps_groups should be ignored in the case of containers, because they will usually just have 1 process, and in rare cases 2-3 (indicating bad practice - 1 container = 1 app is good practice).

I'm getting this info from pstree:

```
  │   │   ├─docker-containe,29684 a5b5c709e0ae731a1c25745acc39216c27eb6a3b4c4a123241fcf2c03eff686f ...
  │   │   │   ├─bash,29703
  │   │   │   │   └─sh,59438 [masked]
  │   │   │   │       └─bgp_simple.pl,59439
```

So from 59439 you'd check `/proc/[pid]/parent` until you hit docker. Or vice versa, when you hit docker, put everything under `/proc/[pid]/tasks` into `container/processes`.

~~~
# cat /proc/29684/cmdline | xargs -0 -n1 echo
docker-containerd-shim
a5b5c709e0ae731a1c25745acc39216c27eb6a3b4c4a123241fcf2c03eff686f
/var/run/docker/libcontainerd/a5b5c709e0ae731a1c25745acc39216c27eb6a3b4c4a123241fcf2c03eff686f
docker-runc
~~~

Hope this helps.

**Comment by ktsaou** [comment]
@titpetric why do we need this?

If we do it, we will just re-generate the information already provided by the cgroups plugin for the containers. So what is the point?

Some systems provide a perfect system break-down using containers. Check this: https://github.com/firehol/netdata/issues/329#issuecomment-216184226 Actually each system service runs in its container!

**Comment by titpetric** [comment]
I'm not sure I follow, 329 is a bit TL;DR for me at the moment (I'll follow back on this one). Just to clarify: I wouldn't regenerate it, I would just move it on the front-end to where it belongs, under the container in which it runs. A very common scenario is that I run several nginx web servers in containers, and with apps.plugin I don't know which nginx belongs to which container. Am I missing something?

**Comment by ktsaou** [comment]
ok, may be I am missing something.

Let's see an example: You have 5 containers with a nginx each. Today you have apps charts that track all the nginx together and cgroups charts that track each container/nginx.

According to your suggestion, we should generate a set of apps charts per container. If we do this, you will have:

1. cgroups charts that show each nginx (cpu, I/O, mem, etc)
2. apps charts per cgroup, that show again each nginx (cpu, I/O, mem, etc)

Am I wrong?

**Comment by titpetric** [comment]
It might be me who's missing something. On the right I have "Applications (1)" and "Containers (N)" sections with graphs. Apps have nginx grouped into one chart group (system i think by default). Containers(N) only contain cpu/memory (no mem, no network per container). I have no written text "cgroups" on the page (I asumed cgroups and docker is the same), and I don't have any section with individual "nginx" processes (non-grouped).

My viewpoint is:

**How to group processes runder under docker in the "Applications"?**

Here we have the possibility of grouping all the processes by container, but since Docker follows SOLID principles (1 app per 1 container), it might be better to group everything in a "containers" group. LXC may be a different beast. I'd suggest a confing option to configure this.

**Distinction between "host" and "guest"?**

Docker containers are "guests", and individual processes running inside them should be graphed in the "Container: *" sections on the right. They may be grouped by process-tree in "Applications". Having nginx from a container show up in the Applications graphs doesn't give the distinction between host/container.

I hope I'm clear on my viewpoint? I'm after a clear(er) distinction by what runs on the host, and what runs inside containers.

**Comment by ktsaou** [comment]
ok, before deciding what to do, let me check if there is a netdata bug somewhere.

Please verify these:

For each container, netdata presents 3 submenus: **cpu**, **mem**, **disk**. If you don't have **mem** or **disk**, please verify the relative cgroups do exist. If they don't, you need to enable them at your kernel. If if they do but are not rendered, cgroups support in netdata has a bug - please help me find it.

What is missing from the above is **net**.

apps.plugin does not measure bandwidth per application. This information is not tracked by the kernel (and this is why various other monitoring solutions install kernel modules to sniff all the traffic to categorize it - I object to this and so far I suggest to install QoS to classify the traffic based on port). Apps.plugin only measures the number of open network sockets.

Containers' Network interfaces are tracked by netdata, but are rendered under the "Network Interfaces" section. My intention was to move them under the container they belong, but I don't have a way of finding where they belong (in another thread it was suggested that there must be a way via network namespaces).

If you confirm the above, I don't see how apps.plugin can help further.

My todo like for cgroups is this:

1. move container networks under each container

2. add a few more sections based on info taken from cgroups:

 - **Containers** Section

    It will provide:

      - a CPU chart, with the cpu consumed by each container (containers = dimensions)
      - a MEMORY chart, with memory occupied by each container (containers = dimensions)
      - a chart per physical DISK, with the I/O usage of each container (containers = dimensions)
 
    The above however will not be as detailed as the per container charts. It becomes visually complex to have all the detail when the containers are dimensions. To understand this complexity, go to one of your "Container: X" sections: every **dimension** in these charts will become a chart with the containers as dimensions.

 - **Services** Section

    This should use the information provided by systemd (https://github.com/firehol/netdata/issues/329#issuecomment-216184226) to provide a break down similar to the **Containers** section, but for the services started by systemd.

     This one, pretty much obsoletes apps.plugin, since systemd and cgroups are doing a much better work tracking the resources per service. Of course, this depends on the deployment of systemd.

  Before implementing these though, I think we need to understand how systemd works. Systemd provides cgroups for **scopes**, **services**, **mounts**, **slices** and **users**. It provides cgroups to track **all** system resources in these categories. Also it supports sub-cgroups, so that a **slice** could have **services**. I find this break-down awesome! I am not a systemd expert (actually I have never used it in production), but I think we have to consider these when designing netdata...

  What is even more interesting, is that given the above, the difference between **host** and **guest** is blurred when we are talking about containers. As I see it, the linux development moves towards something that makes every process a container, every user login (ssh, X, etc) a container, every job the system runs a container, etc. and all these are hierarchically correlated... Actually this requires a new UI, this is why I have opened #345

**Comment by titpetric** [comment]
Sorry, still didn't manage to double check this - but it seems I'm missing something from cgroups, as I'm definitely not getting all the data under containers. I'll dump the proc contents for one of the containers, maybe it will give you a hint what's different/missing.

Seems the cgroups proc filesystem is not the most... frozen API. From what I understand, there are bunches of variations/changes observed in various recent versions, which make it a bit tricky to implement a coherent collection API. I'm on debian jessie, which pretty much means that I might be running an older cgroups implementation.

**Comment by ktsaou** [comment]
I think there are kernel options to enable accounting for memory and disk (blkio). Check your `/sys/fs/cgroup/memory` and `/sys/fs/cgroup/blkio`.

**Comment by titpetric** [comment]
I'm totally missing the `memory` location there. Blkio I have (hence I have "disk" under a container). I'm going to ignore this for now, mainly because I don't want to f* with kernel opts. I don't think it's a bug in netdata, just some older version of cgroups.

**Comment by ktsaou** [comment]
I think you have to boot with these kernel options:

```
cgroup_enable=memory swapaccount=1
```

**Comment by ktsaou** [comment]
Check this: https://github.com/docker/docker/issues/4250

**Comment by titpetric** [comment]
Added, worked. I was already sure it's not netdata's issue ;)

**Comment by ktsaou** [comment]
Cleaning up. @titpetric I think this solved. Right?
