### ISSUE TITLE
Hostile Slave, Demilitarized Master

### ISSUE THREAD

**Issue by Immortalin** [firehol/netdata#4017]
Hi! Thanks for building this, it is an incredible piece of software! I have a question, how secure is netdata master if it is in a demilitarized server while the slave is in a server running untrusted code? (Think web/cloud hosting type situations)

**Comment by ktsaou** [comment]
The slave can only push metrics, much like plugins and authentication is via an API key. The master will disconnect slaves that misbehave (wrong communication format, wrong API KEY, etc).

The only thing you have to work on, is that slaves can push any number of host databases at the master (so that netdata proxies are supported too). To limit them to just 1 host database, use this:

1. Use a dedicated API KEY for each of the untrusted slaves (i.e. don't share API keys to multiple untrusted slaves, since you will not be able to block just one of them later).

2. Limit them by IP: https://github.com/firehol/netdata/blob/3dd456202d7a39fec9c6cc434ced30f8acd6c25f/conf.d/stream.conf#L85

3. Do not allow multiple connections: https://github.com/firehol/netdata/blob/3dd456202d7a39fec9c6cc434ced30f8acd6c25f/conf.d/stream.conf#L120

4. Set database mode to `none` at the API key config, so that if the slave starts streaming multiple hosts, they will not use (much) memory at the master: https://github.com/firehol/netdata/blob/3dd456202d7a39fec9c6cc434ced30f8acd6c25f/conf.d/stream.conf#L101

5. Then create a `[MACHINE_GUID]` section in `stream.conf` for the netdata unique id of the slave, with the same settings with the `[API KEY]`, but this time set the right `memory mode` and `history`.

If you really want to protect your netdata master from all kinds of attacks from slaves, I suggest to use a trusted netdata proxy. So, your untrusted slaves will talk to your trusted proxy, which will push metrics to your demilitarized master. This way, untrusted slaves will never talk directly to your master. The proxy will get all the attacks, if any, and it will push to your master processed and normalized metrics. Use the above settings at your proxy. Then your master can trust the proxy with just an API KEY to push all the slaves at once.

Another frequently used strategy, is to install the netdata master outside the demilitarized zone. Since netdata only stores metrics, without any sensitive business info, users are usually installing slaves inside the demilitarized zone, collecting all the metrics and pushing them outside the sensitive zones. netdata allows building such hierarchies (so servers at zone A, send metrics to a netdata proxy inside zone A, which is allowed to send the metrics outside the zone).

**Comment by Immortalin** [comment]
@ktsaou thank you for your insightful answer, I really appreciate it! 👍

**Comment by Immortalin** [comment]
@ktsaou if we decide to configure it in the form of a registry instead, which security measures should we change?

**Comment by ktsaou** [comment]
hm... I am not sure I get it. What do you mean "configure it in the form of a registry"?

**Comment by Immortalin** [comment]
Like the registry style in the netdata documentation
