### ISSUE TITLE
How to know which function or service is consuming more CPU or which function in my web application responding 400 bad request

### ISSUE THREAD

**Issue by ashutoshrenu** [firehol/netdata#4074]
I have found lots of bad requests in web log responses i want to know which service creating problem i want to identify that method how can i dot it also i want to know which service in my web application consuming more CPU. How can i get it with netdata any help will be appreciated

**Comment by Ferroin** [comment]
Realistically though, 400's are probably not your web application unless you've explicitly coded it to return a 400 error code somewhere (in which case you can just look through the code).  You can verify this by looking at your web server logs yourself, specifically what the client addresses associated with the 400 errors are.  If they don't match up with clients who have made successful requests to paths for your web application, then it's not the web application causing them.  Otherwise, it _might_ be the web application (but probably isn't).

400 isn't really a generic error code like the other x00 codes, it pretty universally means that the request string or headers were invalid, so if they aren't coming from your app, then the web server is returning them because clients are issuing malformed request strings or headers, and it's likely due to one of the following:

* Someone thinks your webserver is a proxy, and is trying to issue a `CONNECT` request.
* Someone thinks your webserver is a WebDAV server, and is trying to issue WebDAV methods that aren't part of standard HTTP (like `PROPFIND` or `MKCOL`).
* Someone is trying to talk to your web server with a protocol other than HTTP (for example, about 20% of the 400 errors on my web servers are people trying to connect to port 80 on my systems with SSH).
* Someone is running `nmap` against your system and has the service version detection feature enabled.
* Someone is trying to exploit your system.

**Comment by ashutoshrenu** [comment]
@Ferroin  thanks for your reply it is really helpful i have another question my CPU load average is very high even there is very few clients surfing my site so i want debug this using netdata which process is consuming more CPU

**Comment by Ferroin** [comment]
Load average isn't the same as CPU usage.  It can correlate with it, but they aren't the same thing.  First thing to check is the CPU chart.  That will show you whether it's CPU usage (high `user`, `system`, or `nice`), or IO (high `iowait`).

The first case (high CPU usage) is reasonably easy to track down.  Check the 'Apps', 'User Groups', and 'Users' sections on the Netdata dashboard (assuming you don't have the apps plugin disabled), and you should be able to figure out enough information between the CPU charts for all of those to determine what is causing the issues.

The second case (high IO load) is a bit trickier, because while it usually means excessive disk usage, it might not.  The first thing to check is the same as for the first case, just look at the disk charts instead of the CPU ones.  If that turns up nothing, then you either have something stuck in an uninterruptible sleep state (in which case rebooting should fix things, though you may need a hard reset for the system), or something is doing some other kind of complex IO that does not involve the block layer (which is a _lot_ harder to track down).

You may also want to look into [htop](https://hisham.hm/htop/).  It's a replacement for the classic UNIX `top` command that provides a much nicer interface, and is great for tracking down issues like this (it should be available in your distribution's package repositories, usually as a package with the name `htop`).

**Comment by ashutoshrenu** [comment]
thanks @Ferroin
