### ISSUE TITLE
When will netdata save its database to registry.db and empty registry-log.db?

### ISSUE THREAD

**Issue by 74cmonty** [firehol/netdata#4121]
From the instructions [here](https://github.com/firehol/netdata/wiki/mynetdata-menu-item) it's not fully clear when persistent saving takes place.

THX

**Comment by ktsaou** [comment]
Persistent saving to `registry-log.db` is real-time. Netdata appends entries to `registry-log.db` immediately, much like a log file.

Then, when the following setting is reached, netdata dumps a new `registry.db` and moves `registry-log.db` to `registry-log.db.old` and creates an empty `registry-db.log`.

```
[registry]
	registry save db every new entries = 1000000
```

I have chosen to do this every 1 million entries by default, mainly because loading back such a file is almost instant. If you want more frequent rotation, lower this value.
