### ISSUE TITLE
Add logrotate setting for netdata

### ISSUE THREAD

**Issue by deveth0** [firehol/netdata#413]
Hi,

i just stumbled across the size of my error.log which is currently around 50mb. I think it would be worth to add a logrotate config for netdata in /etc/logrotate.d/netdata, e.g.:

````
/var/log/netdata/error.log {
        daily
        missingok
        rotate 7
        compress
        copytruncate
        notifempty
        create 640 root root
}
````

**Comment by ktsaou** [comment]
There is one in the system directory.

**Comment by ktsaou** [comment]
I added this information at the installation page.
Thanks!

**Comment by deveth0** [comment]
Shouldn't that be installed automatically?

**Comment by ktsaou** [comment]
you are right! it should! I am changing the installer now...

**Comment by lokiiiii** [comment]
Hello there,

Since this update about lograte, my cron.daily doesn't work anymore with the log:
`/etc/cron.daily/logrotate:
error: error setting owner of /var/log/netdata/access.log.1 to uid 999 and gid 999: operation not permitted`
My /var/log/netdata is set to 755 with netdata:netdata
And my /etc/passwd is set like this: "netdata:x:999:999:netdata:/:/sbin/nologin"

Am I missing something here ?
Thanks !

**Comment by ktsaou** [comment]
Can you post you `/etc/logrotate.d/netdata`?

**Comment by deveth0** [comment]
and please also try to execute logrotate manually:
/usr/sbin/logrotate -v /etc/logrotate.conf

Costa Tsaousis <notifications@github.com> schrieb am Mi., 18. Mai 2016 um
10:07 Uhr:

**Comment by lokiiiii** [comment]
/usr/sbin/logrotate -v /etc/logrotate.conf worked well, no log rotation was needed but no error when running it.
For my /etc/logrotate.d/netdata, I think it's OK since the command above worked, I'll wait for my next cron.daily run to see if it could be a permission issue while updating netdata.
I'll keep you in touch, thanks to both of you :)

**Comment by lokiiiii** [comment]
I had the same issue again last night.

Here is my /etc/logrotate.d/netdata:

```/var/log/netdata/*.log {
daily
missingok
rotate 14
compress
delaycompress
notifempty
sharedscripts
#
# if you add netdata to your init.d/system.d
# comment su & copytruncate and uncomment postrotate
# to have netdata restart when logs are rotated
su netdata
copytruncate
#
#postrotate 
#       if service netdata status > /dev/null ; then \ 
#               service netdata restart > /dev/null; \ 
 #       fi;
#endscript 
}  ```

**Comment by lokiiiii** [comment]
Yop yop, I still got this issue everynight, do you have any idea ?
Could I provide some more logs ?
