### ISSUE TITLE
Adding custom dashboards

### ISSUE THREAD

**Issue by Yenthe666** [firehol/netdata#437]
Hi @ktsaou,

Sorry for having to create an issue for this but this looked like the best way to reach out to you.
First of all, a major congratz on such a nice piece of software. I've tried a few others, but this one is far better, especially thanks to the live charts.

So I've installed Netdata and I wanted to create a new dashboard. I was under the assumption that adding a new html file under `/web` would be enough if I also add the link to this HTML file in `web/Makefile.am`. However when I go to the browser I will always get this error:
![image](https://cloud.githubusercontent.com/assets/6352350/15454360/5737bc70-2037-11e6-9140-43a3932950aa.png)

Should anything else be done? I've created the HTML file in `web` and with the correct rights:
![image](https://cloud.githubusercontent.com/assets/6352350/15454364/6ecdb894-2037-11e6-9670-1d4a890ab6ea.png)

Should I reload Netdata or something?

Thanks for the help,
Yenthe

**Comment by ktsaou** [comment]
Thanks!

1. your custom dashboard can be hosted anywhere you like. The only requirement is to include `dashboard.js` from a netdata server.

2. if you put your file in the `web` directory so that it will be served by netdata itself, please `chown` it to match the other files (usually `chown netdata:netdata myfile.html`. There is no need to change anything in netdata configuration, nor to restart netdata.

**Comment by Yenthe666** [comment]
Hi @ktsaou,

Thank you for the feedback. I've created a new html (`demo3.html`) under `/web` with the following content:
![image](https://cloud.githubusercontent.com/assets/6352350/15469812/f93d1ff0-20ec-11e6-8e62-3f19be5b4458.png)
It has the rights for netdata `(chown netdata:netdata demo3.html`) and the `dashboard.js` file is included, as you can see in the screenshot.
But when I navigate to the URL `http://localhost:19999/demo3.html` I will still get this error:
![image](https://cloud.githubusercontent.com/assets/6352350/15469841/2913f85c-20ed-11e6-9ecb-9fc2e827b710.png)

Am I missing something else?

**Comment by ktsaou** [comment]
1. run `ls -l /usr/share/netdata/web/demo3.html`. What does it say?
2. Since you host the html in netdata, the dashboard.js url should be `dashboard.js` without anything more. You have put `http://127.0.0.1:19999/dashboard.js` so this page will only be accessible from the same machine (your browser hits that URL).

**Comment by Yenthe666** [comment]
1. I went with `ls -l ~/NetData/netdata/web/demo3.html` since it is located elsewhere on my system. The output:
![image](https://cloud.githubusercontent.com/assets/6352350/15470496/561e55aa-20f1-11e6-88d6-2b3c29061a35.png)
2. I changed `http://127.0.0.1:19999/dashboard.js` to `dashboard.js`, but still the same issue:
![image](https://cloud.githubusercontent.com/assets/6352350/15470539/89bd424a-20f1-11e6-986e-b741f5bf3332.png)

**Comment by ktsaou** [comment]
Wait a moment. netdata searches for it in `/usr/share/netdata/web`, so this where you have to install it. How did you install netdata? Did you use the installer with a custom `--install` option? It seems you have not.

Can you please run `ps fax` and give us the netdata tree? This is mine:

```
27749 ?        SNl    1:38 /usr/sbin/netdata -pidfile /var/run/netdata.pid
27777 ?        SN    12:29  \_ /bin/bash /usr/libexec/netdata/plugins.d/charts.d.plugin 1
 2497 ?        SN     0:00  |   \_ sleep 0.2
27780 ?        SNl    0:39  \_ /usr/bin/node /usr/libexec/netdata/plugins.d/node.d.plugin 1
27781 ?        SN     5:19  \_ /usr/libexec/netdata/plugins.d/apps.plugin 1
31790 ?        SN     0:10  \_ /bin/bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
 2463 ?        SN     0:00      \_ sleep 0.973
```

What is yours?

**Comment by Yenthe666** [comment]
I followed the guide at https://github.com/firehol/netdata/wiki/Installation and installed everything under `~/NetData`. 
When running `ps fax` I get the following:
```
 4152 ?        SNl    0:04          \_ /usr/sbin/netdata
 4159 ?        SN     0:00          |   \_ /bin/bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
 7652 ?        SN     0:00          |   |   \_ sleep 0.989
 4163 ?        SN     0:04          |   \_ /bin/bash /usr/libexec/netdata/plugins.d/charts.d.plugin 1
 7654 ?        SN     0:00          |   |   \_ sleep 0.2
 4164 ?        SN     0:12          |   \_ /usr/libexec/netdata/plugins.d/apps.plugin 1
 4312 ?        Sl     0:21          \_ /usr/lib/firefox/firefox
 5323 ?        Sl     0:02          \_ gedit /usr/share/netdata/web/demosites.html
```

**Comment by Yenthe666** [comment]
@ktsaou and @simonnagl sorry for pinging you two, but could you have another look at this? I can't find anything odd?

**Comment by ktsaou** [comment]
You are placing your custom dashboard in `~/NetData/netdata/web/` but your netdata server is looking for it in `/usr/share/netdata/web`.

I thought you have installed netdata in `~/NetData` and I asked for `ps fax`, but your `ps fax` shows that netdata is running from the system directories.

So your solution is simple:

Since you run netdata from the system directories, your web files should be placed in `/usr/share/netdata/web`. Place your dashboard there and it will work. Check the ownership of the files too (they should be owned by user `netdata` and group `netdata` - check the other files in this directory).

If you don't like this, you can serve your custom dashboard with apache or nginx or any other web server. If you do this though, you should properly include `dashboard.js` in your html, so that your web browser will find it (e.g. `http://netdata.server:19999/dashboard.js`). If you leave it as `http://127.0.0.1:19999/dashboard.js` then only localhost will be able to view your dashboard.

**Comment by Yenthe666** [comment]
Looks like my previous installation had an issue with rights / folders. I did a re-install and I can now easily add custom dashboards. Thank you @ktsaou!

**Comment by Yenthe666** [comment]
@ktsaou,

I had one more question if you don't mind. Imagine that I have my own application where I want to show your dashboards on. My application runs on port `8069` and I add the `dashboard.js`, what more should I do to make it work inside my application?

> If you don't like this, you can serve your custom dashboard with apache or nginx or any other web server. 

What exactly do you mean by this? Is it enough if I just add `http://netdata.server:19999/dashboard.js` in?

**Comment by ktsaou** [comment]
> What exactly do you mean by this? Is it enough if I just add http://netdata.server:19999/dashboard.js in?

yeap!

Keep in mind `dashboard.js` will load jquery, bootstrap, themes, etc. If this messes your page, you can load them yourself. Check the first few lines of `dashboard.js` for options you can set before loading it to your page.

**Comment by fti-dpogra** [comment]
i have some processes i want to show status of these process over netadata homepage.. How can proceed?

**Comment by cakrit** [comment]
> i have some processes i want to show status of these processes over netadata homepage.. How can proceed?

Please create a new issue so we can answer your question. The default netdata UI doesn't currently permit extensions though, we'll be adding custom dashboards in the upcoming releases.
