### ISSUE TITLE
dashboard.js - Cross-domain authentication problems

### ISSUE THREAD

**Issue by hhallman** [firehol/netdata#477]
When deploying NETDATA in one domain and using the charting functionality on another, there are three problems.

1) The hello ajax-call is made with double / between the deployment resource path:
`https://myhost/mynetdata//hello-resource`
`Init()` needs to call `hello()` with `NETDATA.serverDefault.slice(0, -1)`, or similar, instead of just NETDATA.serverDefault. (hello expects host without trailing /, but serverDefault always has a trailing /)

2) When drawing and updating charts, jQuery needs the `xhrFields: { withCredentials: true }` option. (Possibly more places)

3) When loading the font-resource, `/fonts/fontawesome-webfont.woff2?v=4.5.0`, in my case, my browser complains on 403 because the cookies are not sent. The font is loaded from: `/css/font-awesome.min.css`, which is correctly loaded with authentication headers.

**Comment by ktsaou** [comment]
Hi,

1. You are right. I am submitting a PR now. Although no harm is done.

The other two are not right. `withCredentials: true` is only required for the registry calls, since this is the only place we use cookies. Charts and static files are public info (no cookies are required).

To verify it, I just edited the file  `demosites.html` on my netdata, to fetch `dashboards.js` from `http://registry.my-netdata.io`, and it worked. It downloaded all static files from `registry.my-netdata.io` and charts from all 3 servers on that dashboard are being refreshed properly.

Tried it with chrome and firefox.

Which browser are you using?

**Comment by ktsaou** [comment]
merged the fix for No 1 with PR: #478

**Comment by hhallman** [comment]
Hi ktsaou,

The cookies are needed for me, since I'm using an authenticating proxy that protects all HTTP(s) traffic, including netdata. The proxy we use provide access by means of cookies.
If you have a design-principle of not needing cookies in the second case, then we might be looking at a configuration needed?

**Comment by ktsaou** [comment]
oh! I see. 

I have added the needed ajax options on all ajax queries in my private repo: https://github.com/ktsaou/netdata

Could you please clone this repo and install it? If it works, I'll merge it to the mainstream.
