### ISSUE TITLE
Can I monitor several servers from one single netdata instance?

### ISSUE THREAD

**Issue by Jramirezg** [firehol/netdata#510]
I have 40 LXC containers in different hosts and I would like to monitor ll the instances from one single netdata monitor. Is that possible? What are the steps to follow? Thanks!!!!
JR

**Comment by ktsaou** [comment]
Install one netdata per host. Don't install it in a container, but directly on the host.
The above will monitor the host system and all the containers.

Regarding plugins (applications monitoring) there are a few plugins (php-fm, mysql, bind) that can monitor multiple instances of the same application. However, since your applications will run in containers the only way to connect to them is via the network. I am trying to figure a way to allow this to happen by switching namespaces. It seems feasible, but it needs some more work from my side to standardize it. Check #474.

You can find my view of how this should finally work, here: https://github.com/firehol/netdata/issues/474#issuecomment-223142222

To understand why netdata needs to be installed on each host, check https://github.com/firehol/netdata/wiki/mynetdata-menu-item

Netdata collects thousands of metrics per second per server. It does this with <1% cpu usage of a single cpu core (plugins may require more). If you are going to centralize all these data, you are going to needs some serious dedicated resources for data collection and visualization. So, we scale out.

**Comment by NeckBeardPrince** [comment]
Wondering the same thing but minus the containers.
I have between 12 and 20 hosts per topo in EC2 wondering if I can have all metrics go to one dashboard on just one of the instances.
`status.dev.application.domain.com` and see everything in that env and that topo.

**Comment by ktsaou** [comment]
Check #416. When this task is completed, you will not need to centralize the data.

Keep in mind you can **already** have dashboards with data coming from all servers. http://my-netdata.io is an example. Just view its source. It is plain HTML, no javascript needed. Check also http://your.netdata:19999/tv.html, another HTML-only example.

**Comment by ktsaou** [comment]
`tv.html` is a lot simpler to get started with your multi-server dashboard.

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, please post here.

**Comment by ktsaou** [comment]
btw, as of v1.3.0 most application data collectors have been ported to python and each of these supports collecting data from multiple instances of the same application.

**Comment by mailinglists35** [comment]
I have an use case where the operator has to monitor metrics of a system to which he does not have tcp/ip connectivity to (it's a database behind a firewall), but has access to the front end application host on where a netdata is running.

In this case I cannot use the tv.html example dashboard as there is no direct ip connectivity between the browser and the monitored system. 

Will registry allow this scenario?

**Comment by ktsaou** [comment]
ok, but PR #1817 should also be mentioned here. This PR adds multi-host support to netdata.
