### ISSUE TITLE
memory latency optimization

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#534]
Today netdata allocates structures for thousands of metrics and charts, all updated per second. This produces thousands of minor page faults per second. You can see this number that the Applications section, at the memory chart, the dimension `netdata`.

I am not aware of any issues, apart from various notes on the net that minor page faults are a source of memory latency for the application that makes them.

So, I am trying to find a way to lower the number of minor page faults netdata generates.

The obvious way is to compact the frequently used memory to the least possible pages. This can be done using arrays instead of individual `malloc()` for the structures used for charts, dimensions and configuration options (all these are accessed all the time), and possibly using some kind of buffers for storing collected values for some time (e.g. 30 mins) and then copying them to their final location in larger batches.

If you know any other way, please let me know.

**Comment by ktsaou** [comment]
@fredericopissarra do you know if minor page faults is problematic for any reason?
If you have any idea about this, please let me know.

**Comment by ktsaou** [comment]
false alarm. BASH (charts.d.plugin) is generating all these minor page faults. I guess because it runs so many commands every second that need to be loaded / linked.

I am closing this.

**Comment by fredericopissarra** [comment]
It depends on the fault... Page faults occurs all the time (when the 
stack grows and when you fork a process (copy on write rely on paging to 
do it's job), for instance).
Some page faults are bad: Try to write in a page marked as read only 
(OpenBSD will enforce this on pages of your code, making very difficult 
to do shell codes!).

mmap() can create pages not available in memory when the syscall is 
made, but will be when the first page fault occurs. That's why functions 
of malloc.h will try to use another method for quantities less then 128 
KiB, relying on mmap() just for big blocks. If you are using more then 
128 KiB of the heap it will use mmap, I mean...

But It is wise to avoid them. Preallocation and writing a single byte in 
every page can mitigate faults, but they can be swapped out if there is 
not enough physical memory available..
