### ISSUE TITLE
EXIM plugin

### ISSUE THREAD

**Issue by emper0r** [firehol/netdata#56]
Hi, 
I see on todo list a postfix MTA, Can you add for an EXIM mail server too ?
thanks for the great job.

**Comment by ktsaou** [comment]
Hi,

I don't have EXIM installed. Can you help?

If yes, I need to know the following:

1. The command that returns statistics, with its command line options. Make sure the command returns immediately (there are a few mailers that provide statistics by parsing mail logs - such commands will not do, since they consume a lot of resources). My little search shows the command in question might be  `exim -bpc`.

 Check its performance too. Run it like `time exim -bpc`. Is it fast? If not, it will use significant resources on your systems (I can hard code a max update frequency to overcome this).

2. A few sample outputs of the command. We need to parse this to extract its counters. If you have multiple versions of it installed, please provide the output of different versions too.

3. Your idea on the charts to be created (how many, which value of the output should go to each chart, etc).

If you provide these, I'll create a new bash plugin for it.

**Comment by mcnewton** [comment]
`exim -bpc` is the right command to get the number of messages on the queue. It simply outputs a single number to stdout (it needs root, or an exim trusted admin user, to be used, though this requirement can be disabled in the configuration):

> root@gemsbok:/# exim -bpc
> 92
> root@gemsbok:/# 

The exim queue is flat - a single directory of files. So the alternative is to count the files ending in '-H' in the spool directory. But calling `exim -bpc` will do the same thing and is probably safer. Of course this can slow down if there are massive numbers of messages stuck in the queue.

I don't believe there is any way to get stats out of a running exim apart from by examining the logs, so that isn't a quick process unless you continuously tail the logs.

Cheers,
Matthew

**Comment by jsveiga** [comment]
Hello, the latest version has included the exim script on charts.d.
BR!

**Comment by ktsaou** [comment]
@jsveiga thanks!

**Comment by paulfantom** [comment]
close?

**Comment by ragnar76** [comment]
just one question. how do enable/install it. i've made a copy of exim.chart.sh to /etc/netdata/charts.d , added the exim_command but nothing happend.

do i need to add a [plugin ****] to the config file?

**Comment by paulfantom** [comment]
Since netdata moved from bash to python, if you want to use exim bash module (`exim.chart.sh`), you should add line `exim=force` to `charts.d.conf`.

Also if `exim` binary isn't detected, you can add `exim_command=/path/to/binary/exim` to `charts.d.conf`.

**Comment by ragnar76** [comment]
Okay, made so but, still it does not work.

At first i get this message in error.log:
`charts.d: exim: configuration file '/etc/netdata/charts.d/exim.conf' not found. Using defaults.`

after this the next message is:
```
charts.d: exim: permission denied. Please set 'queue_list_requires_admin = false' in your exim options file
charts.d: chart 'exim' check() function reports failure.
```

so, i've created an exim.conf in /etc/netdata/charts.d i get this:
`
/etc/netdata/charts.d/exim.conf: line 1: queue_list_requires_admin: command not found`

and later on this comes up
```
python.d ERROR: exim_local No data collected.
python.d ERROR: exim_local No data collected.
python.d ERROR: exim_local 'NoneType' object has no attribute '__getitem__'
python.d INFO: Disabled exim
```

**Comment by jsveiga** [comment]
Hi, 

"queue_list_requires_admin = false" goes into your exim options configuration (not on netdata's exim configuration). For a debian exim with split-file configuration, that would be in

/etc/exim4/conf.d/main/000_local_options for example

on a single file configuration, it should be /etc/exim/exim4.conf; you have to check your specific distro/configuration.

that setting is telling exim that a non-root user can call the command to list the mail queue content. This is required because the netdata scripts do not run as root.

regards,

Joao

**Comment by ragnar76** [comment]
That was the missing link and now it works. Thank you :)

**Comment by paulfantom** [comment]
Close?

**Comment by ragnar76** [comment]
*shrug* close but a nice english install guide would be nice ´;)

**Comment by ktsaou** [comment]
If I add the following to `/etc/netdata/python.d/exim.conf`, is it sufficient?

```yaml
...

# REQUIRED exim CONFIGURATION
#
# netdata will run exim as user netdata. By default exim will refuse to run.
# To allow running exim as non-admin user, please set:
#
# queue_list_requires_admin = false
#
# to your exim configuration. Your exim configuration should be something like:
#  /etc/exim/exim4.conf
#  /etc/exim4/conf.d/main/000_local_options
# Please consult your distribution information to find the exact file to add it.

...
```

**Comment by ktsaou** [comment]
Also, is there any alternative? For example is there an `admin` group to add user netdata to, that will allow   running exim?

**Comment by ragnar76** [comment]
Doesn't look good, debian default is __Debian-exim__ for user and group

**Comment by jsveiga** [comment]
Yes, I'd just suggest "netdata will query the exim queue list as user
netdata"; "netdata will run exim" may scare some users.

Joao

**Comment by jsveiga** [comment]
I'm not sure, but the queue_list_requires_admin route is the safest imo, as
it is only giving the non-root authorization to query the queue and nothing
more. If netdata is added to a group authorized to run exim, then it's too
much power just to be querying the queue.

**Comment by ktsaou** [comment]
This one?

```yaml
...

# REQUIRED exim CONFIGURATION
#
# netdata will query exim as user netdata. By default exim will refuse to respond.
# To allow querying exim as non-admin user, please set:
#
# queue_list_requires_admin = false
#
# to your exim configuration. Your exim configuration should be something like:
#  /etc/exim/exim4.conf
#  /etc/exim4/conf.d/main/000_local_options
# Please consult your distribution information to find the exact file to add it.

...
```

**Comment by ktsaou** [comment]
final here: https://github.com/ktsaou/netdata/commit/7c4ad3324f1fe4e2cb25c8d7b29ba5402d4c3e6a

is it ok?

**Comment by ktsaou** [comment]
merge it.
