### ISSUE TITLE
Your netdata version: Unknown

### ISSUE THREAD

**Issue by da2x** [firehol/netdata#614]
I downloaded the latest version from [the GitHub releases page](https://github.com/firehol/netdata/releases/tag/v1.2.0), and followed these [installation instructions](https://github.com/firehol/netdata/wiki/Installation). Fedra 24.

When I click the Update button I get the following error message:

> Your netdata version: Unknown
> Failed to get your netdata version!

Everything else appears to be working just dandy.

**Comment by ktsaou** [comment]
You are right. This is a bug in the released versions. A file is not generated.

@philwhineray any ideas on how to include a `version.txt` on the released version?

**Comment by philwhineray** [comment]
Where are you looking?

In the netdata-1.2.0.tar.gz from the releases page it is pre-generated from
package creation time, so already present and is installed by the
Makefile.am.

If you pull down one of the links called "source code", these are
autogenerated by github, which means autoconf has not been run and this
file (along with various others from the release package) will be missing
from the package i.e. it's not really a release. It cannot generate a
usable versions.txt file because the content is the most recent git ID, so
you get a value '0'.

I looked around and as far as I can tell we can't suppress these links,
other people have asked for it. I don't know what other projects do in this
situation, I will have a look around in my spare time.

Now, this '0' file was considered valid so that people (e.g. distros) could
prevent auto-update but I guess we could edit the script to make it fail
with a message in this circumstance.

**Comment by ktsaou** [comment]
ok, let me explain what I understand:

1. When we release netdata, the user is going through autogen.sh, etc, but there is not `.git` directory.
2. Since there is no `.git`, the makefiles cannot find the commit id to place in `version.txt`, so they just write a zero to disable this feature.

What we need, is to have a `version.txt` file with the correct commit id, placed inside the release package. So, users downloading the released version will have the commit id that had been used for making the release.

Am I missing something?

**Comment by Aeyoun** [comment]
I, as a user, has also not installed through a distro but through the releases you’ve published here on GitHub. I wouldn’t expect the updater to be disabled (Nor would I expect it to show me git hashes, but version numbers as I installed a tagged release.)

I’ll just subscribe to https://github.com/firehol/netdata/releases.atom. Your updater for released versions could use this too, I guess.

**Comment by philwhineray** [comment]
@ktsaou when you do a release, the commit id is written to the version.txt
file and included in the tar.gz etc., this happens with both the formal
releases (1.2.0) and with the "nightly" (read instant) builds. These also
include a configure file, so no run of autogen should be necessary but in
any case I don't believe the version file would be overwritten if it was.

Unfortunately, github also provides two links for a tar and for a zip,
which is basically an export of the repository. There is no way to get the
commit id in there. Smudge filters are not applied so these cannot be used.
With these links, if you use the nedata-installer.sh then you get told what
happened and pointed to the packaged releases. If you bypass the script or
do not heed the warning then you get the '0' file.

@Aeyoun makes the suggestion of using release version numbers instead which
could be made to work regardless of which package was downloaded but would
require a code change to look for an incrementing version number rather
than a simple difference of commit id (where the repo can be assumed to be
later if the two are different). This may be better long-term anyway for
those who do not want to live on the bleeding edge.

**Comment by ktsaou** [comment]
I think this has been fixed. There is a new version number now, that includes both the release of netdata and the number of commits since the last released version.

I am closing it. If you believe there is something missing, just post.
