### ISSUE TITLE
License incompatibility

### ISSUE THREAD

**Issue by FedericoCeratto** [firehol/netdata#725]
Hello and thanks for developing Netdata.
The "src/avl.h" file is under GPL-2 *only* while the majority of Netdata is under "GPL-3 or later".
avl.h is being included by 7 files.

Thanks

**Comment by ktsaou** [comment]
netdata re-distributes a uses components under various licenses. Check: https://github.com/firehol/netdata/blob/master/LICENSE.md

AVL is properly mentioned there.

Is that a problem?

**Comment by FedericoCeratto** [comment]
It is: building GPLv3 code against a GPLv2 library violates the license of the library.

The good news is that Debian distributes a LGPL version of libavl that you can use:
[libavl](https://packages.debian.org/sid/libavl1)
[copyright](http://metadata.ftp-master.debian.org/changelogs//main/liba/libavl/libavl_0.3.5-4_copyright)

The upsteram website seems to be dead. You could have Netdata depend on this library at compile and runtime if it's available on other distros as well, or maybe fetch the sources from Debian to replace src/avl.*

**Comment by ktsaou** [comment]
@nagydani I use in netdata your AVL library for its internal index. You have done a wonderful job in this library and actually much of the performance of netdata comes thanks to your work.

I am facing a problem here: I want netdata to use the latest GPL version 3+. However, as you can see in the comments above, I should not link netdata against GPL v2 code.

I have 3 alternatives now:

1. Remove your AVL library from netdata and find an alternative.
2. Use GPL v2 for netdata
3. Get an LGPL or a GPL v3+ license from you.

Before evaluating (1) or (2), I would kindly request (3) from you. Can I have your AVL library as LGPL or GPL v3+ ?

Thanks!

**Comment by lhw** [comment]
A GPL 2+ would suffice in this case. You can find the license compatibility here: http://gplv3.fsf.org/dd3-faq

**Comment by ktsaou** [comment]
@lhw thanks! So a GPL v2+ from @nagydani is also good. I updated my request above (replaced at point 3, GPL v3+ with GPLv2+).

**Comment by lhw** [comment]
I have been looking around for a bit. The avl.c/avl.h from http://adtinfo.org/ could be used as a drop-in replacement. As it is licensed under GPL-2+.
The library in debian could be linked but it doesn't seem to be present in other distribution repositories and the upstream website is not available anymore. So it would take extra time to get the library into the other distros and I don't think thats a good solution.

**Comment by lhw** [comment]
The GNU avl would require some minor changes for the normal version and an additional mutex for the lock version. I could create pull request for the changes if you'd prefer a quick solution to this.

**Comment by ktsaou** [comment]
hm... I am not sure they are so close. I mean, @nagydani version is perfect for embedded apps because it does not allocate any memory (this is also the key reason I chose it). This allows netdata to embed the AVL node into its structures. In a few cases netdata even uses offset() to find the relative position of the AVL node in its objects.

Having the AVL node in its private allocated space, will also increase the memory footprint of netdata by 8 bytes per node on 64bit machines. This might affect a large registry significantly. It will also increase memory fragmentation, which is important for embedded apps.

Of course we can work around these issues, but before starting I would suggest to wait 1-2 days for a response from @nagydani. I hope he will respond.

**Comment by lhw** [comment]
Yes we can wait a few days of course. Just saying its an option. 

Also I checked the avl usage. The offsetof is used on the retrieved data structure, not the avl tree. So a switch of the implementation would only end up in changing the API calls and adding a mutex were necessary. But yes this implementation would alloc/free memory.

**Comment by ktsaou** [comment]
Since we are talking about possible options:

Another option could be to keep @nagydani API as-is (the header file, with my lock additions) and rewrite the functions to use loops instead of recursion. This will also increase its speed significantly.

I have measured that @nagydani implementation can do about 1.2 mil inserts/sec per core on a J1900. He did not have an exact search (only range search was supplied). So, I wrote the exact search, without recursion - with a loop, and it does 1.8 mil searches/sec per core on the same machine.

Thus we can expect quite an increase in speed for inserts and deletes by re-writing `insert` and `delete`. We don't need the `range` one.

So, if I re-write it to be a drop in replacement, can I release the new one as GPL v3+?

**Comment by lhw** [comment]
Yes that would be an option. And of course you are then free to chose the license as you see fit. As long as you don't straight out copy code from the GPL2 implementation that is.

About the API I can only say that AVL is textbook, so a similar API will exist in all implementations so it shouldn't be an issue with having the same.

July 25 2016 5:21 PM, "Costa Tsaousis"  wrote:
	Since we are talking about possible options: 

	Another option could be to keep @nagydani (https://github.com/nagydani) API as-is (the header file, with my lock additions) and rewrite the functions to use loops instead of recursion. This will also increase its speed significantly. 

	I have measured that @nagydani (https://github.com/nagydani) implementation can do about 1.2 mil inserts/sec per core on a J1900. He did not have an exact search (only range search was supplied). So, I wrote the exact search, without recursion - with a loop, and it does 1.8 mil searches/sec per core on the same machine. 

	Thus we can expect quite an increase in speed for inserts and deletes by re-writing insert and delete. We don't need the range one. 

	So, if I re-write it to be a drop in replacement, can I release the new one as GPL v3+?

**Comment by ktsaou** [comment]
Since @nagydani is not responsive, I made PR #740 which replaces his AVL library with libavl 2.0.3, adapted to remove all memory allocations and use data structures with exactly the memory footprint of the @nagydani version ( @lhw thanks for the hint - they were very close indeed ).

In my benchmarks, it seems libavl performance is very close +/- 1% (faster inserts, slower searches for non-existing keys). Probably @nagydani version manages better the balance of the tree, hence the difference. Anyway, it is not so significant to trace it.

I am testing it. If @nagydani does not alter its license within the next few days, I'll merge it.

**Comment by ktsaou** [comment]
Since @nagydani is not responsive, I merged PR #740.
Thank you guys for reporting this and me helping me.
