### ISSUE TITLE
Option to view cached data while netdata is offline

### ISSUE THREAD

**Issue by LucaDev** [firehol/netdata#777]
It would be nice to have an option to look at the old charts even if the netdata sevice or the whole server is offline instead of this "data download failed for url" error

**Comment by ktsaou** [comment]
I know this is too late. Somehow I missed this issue.

There is now the option of streaming metrics between netdata servers. So, assign one to be the master, and configure all your netdata servers to push metrics to it.

**Comment by christomaliyekkal** [comment]
If I have N servers as slave and 1 centralized server as master, I will be pushing metrics from all slaves to master. But what will happen if slaves are offline(no connection to master) for X hours? Are those metrics data lost? Or metrics when slave was offline will be whenever connectivity is restored?

**Comment by ktsaou** [comment]
> If I have N servers as slave and 1 centralized server as master, I will be pushing metrics from all slaves to master. But what will happen if slaves are offline(no connection to master) for X hours? Are those metrics data lost? Or metrics when slave was offline will be whenever connectivity is restored?

Today the metrics will be lost. We plan to re-implement the streaming functionality to replicate the database instead of having the slave netdata operate as a remote data collection plugin for the master. This will allow the slave to push the missing metrics to the master.

Keep in mind, the existing functionality allows defining multiple masters (space separated). The first working master will be used. So, you could have a setup like this:

SLAVE -> MASTER A -> MASTER B

On slave you could define both MASTER A and MASTER B. So, if MASTER A is lost, the SLAVE will push all the metrics to MASTER B. Given than MASTER A is pushing metrics to MASTER B too, on MASTER B there will be no lost metrics if MASTER A goes down. Not perfect, but somewhat better than nothing.

**Comment by cakrit** [comment]
Your scenario also needs the longer retention period that will come with the implementation of #4687 (in progress).
