### ISSUE TITLE
Packet counts is frequently not an integer

### ISSUE THREAD

**Issue by timtjtim** [firehol/netdata#788]
Frequently, the packet count will be a decimal - sometimes varying up to 0.1 from a whole number (pictured).

This is fairly annoying, as packets are one thing.

![screenshot from 2016-08-16 00-50-49](https://cloud.githubusercontent.com/assets/6292691/17683534/919e28ca-634b-11e6-871d-ccfa3b137f2c.png)

**Comment by ktsaou** [comment]
This happens because netdata interpolates the collected values at exactly second boundaries using nanosecond resolution. This removes the data collection latencies from the presented numbers (without this interpolation, a data collection delay could present wrong information).

Most numbers in netdata are rates. For example, the number you refer most probably is **116.9 packets per second**, not an absolute number.

Rounding this number, is not easy. It depends on the metric itself if it can be rounded or not. There are many metrics that 0.6 and 1.4 are quite different and should not be rounded to 1.

One solution I am thinking is to allow you round these numbers on custom dashboards yourself.

**Comment by ktsaou** [comment]
netdata keeps up to 7 decimal digits for all numbers.

What I have done in the code (https://github.com/firehol/netdata/blob/81b986a426cf51002a2073085e83a9a83bf957be/web/dashboard.js#L1931-L1936) is this:

1. values above 1000 show no decimal digits
2. above 100 and below 1000, show 1 decimal digit
3. above 1 and below 100, show 2 decimal digits
4. above 0.1 and below 1, show 3 decimal digits
5. below 0.1 show 4 decimal digits

I am open to better ideas...

**Comment by timtjtim** [comment]
Could you add a `data-round` tag that takes a number for the number of decimal places required?

E.g. `data-round="0"` would show no decimal places. That would be ideal.

**Comment by ktsaou** [comment]
switched this to enhancement. I'll do it...

**Comment by ktsaou** [comment]
I added `data-decimal-digits' to allow us set the decimal digits of the legend values, per chart.

**Comment by fti-dpogra** [comment]
@ktsaou Decimal number is not returning custom python module

**Comment by cakrit** [comment]
Please open a new issue, so we can assist you.
