### ISSUE TITLE
Issue with the API: new Date(...) instead of a properly formatted date

### ISSUE THREAD

**Issue by alessandrousseglioviretta** [firehol/netdata#83]
A call to `/api/v1/data?chart=apps.processes` returns a _data_ array containing items of this kind:

`[ new Date(2016,2,30,17,12,44), 13, 49, 3, 1, 3, 6, 112, 2, 1, 1, 6, 1]`

where instead of `new Date(...)` one would expect a properly formatted date.

**Comment by ktsaou** [comment]
Yeah! I forgot to fix this! (it is a leftover from the Google Charts API used by the old dashboard - just go to /old/ on your netdata to see it - although this is using an old API).

For the moment use `&options=seconds` to get a timestamp, or `&options=milliseconds` to get a millisecond timestamp.

**Comment by hiendv** [comment]
@ktsaou How is it going, sir? Do you need help with a PR?

**Comment by ktsaou** [comment]
A PR would be good, yes.

However it is a bit complicated and it needs a lot of testing. The same code is used for generating google API responses, and these responses need this special formatting of the date.

If you can do it, please do so. Otherwise, I'll need some time. I have to build a test environment for the different cases and come with a solution that satisfies all cases.

**Comment by hiendv** [comment]
In my opinion, the response of REST should be valid JSON or XML. Date objects could be initialized at the client-side. So what is that google API exactly, sir?
I haven't calculated the amount of work yet but I can imagine it. Testing is inevitable.

**Comment by ktsaou** [comment]
It has been fixed with PR #1718.
Thanks!
