### ISSUE TITLE
Allow stats grouping by user?

### ISSUE THREAD

**Issue by squash** [firehol/netdata#85]
For multi-user systems, or docker hosts, tracking stats by uid would provide a very useful view.

**Comment by ktsaou** [comment]
Nice idea!

**Comment by ktsaou** [comment]
WIth the https://github.com/firehol/netdata/commit/da9e1df4cbde9208d30b99937046b667e82e88a1 commit, the following have been added:

1. Per user charts (all of the previously known as Apps Charts: cpu, memory, disk, files, sockets, pipes, swap, etc)

  these were tricky, because:
  -  I had to find a way to detect the username of all running pids without reading all the thousands of the `/proc/X/status` files. It turns out that just examining each pid /proc directory `/proc/X` (without reading any files), I could get the effective uid and gid of the process - this is very fast, just this addition did not have any impact on the profiler, and
  - tasks switch users all the time (especially samba - every few seconds), so the incremental resources consumed were transferred among users and resulted in unrealistic spikes in the charts (I solved it of course, but it required some treatment).

2. Per user group charts (all of them again)

 similar to the above - same things

3. Almost total re-write of `apps.plugin`.

  The new one is optimized too. It is 10% faster, **after the new features**, compared to the old.

4. Solved a few corner cases that were unhandled in the previous version.

Enjoy!
