### ISSUE TITLE
Interesting disk_full_after_hours alarms

### ISSUE THREAD

**Issue by jurgenhaas** [firehol/netdata#859]
This is not a bug report, it is an interesting use case of alarms where I wonder how things could be configured in a better way such that those false alarms can be avoided.

Here is what happens:

We have a couple of hosts with pretty small hard drives of 8 GB of space over all. They are utilized with around 70% and that's pretty static for the application that they host and there is no reason to increase them.

Now, when we run `apt-get update` the system is downloading the archive indexes in a short period of time which is obviously triggering the disk_full_after_jours alarms stating that the disk would be full within e.g. 14 hour if the system continued to add data at the same speed as it did in the last 30 minutes in average.

This is surprising but I see that every time I run those maintenance tasks. I haven't done the math yet but I wanted to reach out if anyone else is seeing this issue or has an explanation for what's going on. Thx.

**Comment by ktsaou** [comment]
So, here is what I have done:

1. netdata, every 15 seconds, looks up the available disk space, exactly 30 minutes ago. Based on this info, it calculates `GB/min` as `disk_fill_rate`: https://github.com/firehol/netdata/blob/020a100fd41a1859a2d0b9e26c8f4edb2fe2e872/conf.d/health.d/disks.conf#L29-L35

2. netdata, every 10 seconds, calculates the hours the disk will run out of space, if it continues writing with `disk_fill_rate`: https://github.com/firehol/netdata/blob/020a100fd41a1859a2d0b9e26c8f4edb2fe2e872/conf.d/health.d/disks.conf#L42-L49

I agree this will lead to false positives if the disk has short spikes and there is not enough disk space available.

What we could do, is instead of looking up the available disk space 30 mins ago, to find the `max` available disk space of a short duration 30+ minutes ago. This short duration should be longer than the spike we want to avoid.

So, if the max spike is for 2 minutes, we should do the lookup like this:

```
lookup: max -2m at -30m unaligned of avail
```

Set this at https://github.com/firehol/netdata/blob/020a100fd41a1859a2d0b9e26c8f4edb2fe2e872/conf.d/health.d/disks.conf#L31

If you still get false positives, increase `-2m` to `-3m` or even `-5m`. The idea is that this duration should be bigger that the spike you are trying to avoid.

If it works better like this, I'll merge it to be the default.

**Comment by jurgenhaas** [comment]
I've changed that on half of the hosts to `-2m` and watch their behaviour compared to the other half over the course of the next couple of days. I'll report back to see if this fixes the problem.

**Comment by ktsaou** [comment]
thanks!

**Comment by jurgenhaas** [comment]
I haven't seen these alarms anymore, however I haven't seen them either for the hosts where I haven't changed the default. Maybe the reason is that I had reported this before you changed the default from MB to GB?

**Comment by ktsaou** [comment]
> Maybe the reason is that I had reported this before you changed the default from MB to GB?

hm... I don't think this is related. I just changed the units, it should not affect the calculation.

**Comment by ktsaou** [comment]
I think I'll do the change after all. Absorbing 2 minute spikes seems logical. I'll make a PR.

**Comment by ktsaou** [comment]
merged it.

**Comment by ktsaou** [comment]
I found that even if `max -2m at -30m of avail` is used, it would not make such a difference because of `max`. In PR #905 I am changing this to `min -5m at -30m of avail`. This will find the lowest disk free space from -30m to -35m and compare this to current disk space available for triggering the alarm.

I hope spikes will now be eliminated...
