### ISSUE TITLE
No TCP connection to Netdata web-server.

### ISSUE THREAD

**Issue by efemerid** [firehol/netdata#872]
I've successfully used Netdata for about 1 month and after that I've updated my server (CentOS release 6.8) by `yum update`. After that Netdata web-server shown only header but no graphs. I've updated and reinstalled Netdata, faced many new problems, resolved most of it.  But now I have problem and I don't know how to deal with it. Netdata web-server stop answering. As far as I can see, backend is working, collecting data, updating databases etc. But `tcpdump tcp port 19999` shows incoming SYN-packets and no answers from Netdata web server. Please give me some directions to resolve it. And sorry for my English.

Update: everything is OK in case of local connection via lo interface, problem arise only with remote connection. This server have no global network problems, other services including nginx, apache and mysql working fine with remote users.

**Comment by LucaDev** [comment]
Could you show us your netdata config?

**Comment by efemerid** [comment]
Update: as a temporary workaround I've passed it through nginx proxy. So far so good, but I'm still curious why it stop working directly.

**Comment by efemerid** [comment]
Update: quote from error.log, is it make any sense?
```

16-09-02 10:43:44: INFO: netdata: Multi-threaded WEB SERVER thread created with task id 31127
16-09-02 10:43:44: INFO: netdata: Not starting thread web-single-threaded.
16-09-02 10:43:44: INFO: netdata: Listening on '[0.0.0.0]:19999'
16-09-02 10:43:44: INFO: netdata: Listening on '[::]:19999'
```

**Comment by ktsaou** [comment]
For the requests it does not answer, does it log anything in `/var/log/access.log`?

Using either tcpdump or your browser console (F12), can you post here the HTTP headers of the request that stalls?

The worst thing that can happen is an infinite loop in netdata. When you have sent a request that stalls, does netdata use 1 core of cpu (check its cpu utilization using `top` - if it is near 100% we have an infinite loop).

If it does not use 100% cpu, it might be a bad lock, so that the thread that serves this request waits forever. If you sent the same request using `curl` does it work? If yes, it is not that case either.

Please open netdata.conf and set `debug flags = 0x0000008E` (uncomment the line too). This will create some output on `/var/log/netdata/debug.log`. Sent the request that stalls, and post the contents of this file here.

**Comment by efemerid** [comment]
You must be a magican. I've added "Live HTTP headers" extension to my Firefox and restarted it to intercept HTTP headers, and now I cannot reproduce the problem. Everything is working flawless. I still have no idea what it was, but now all my problems are gone. Thank you.
