### ISSUE TITLE
QoS latency performance hit

### ISSUE THREAD

**Issue by mo0nsniper** [firehol/netdata#898]
Hello,

I'm running some game servers on my machine and I would like to ask how is the QoS impacting network latency performance?
Also could I measure this with netdata?

Thank you.

**Comment by ktsaou** [comment]
netdata will render any `tc` classes you have. If you also have fireqos, it will automatically collect class names.

QoS will only affect traffic under network link congestion. If you don't congest the network, QoS does virtually nothing.

**Comment by mo0nsniper** [comment]
I am using your tutorial [here](https://github.com/firehol/netdata/wiki/Monitor-application-bandwidth-with-Linux-QoS) to setup QoS. And everything works nicely with netdata.
Thank you for writing it. It is very easy to understand and to configure.

I was wondering if there is any performance hit just for adding QoS to the networking stack. From the documentation it looks like it is always used but just wanted to ask.

Right now the network link is not under congestion but I had some DDoS attacks and decided to implement QoS after seeing your tutorial. 

I also want to do some modifications to the network settings to lower latency.
What would you suggest would be the best way to measure network latency?

...Performance tunning without monitoring is bupkis :)

**Comment by ktsaou** [comment]
> I was wondering if there is any performance hit just for adding QoS to the networking stack. From the documentation it looks like it is always used but just wanted to ask.

Well, yes QoS is always applied, but if the network is not congested it should not affect anything. The whole idea with QoS is to choose which packet to forward and which one to keep in the queue. The latency due to QoS... I have never measured it but I don't believe it is measurable either (i.e. could be something at the nanosecond level - I doubt it can reach 1 microsecond).

Generally, if the network is not congested and your CPU is not high (check softirqs), you should not bother - there is nothing you can do. If you CPU is high, check your ethernet card CPU offloading options (although enabling them destroys QoS).

In most of the cases, latency comes from congested links, congested applications and bad possibly non-optimal programming.
