### ISSUE TITLE
Send alarm via Pushover

### ISSUE THREAD

**Issue by Splo0sh** [firehol/netdata#915]
Not an issue but an alarm for everyone who wants to push them via [Pushover](https://pushover.net). #826 

It's based on the `alarm-email.sh` script.
Check it out here if you want: [https://github.com/Splo0sh/netdata_pushover](https://github.com/Splo0sh/netdata_pushover).

**Comment by ktsaou** [comment]
nice! Thank you for creating this!

I can try to integrate it into `alarm-email.sh`, so that the same script will send email and push notifications (only when pushover is configured of course).

Do you want to make a PR for `alarm-pushover.sh`? I will merge it and then adapt `alarm-email.sh` so that you will appear in the commit log.

**Comment by Splo0sh** [comment]
Sure, go ahead :) I will do the PR as soon as I'm back at my desk.
Happy to assist!
