### ISSUE TITLE
How to enable example plugin?

### ISSUE THREAD

**Issue by AckRiteris** [firehol/netdata#963]
Feels dumb but I can't get it to work. Aside from editing the variable to enable this chart, is there anything else I need to do? 

I restarted netdata but that doesn't solve it. 
Checked /api/v1/charts but it does not appear to come up there.

**Comment by ktsaou** [comment]
The example plugin of BASH (charts.d.plugin) is enabled by editing `/etc/netdata/charts.d.conf`.

The example plugin of python (python.d.plugin) is enabled by editing `/etc/netdata/python.d.conf`.

**Comment by AckRiteris** [comment]
Great, knew this was something simple! By the way, why do new plugins need to be set to "force" instead of just running? enable_all_charts="yes" should enable all plugins, no?

**Comment by ktsaou** [comment]
There are overlapping plugins provided by both python.d.plugin and charts.d.plugin. Since python is more efficient than BASH, to enable a BASH plugin that exists in python, you have to force it.

**Comment by ktsaou** [comment]
Since bash plugins existed first, this was a simple solution to allow old installations accept the python ones without any configuration. So, if you had an installation of netdata 3 months old, we needed a way to prevent 2 plugins collecting the same info. So, the new charts.d.plugin requires the keyword `force` to allow its mysql data collector to run, while the python one is enabled by default.
