### ISSUE TITLE
How to correlate raised alarms to netdata graphs?

### ISSUE THREAD

**Issue by ovizii** [firehol/netdata#990]
OK; so say I get an alarm via email:

`james needs attention
net_drops.vmbr0
CHART
1hour packet drops = 3 packets 
interface dropped packets in the last hour
ALARM
vmbr0
FAMILY
WARNING
SEVERITY
Tue 20 Sep 13:41:56 CEST 2016
TIME`

How do I now find the graph which corresponds to this alarm to check it visually? 

Same question applies to going to my netdata dashboard => alarms => active - how about the option to have a clickable link for each alarm which points me to the graph which triggered the alarm?

**Comment by ktsaou** [comment]
You are right, I have to do this. Actually I don't even like the alarms modal at all. Alarms should be shown on the main menu and at the charts.

**Comment by shadycuz** [comment]
@ktsaou Yes it would be nice. I get the little notifications from chrome but clicking on them does not take you to the proper chart. That would be a nice feature.

**Comment by ktsaou** [comment]
> I get the little notifications from chrome but clicking on them does not take you to the proper chart.

Unfortunately, this is not supported by chrome (or any other browser). I have tried it already...

**Comment by ktsaou** [comment]
Well it is supported. I found out how. Making a PR now...

**Comment by ktsaou** [comment]
The alarms are clickable and the alarms pop-up also has links to the related charts. it is in PR #1014.

**Comment by shadycuz** [comment]
I thought so =) , my Facebook notifications are links but I wasn't sure if
the way they were implemented in netdata was the same.

**Comment by shadycuz** [comment]
I thought so =) , my Facebook notifications are links but I wasn't sure if
the way they were implemented in netdata was the same.

On Sep 23, 2016 4:56 PM, "Costa Tsaousis" <notifications@github.com> wrote:

Well it is supported. I found out how. Making a PR now...

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/firehol/netdata/issues/990#issuecomment-249300200>, or mute
the thread

**Comment by ktsaou** [comment]
unfortunately, there are a million ways to make notifications. I tried to follow the standards and implement HTML5 notifications, according to book. It was not clear how on-click works. I tried a few way, they didn't work and I assumed this is somehow non-standard.

Today, I decided to take a closer look, so here they are... I also made a few more changes to make the alarms somewhat more user friendly.

I still believe, alarms should be embedded in the dashboard. May be at the next version (I plan to make quite a few changes on the dashboard to embed all documentation in it - so, I'll try to implement this feature with all these changes).

**Comment by shadycuz** [comment]
Yes I think alarms should be right under the system overview and should also be linked to the appropriate section. I need to finish my python course so that I can try to make some small contributions to the code base. When I look at sections of code I understand what it does but not how it works as a whole,  if that makes any sense.  

Glad you was able to find a solution to the notifications.

**Comment by ktsaou** [comment]
merged it!
